#include "Game/Scene/SceneNameObjListExecutor.hpp"
#include "Game/Scene/SceneFunction.hpp"

namespace {
    const CategoryListInitialTable cMovementListInitTable[] = {
        {
            MR::MovementType_UNK_0x00,
            1,
        },
        {
            MR::MovementType_StopSceneDelayRequest,
            16,
        },
        {
            MR::MovementType_Camera,
            1,
        },
        {
            MR::MovementType_ScreenEffect,
            16,
        },
        {
            MR::MovementType_ClippingDirector,
            1,
        },
        {
            MR::MovementType_SensorHitChecker,
            1,
        },
        {
            MR::MovementType_MsgSharedGroup,
            32,
        },
        {
            MR::MovementType_UNK_0x07,
            16,
        },
        {
            MR::MovementType_UNK_0x08,
            1,
        },
        {
            MR::MovementType_AudCameraWatcher,
            1,
        },
        {
            MR::MovementType_TalkDirector,
            1,
        },
        {
            MR::MovementType_SwitchWatcherHolder,
            1,
        },
        {
            MR::MovementType_DemoDirector,
            1,
        },
        {
            MR::MovementType_UNK_0x0C,
            32,
        },
        {
            MR::MovementType_AreaObj,
            256,
        },
        {
            MR::MovementType_Layout,
            96,
        },
        {
            MR::MovementType_LayoutDecoration,
            32,
        },
        {
            MR::MovementType_Movie,
            1,
        },
        {
            MR::MovementType_MovieSubtitles,
            8,
        },
        {
            MR::MovementType_WipeLayout,
            8,
        },
        {
            MR::MovementType_LayoutOnPause,
            16,
        },
        {
            MR::MovementType_MirrorCamera,
            1,
        },
        {
            MR::MovementType_AudEffectDirector,
            1,
        },
        {
            MR::MovementType_AudBgmConductor,
            1,
        },
        {
            MR::MovementType_CollisionDirector,
            1,
        },
        {
            MR::MovementType_ShadowControllerHolder,
            1,
        },
        {
            MR::MovementType_CameraCover,
            1,
        },
        {
            MR::MovementType_Planet,
            96,
        },
        {
            MR::MovementType_Player,
            16,
        },
        {
            MR::MovementType_PlayerDecoration,
            32,
        },
        {
            MR::MovementType_PlayerMessenger,
            1,
        },
        {
            MR::MovementType_NPC,
            96,
        },
        {
            MR::MovementType_CollisionEnemy,
            128,
        },
        {
            MR::MovementType_Enemy,
            1024,
        },
        {
            MR::MovementType_EnemyDecoration,
            768,
        },
        {
            MR::MovementType_UNK_0x15,
            64,
        },
        {
            MR::MovementType_ClippedMapParts,
            2048,
        },
        {
            MR::MovementType_CollisionMapObj,
            1024,
        },
        {
            MR::MovementType_Ride,
            256,
        },
        {
            MR::MovementType_MapObj,
            2048,
        },
        {
            MR::MovementType_MapObjDecoration,
            512,
        },
        {
            MR::MovementType_Item,
            512,
        },
        {
            MR::MovementType_Environment,
            512,
        },
        {
            MR::MovementType_Sky,
            8,
        },
        {
            MR::MovementType_ImageEffect,
            4,
        },
        {
            MR::MovementType_UNK_0x14,
            1,
        },
        {
            -1,  // TODO "None" MovementType name?
            0,
        },
    };
    const CategoryListInitialTable cCalcAnimListInitTable[] = {
        {
            MR::CalcAnimType_UNK_0x15,
            1,
        },
        {
            MR::CalcAnimType_Layout,
            96,
        },
        {
            MR::CalcAnimType_LayoutDecoration,
            32,
        },
        {
            MR::CalcAnimType_MovieSubtitles,
            8,
        },
        {
            MR::CalcAnimType_Player,
            8,
        },
        {
            MR::CalcAnimType_PlayerDecoration,
            32,
        },
        {
            MR::CalcAnimType_NPC,
            96,
        },
        {
            MR::CalcAnimType_Enemy,
            2048,
        },
        {
            MR::CalcAnimType_CollisionEnemy,
            128,
        },
        {
            MR::CalcAnimType_ClippedMapParts,
            1280,
        },
        {
            MR::CalcAnimType_CollisionMapObj,
            1024,
        },
        {
            MR::CalcAnimType_MapObj,
            1280,
        },
        {
            MR::CalcAnimType_Ride,
            256,
        },
        {
            MR::CalcAnimType_MapObjDecoration,
            768,
        },
        {
            MR::CalcAnimType_MirrorMapObj,
            256,
        },
        {
            MR::CalcAnimType_Item,
            512,
        },
        {
            MR::CalcAnimType_Planet,
            96,
        },
        {
            MR::CalcAnimType_Environment,
            512,
        },
        {
            MR::CalcAnimType_UNK_0x11,
            128,
        },
        {
            MR::CalcAnimType_UNK_0x12,
            128,
        },
        {
            MR::CalcAnimType_AnimParticle,
            1,
        },
        {
            MR::CalcAnimType_AnimParticleIgnorePause,
            2,
        },
        {
            -1,  // TODO "None" CalcAnimType name?
            0,
        },
    };
    const DrawBufferInitialTable cDrawBufferListInitTable[] = {
        {
            MR::DrawBufferType_0x26,
            16,
            MR::LightType_None,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_Planet,
            64,
            MR::LightType_Planet,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_IndirectPlanet,
            64,
            MR::LightType_Planet,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_Player,
            4,
            MR::LightType_Player,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_PlayerDecoration,
            8,
            MR::LightType_Player,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_CrystalBox,
            8,
            MR::LightType_Player,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_UNK_0x17,
            1,
            MR::LightType_Weak,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_NPC,
            80,
            MR::LightType_Strong,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_Enemy,
            64,
            MR::LightType_Strong,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_EnemyDecoration,
            64,
            MR::LightType_Strong,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_TripodBoss,
            64,
            MR::LightType_Strong,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_ClippedMapParts,
            32,
            MR::LightType_Planet,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_UNK_0x18,
            64,
            MR::LightType_Planet,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_IndirectMapObj,
            64,
            MR::LightType_Planet,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_IndirectMapObjStrongLight,
            64,
            MR::LightType_Planet,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_IndirectNpc,
            16,
            MR::LightType_Strong,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_IndirectEnemy,
            64,
            MR::LightType_Strong,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_0x28,
            64,
            MR::LightType_Planet,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_Ride,
            32,
            MR::LightType_Strong,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_NoShadowedMapObj,
            64,
            MR::LightType_Planet,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_NoShadowedMapObjStrongLight,
            64,
            MR::LightType_Strong,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_NoSilhouettedMapObj,
            64,
            MR::LightType_Planet,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_NoSilhouettedMapObjWeakLight,
            64,
            MR::LightType_Weak,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_NoSilhouettedMapObjStrongLight,
            64,
            MR::LightType_Strong,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_MapObj,
            256,
            MR::LightType_Planet,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_MapObjWeakLight,
            32,
            MR::LightType_Weak,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_MapObjStrongLight,
            64,
            MR::LightType_Strong,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_MirrorMapObj,
            256,
            MR::LightType_Planet,
            MR::CameraType_Mirror,
        },
        {
            MR::DrawBufferType_Crystal,
            8,
            MR::LightType_Planet,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_CrystalItem,
            8,
            MR::LightType_Strong,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_GlaringLight,
            8,
            MR::LightType_Planet,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_PlanetLow,
            64,
            MR::LightType_Planet,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_Sky,
            4,
            MR::LightType_Planet,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_Air,
            8,
            MR::LightType_Planet,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_Sun,
            4,
            MR::LightType_Planet,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_Environment,
            64,
            MR::LightType_Planet,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_EnvironmentStrongLight,
            64,
            MR::LightType_Planet,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_AstroDomeSky,
            1,
            MR::LightType_Planet,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_BloomModel,
            16,
            MR::LightType_Planet,
            MR::CameraType_3D,
        },
        {
            MR::DrawBufferType_Model3DFor2D,
            16,
            MR::LightType_None,
            MR::CameraType_2D,
        },
        {
            MR::DrawBufferType_0x25,
            16,
            MR::LightType_None,
            MR::CameraType_2D,
        },
        {
            -1,  // TODO "None" DrawBufferType name?
            0,
            MR::LightType_None,
            MR::CameraType_3D,
        },
    };
    const CategoryListInitialTable cDrawListInitTable[] = {
        {
            MR::DrawType_Layout,
            128,
        },
        {
            MR::DrawType_LayoutDecoration,
            32,
        },
        {
            MR::DrawType_LayoutOnPause,
            32,
        },
        {
            MR::DrawType_Movie,
            1,
        },
        {
            MR::DrawType_MovieSubtitles,
            8,
        },
        {
            MR::DrawType_WipeLayout,
            8,
        },
        {
            MR::DrawType_CometScreenFilter,
            3,
        },
        {
            MR::DrawType_TalkLayout,
            32,
        },
        {
            MR::DrawType_0x44,
            32,
        },
        {
            MR::DrawType_CinemaFrame,
            1,
        },
        {
            MR::DrawType_CaptureScreenIndirect,
            1,
        },
        {
            MR::DrawType_CenterScreenBlur,
            2,
        },
        {
            MR::DrawType_0x30,
            16,
        },
        {
            MR::DrawType_Fur,
            1,
        },
        {
            MR::DrawType_0x3B,
            1,
        },
        {
            MR::DrawType_GalaxyNamePlate,
            1,
        },
        {
            MR::DrawType_CaptureScreenCamera,
            1,
        },
        {
            MR::DrawType_MessageBoardCapture,
            1,
        },
        {
            MR::DrawType_CameraCover,
            1,
        },
        {
            MR::DrawType_ShadowSurface,
            256,
        },
        {
            MR::DrawType_ShadowVolume,
            1024,
        },
        {
            MR::DrawType_0x28,
            4,
        },
        {
            MR::DrawType_AlphaShadow,
            1,
        },
        {
            MR::DrawType_OceanBowl,
            8,
        },
        {
            MR::DrawType_OceanRing,
            16,
        },
        {
            MR::DrawType_OceanRingPipeInside,
            8,
        },
        {
            MR::DrawType_OceanRingPipeOutside,
            8,
        },
        {
            MR::DrawType_OceanSphere,
            8,
        },
        {
            MR::DrawType_WaterRoad,
            16,
        },
        {
            MR::DrawType_WhirlPoolAccelerator,
            64,
        },
        {
            MR::DrawType_0x33,
            1,
        },
        {
            MR::DrawType_DashRing,
            16,
        },
        {
            MR::DrawType_BrightSun,
            16,
        },
        {
            MR::DrawType_WaterCameraFilter,
            1,
        },
        {
            MR::DrawType_Player,
            4,
        },
        {
            MR::DrawType_0x23,
            4,
        },
        {
            MR::DrawType_0x24,
            4,
        },
        {
            MR::DrawType_MiiFacePartsHolder,
            1,
        },
        {
            MR::DrawType_MiiFaceIcon,
            1,
        },
        {
            MR::DrawType_MiiFaceNew,
            1,
        },
        {
            MR::DrawType_KirairaChain,
            64,
        },
        {
            MR::DrawType_VolumeModel,
            64,
        },
        {
            MR::DrawType_0x20,
            8,
        },
        {
            MR::DrawType_SwingRope,
            256,
        },
        {
            MR::DrawType_Creeper,
            64,
        },
        {
            MR::DrawType_0x1,
            64,
        },
        {
            MR::DrawType_0x3,
            64,
        },
        {
            MR::DrawType_PlantStalk,
            64,
        },
        {
            MR::DrawType_Plant,
            64,
        },
        {
            MR::DrawType_Trapeze,
            64,
        },
        {
            MR::DrawType_ElectricRailHolder,
            1,
        },
        {
            MR::DrawType_DrawType_BigBubble,
            1,
        },
        {
            MR::DrawType_BigBubbleGoal,
            32,
        },
        {
            MR::DrawType_0x11,
            64,
        },
        {
            MR::DrawType_0x17,
            32,
        },
        {
            MR::DrawType_WarpPodPath,
            256,
        },
        {
            MR::DrawType_FlexibleSphere,
            16,
        },
        {
            MR::DrawType_FallOutFieldDraw,
            1,
        },
        {
            MR::DrawType_ClipFieldFillDraw,
            1,
        },
        {
            MR::DrawType_ClipArea,
            256,
        },
        {
            MR::DrawType_SpinDriverPathDrawer,
            64,
        },
        {
            MR::DrawType_GCapture,
            64,
        },
        {
            MR::DrawType_ClipAreaDropLaser,
            64,
        },
        {
            MR::DrawType_SpiderThread,
            1,
        },
        {
            MR::DrawType_SpaceCocoon,
            64,
        },
        {
            MR::DrawType_0x32,
            2,
        },
        {
            MR::DrawType_AstroDomeSkyClear,
            1,
        },
        {
            MR::DrawType_AstroDomeOrbit,
            8,
        },
        {
            MR::DrawType_WaterPlant,
            256,
        },
        {
            MR::DrawType_Flag,
            1024,
        },
        {
            MR::DrawType_BloomEffectPreDraw,
            1,
        },
        {
            MR::DrawType_BloomEffectPostDraw,
            1,
        },
        {
            MR::DrawType_BloomModel,
            64,
        },
        {
            MR::DrawType_OceanBowlBloomDrawer,
            32,
        },
        {
            MR::DrawType_ImageEffect,
            4,
        },
        {
            MR::DrawType_EffectDraw3D,
            1,
        },
        {
            MR::DrawType_EffectDrawIndirect,
            1,
        },
        {
            MR::DrawType_EffectDrawAfterIndirect,
            1,
        },
        {
            MR::DrawType_EffectDrawForBloomEffect,
            1,
        },
        {
            MR::DrawType_EffectDrawAfterImageEffect,
            1,
        },
        {
            MR::DrawType_EffectDraw2D,
            2,
        },
        {
            MR::DrawType_EffectDrawFor2DModel,
            1,
        },
        {
            MR::DrawType_0x52,
            256,
        },
        {
            -1,  // TODO "None" DrawType name?
            0,
        },
    };
    static bool sVar = true;
};  // namespace

void SceneNameObjListExecutor::initMovementList() {
    mMovementList = new NameObjCategoryList(sizeof(cMovementListInitTable) / sizeof(*cMovementListInitTable) - 1, cMovementListInitTable,
                                            &NameObj::executeMovement, sVar, "");
}

void SceneNameObjListExecutor::initCalcAnimList() {
    mCalcAnimList = new NameObjCategoryList(sizeof(cCalcAnimListInitTable) / sizeof(*cCalcAnimListInitTable) - 1, cCalcAnimListInitTable,
                                            &NameObj::calcAnim, sVar, "");
}

void SceneNameObjListExecutor::initCalcViewAndEntryList() {
    mBufferHolder = new DrawBufferHolder();
    mBufferHolder->initTable(cDrawBufferListInitTable, sizeof(cDrawBufferListInitTable) / sizeof(*cDrawBufferListInitTable) - 1);
}

void SceneNameObjListExecutor::initDrawList() {
    mDrawList = new NameObjCategoryList(sizeof(cDrawListInitTable) / sizeof(*cDrawListInitTable) - 1, cDrawListInitTable, &NameObj::draw, sVar, "");
}
