INIT_O_FILES := 						            \
	$(BUILD_DIR)/asm/init.o

EXTAB_O_FILES :=                                    \
    $(BUILD_DIR)/asm/extab.o

EXTABINDEX_O_FILES :=                               \
    $(BUILD_DIR)/asm/extabindex.o

NW4R_O_FILES := 					            \
    $(BUILD_DIR)/asm/nw4r/libnw4r_ut.o   \
    $(BUILD_DIR)/asm/nw4r/libnw4r_db.o   \
    $(BUILD_DIR)/asm/nw4r/libnw4r_math.o   \
    $(BUILD_DIR)/asm/nw4r/libnw4r_lyt.o   \

GAME_ANIM_O_FILES := \
    $(BUILD_DIR)/asm/Game/Animation/AnmPlayer.o \
    $(BUILD_DIR)/asm/Game/Animation/BckCtrl.o \
    $(BUILD_DIR)/asm/Game/Animation/BpkPlayer.o \
    $(BUILD_DIR)/asm/Game/Animation/BrkPlayer.o \
    $(BUILD_DIR)/asm/Game/Animation/BtkPlayer.o \
    $(BUILD_DIR)/asm/Game/Animation/BtpPlayer.o \
    $(BUILD_DIR)/asm/Game/Animation/BvaPlayer.o \
    $(BUILD_DIR)/asm/Game/Animation/LayoutAnmPlayer.o \
    $(BUILD_DIR)/asm/Game/Animation/MaterialAnmBuffer.o \
    $(BUILD_DIR)/asm/Game/Animation/XanimeCore.o \
    $(BUILD_DIR)/asm/Game/Animation/XanimePlayer.o \
    $(BUILD_DIR)/asm/Game/Animation/XanimeResource.o

AREAOBJ_O_FILES := \
    $(BUILD_DIR)/asm/Game/AreaObj/data.o \
    $(BUILD_DIR)/asm/Game/AreaObj/AreaForm.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/AreaFormDrawer.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/AreaObj.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/AreaObjContainer.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/AreaObjFollower.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/AstroChangeStageCube.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/AudioEffectArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/BgmProhibitArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/BigBubbleCameraArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/BigBubbleGoalArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/BloomArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/CameraRepulsiveArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/ChangeBgmCube.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/CollisionArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/CubeCamera.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/DeathArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/DepthOfFieldArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/FollowCollisionArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/GlaringLightArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/HazeCube.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/ImageEffectArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/LightArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/LightAreaHolder.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/MercatorTransformCube.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/MessageArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/PlayerSeArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/QuakeEffectArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/RestartCube.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/ScreenBlurArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/SimpleBloomArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/SoundEmitterCube.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/SoundEmitterSphere.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/SpinGuidanceArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/SunLightArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/SwitchArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/WarpCube.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/WaterArea.o 

TEXT_O_FILES :=     \
    $(BUILD_DIR)/asm/Game/AudioLib/data.o \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSystem.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSystemVolumeController.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudAudience.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSoundInfo.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudWrap.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSoundObject.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSoundObject_Kawamura.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSoundObject_Takezawa.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSoundObject_Gohara.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudAnmSoundObject.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudBgm.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudBgmKeeper.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudBgmMgr.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudBgmRhythmStrategy.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudBgmSetting.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudBgmVolumeController.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudEffector.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudFader.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudLimitedSound.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudMeNameConverter.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudMicWrap.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudRemixMgr.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudRemixSequencer.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSceneMgr.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSeStrategy.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSoundNameConverter.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSoundObjHolder.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSpeakerWrap.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudTrackController.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudUtil.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/OverwriteJAudio.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/CSSoundNameConverter.o    \
    $(BUILD_DIR)/asm/Game/Boss/data.o \
    $(BUILD_DIR)/asm/Game/Boss/BossAccessor.o \
    $(BUILD_DIR)/asm/Game/Boss/BossBegoman/BossBegoman.o \
    $(BUILD_DIR)/asm/Game/Boss/BossBegoman/BossBegomanHead.o \
    $(BUILD_DIR)/asm/Game/Boss/BossKameck/BossKameck.o \
    $(BUILD_DIR)/asm/Game/Boss/BossKameck/BossKameckAction.o \
    $(BUILD_DIR)/asm/Game/Boss/BossKameck/BossKameckBarrier.o \
    $(BUILD_DIR)/asm/Game/Boss/BossKameck/BossKameckBattleDemo.o \
    $(BUILD_DIR)/asm/Game/Boss/BossKameck/BossKameckBattlePattarn.o \
    $(BUILD_DIR)/asm/Game/Boss/BossKameck/BossKameckSequencer.o \
    $(BUILD_DIR)/asm/Game/Boss/BossKameck/BossKameckMoveRail.o \
    $(BUILD_DIR)/asm/Game/Boss/BossKameck/BossKameckVs1.o \
    $(BUILD_DIR)/asm/Game/Boss/BossKameck/BossKameckVs2.o \
    $(BUILD_DIR)/asm/Game/Boss/BossKameck/BossKameckStateBattle.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBug.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugActionBase.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugActionFlyHigh.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugActionFlyLow.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugActionGround.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugActionSequencer.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugAngryDemo.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugBomb.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugBombHolder.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugFinishDemo.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugFlyDemo.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugFunction.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugOpeningDemo.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackun.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunAction.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunBall.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunBattleEgg.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunBattleEggVs2.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunBattleVs1Lv1.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunBattleVs1Lv2.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunBattleVs2Lv1.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunDemo.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunDemoPosition.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunEggShell.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunFire.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunSequencer.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunStateAwake.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunStateDamage.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunStateFire.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunTail.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunTailNode.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunTailPart.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunTailRoot.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunTrackFire.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunVs1.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunVs2.o \
    $(BUILD_DIR)/asm/Game/Boss/Dodoryu/Dodoryu.o \
    $(BUILD_DIR)/asm/Game/Boss/Dodoryu/DodoryuDemo.o \
    $(BUILD_DIR)/asm/Game/Boss/Dodoryu/DodoryuHill.o \
    $(BUILD_DIR)/asm/Game/Boss/Dodoryu/DodoryuMove.o \
    $(BUILD_DIR)/asm/Game/Boss/Dodoryu/DodoryuStateBase.o \
    $(BUILD_DIR)/asm/Game/Boss/Dodoryu/DodoryuStateLv1.o \
    $(BUILD_DIR)/asm/Game/Boss/Dodoryu/DodoryuStateLv2.o \
    $(BUILD_DIR)/asm/Game/Boss/Dodoryu/DodoryuStateWait.o \
    $(BUILD_DIR)/asm/Game/Boss/Dodoryu/DodoryuUtil.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/Koopa.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaBattleBase.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaBattleMain.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaBattleStairsBase.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaBattleStairsVs1.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaBattleStairsVs3.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaBattleVs3Lv1.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaBattleVs3Lv2.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaDemoPowerUp.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaDemoFallToPlanetVs3Lv2.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaDemoFallToPlanetVs3Lv3.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaDemoJumpToPlanet.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaFigureBall.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaFireShort.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaFireStairs.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaFunction.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaParts.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaPowerUpSwitch.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaPlanetShadow.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaRestarterVs3.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaRockBreak.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaSensorCtrl.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaSequencer.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaSubSequenceBattle.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaSequencerVs1.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaSequencerVs2.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaSequencerVs3.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaShockWave.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaStateAttackFireShort.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaStateAttackFireLong.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaStateAttackHipDrop.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaStateAttackRoll.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaStateAttackShockWave.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaStateAttackSpin.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaStateChaseRoll.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaStateDamageEscape.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaStateGuard.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaStateJumpAway.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaSwitchKeeper.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaViewSwitchKeeper.o \
    $(BUILD_DIR)/asm/Game/Boss/OtaKing/OtaKing.o \
    $(BUILD_DIR)/asm/Game/Boss/OtaKing/OtaKingLongFoot.o \
    $(BUILD_DIR)/asm/Game/Boss/OtaKing/OtaKingMagma.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/Polta.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaActionBase.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaActionSequencer.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaArm.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaBattleLv1.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaBattleLv2.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaDemo.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaFunction.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaGroundRock.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaGroundRockHolder.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaRock.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaRockHolder.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaSensorCtrl.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaStateAttackGround.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaStateGenerateRock.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaStateGroundRockAttack.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaStatePunch.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaStateStagger.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaWaitStart.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishBaby.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishBabyRail.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishBabyRailHolder.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishBoss.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishBossBattleDirector.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishBossFunc.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishBossInfo.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishBossRail.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishBossRailHolder.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishGuard.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishGuardHolder.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishJointCalc.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishRailControl.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpider.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderAcid.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderAction1st.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderAction2nd.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderActionBase.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderActionCocoon.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderDemo.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderEnvironment.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderFunction.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderGland.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderParts.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderSensorCtrl.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderStateSwoon.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderThreadAttacher.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderVitalSpot.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBoss.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossAccesser.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossBaseJointPosition.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossBreakMovement.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossCoin.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossCore.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossFixParts.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossFixPartsBase.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossGuardWall.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossGuardWallPart.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossKillerGenerater.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossKillerGeneraterCircle.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossKinokoOneUp.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossLeg.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossMovableArea.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossRailMoveParts.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossRotateParts.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossShell.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossStepPoint.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossStepSequence.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossStepStartArea.o \
    $(BUILD_DIR)/asm/Game/Camera/Camera.o \
    $(BUILD_DIR)/asm/Game/Demo/data.o \
    $(BUILD_DIR)/asm/Game/Demo/rodata.o \
    $(BUILD_DIR)/asm/Game/Demo/AstroDemoStarter.o \
    $(BUILD_DIR)/asm/Game/Demo/AstroDemoFunction.o \
    $(BUILD_DIR)/asm/Game/Demo/DemoActionKeeper.o \
    $(BUILD_DIR)/asm/Game/Demo/DemoCameraFunction.o \
    $(BUILD_DIR)/asm/Game/Demo/DemoCameraKeeper.o \
    $(BUILD_DIR)/asm/Game/Demo/DemoCastGroup.o \
    $(BUILD_DIR)/asm/Game/Demo/DemoCastGroupHolder.o \
    $(BUILD_DIR)/asm/Game/Demo/DemoCastSubGroup.o \
    $(BUILD_DIR)/asm/Game/Demo/DemoDirector.o \
    $(BUILD_DIR)/asm/Game/Demo/DemoExecutor.o \
    $(BUILD_DIR)/asm/Game/Demo/DemoFunction.o \
    $(BUILD_DIR)/asm/Game/Demo/DemoKoopaJrShip.o \
    $(BUILD_DIR)/asm/Game/Demo/DemoPadRumbler.o \
    $(BUILD_DIR)/asm/Game/Demo/DemoParamCommonDataTable.o \
    $(BUILD_DIR)/asm/Game/Demo/DemoPlayerKeeper.o \
    $(BUILD_DIR)/asm/Game/Demo/DemoPositionController.o \
    $(BUILD_DIR)/asm/Game/Demo/DemoSimpleCastHolder.o \
    $(BUILD_DIR)/asm/Game/Demo/DemoSoundKeeper.o \
    $(BUILD_DIR)/asm/Game/Demo/DemoStartRequestHolder.o \
    $(BUILD_DIR)/asm/Game/Demo/DemoStartRequestUtil.o \
    $(BUILD_DIR)/asm/Game/Demo/DemoSubPartKeeper.o \
    $(BUILD_DIR)/asm/Game/Demo/DemoTalkAnimCtrl.o \
    $(BUILD_DIR)/asm/Game/Demo/DemoTimeKeeper.o \
    $(BUILD_DIR)/asm/Game/Demo/DemoWipeKeeper.o \
    $(BUILD_DIR)/asm/Game/Demo/GrandStarReturnDemoStarter.o \
    $(BUILD_DIR)/asm/Game/Demo/PrologueDirector.o \
    $(BUILD_DIR)/asm/Game/Demo/ReturnDemoRailMove.o \
    $(BUILD_DIR)/asm/Game/Demo/ScenarioStarter.o \
    $(BUILD_DIR)/asm/Game/Demo/StarReturnDemoStarter.o \
    $(BUILD_DIR)/asm/Game/Effect/data.o \
    $(BUILD_DIR)/asm/Game/Effect/AstroEffectObj.o \
    $(BUILD_DIR)/asm/Game/Effect/AutoEffectGroup.o \
    $(BUILD_DIR)/asm/Game/Effect/AutoEffectGroupHolder.o \
    $(BUILD_DIR)/asm/Game/Effect/AutoEffectInfo.o \
    $(BUILD_DIR)/asm/Game/Effect/EffectObjGravityDust.o \
    $(BUILD_DIR)/asm/Game/Effect/EffectSystem.o \
    $(BUILD_DIR)/asm/Game/Effect/EffectSystemUtil.o \
    $(BUILD_DIR)/asm/Game/Effect/MultiEmitter.o \
    $(BUILD_DIR)/asm/Game/Effect/MultiEmitterAccess.o \
    $(BUILD_DIR)/asm/Game/Effect/MultiEmitterCallBack.o \
    $(BUILD_DIR)/asm/Game/Effect/MultiEmitterParticleCallBack.o \
    $(BUILD_DIR)/asm/Game/Effect/ParticleCalcExecutor.o \
    $(BUILD_DIR)/asm/Game/Effect/ParticleDrawExecutor.o \
    $(BUILD_DIR)/asm/Game/Effect/ParticleEmitter.o \
    $(BUILD_DIR)/asm/Game/Effect/ParticleEmitterHolder.o \
    $(BUILD_DIR)/asm/Game/Effect/ParticleResourceHolder.o \
    $(BUILD_DIR)/asm/Game/Effect/RandomEffectObj.o \
    $(BUILD_DIR)/asm/Game/Effect/SimpleEffectObj.o \
    $(BUILD_DIR)/asm/Game/Effect/SingleEmitter.o \
    $(BUILD_DIR)/asm/Game/Effect/SpinPullParticleCallBack.o \
    $(BUILD_DIR)/asm/Game/Effect/SyncBckEffectChecker.o \
    $(BUILD_DIR)/asm/Game/Effect/SyncBckEffectInfo.o \
    $(BUILD_DIR)/asm/Game/Enemy/data.o \
    $(BUILD_DIR)/asm/Game/Enemy/AnimScaleController.o \
    $(BUILD_DIR)/asm/Game/Enemy/AnimStampController.o \
    $(BUILD_DIR)/asm/Game/Enemy/BallBeamer.o \
    $(BUILD_DIR)/asm/Game/Enemy/Balloonfish.o \
    $(BUILD_DIR)/asm/Game/Enemy/BasaBasa.o \
    $(BUILD_DIR)/asm/Game/Enemy/BegomanBaby.o \
    $(BUILD_DIR)/asm/Game/Enemy/BegomanBase.o \
    $(BUILD_DIR)/asm/Game/Enemy/BegomanFunction.o \
    $(BUILD_DIR)/asm/Game/Enemy/BegomanLauncher.o \
    $(BUILD_DIR)/asm/Game/Enemy/BegomanSpike.o \
    $(BUILD_DIR)/asm/Game/Enemy/BegomanSpring.o \
    $(BUILD_DIR)/asm/Game/Enemy/BegomanSpringHead.o \
    $(BUILD_DIR)/asm/Game/Enemy/Birikyu.o \
    $(BUILD_DIR)/asm/Game/Enemy/BombBird.o \
    $(BUILD_DIR)/asm/Game/Enemy/BombBirdBomb.o \
    $(BUILD_DIR)/asm/Game/Enemy/BombHei.o \
    $(BUILD_DIR)/asm/Game/Enemy/BombHeiLauncher.o \
    $(BUILD_DIR)/asm/Game/Enemy/BombTeresa.o \
    $(BUILD_DIR)/asm/Game/Enemy/CannonShellBase.o \
    $(BUILD_DIR)/asm/Game/Enemy/CocoNutBall.o \
    $(BUILD_DIR)/asm/Game/Enemy/CocoSambo.o \
    $(BUILD_DIR)/asm/Game/Enemy/DharmaSambo.o \
    $(BUILD_DIR)/asm/Game/Enemy/Dossun.o \
    $(BUILD_DIR)/asm/Game/Enemy/ElectricPressureBullet.o \
    $(BUILD_DIR)/asm/Game/Enemy/EyeBeamer.o \
    $(BUILD_DIR)/asm/Game/Enemy/FireBall.o \
    $(BUILD_DIR)/asm/Game/Enemy/FireBubble.o \
    $(BUILD_DIR)/asm/Game/Enemy/Gesso.o \
    $(BUILD_DIR)/asm/Game/Enemy/HammerHeadPackun.o \
    $(BUILD_DIR)/asm/Game/Enemy/Hanachan.o \
    $(BUILD_DIR)/asm/Game/Enemy/HomingKiller.o \
    $(BUILD_DIR)/asm/Game/Enemy/IceMerameraKing.o \
    $(BUILD_DIR)/asm/Game/Enemy/ItemGenerator.o \
    $(BUILD_DIR)/asm/Game/Enemy/Jellyfish.o \
    $(BUILD_DIR)/asm/Game/Enemy/JellyfishElectric.o \
    $(BUILD_DIR)/asm/Game/Enemy/Jiraira.o \
    $(BUILD_DIR)/asm/Game/Enemy/JumpBeamer.o \
    $(BUILD_DIR)/asm/Game/Enemy/JumpGuarder.o \
    $(BUILD_DIR)/asm/Game/Enemy/JumpSpider.o \
    $(BUILD_DIR)/asm/Game/Enemy/Kabokuri.o \
    $(BUILD_DIR)/asm/Game/Enemy/KabokuriFire.o \
    $(BUILD_DIR)/asm/Game/Enemy/KabokuriFireHolder.o \
    $(BUILD_DIR)/asm/Game/Enemy/Kameck.o \
    $(BUILD_DIR)/asm/Game/Enemy/KameckBeam.o \
    $(BUILD_DIR)/asm/Game/Enemy/KameckBeamHolder.o \
    $(BUILD_DIR)/asm/Game/Enemy/KameckFireBall.o \
    $(BUILD_DIR)/asm/Game/Enemy/KameckHolder.o \
    $(BUILD_DIR)/asm/Game/Enemy/KameckTurtle.o \
    $(BUILD_DIR)/asm/Game/Enemy/Kanina.o \
    $(BUILD_DIR)/asm/Game/Enemy/Karikari.o \
    $(BUILD_DIR)/asm/Game/Enemy/KarikariDirector.o \
    $(BUILD_DIR)/asm/Game/Enemy/Karon.o \
    $(BUILD_DIR)/asm/Game/Enemy/Kiraira.o \
    $(BUILD_DIR)/asm/Game/Enemy/KirairaChain.o \
    $(BUILD_DIR)/asm/Game/Enemy/KoopaJrShip.o \
    $(BUILD_DIR)/asm/Game/Enemy/KoopaJrShipCannonMainShell.o \
    $(BUILD_DIR)/asm/Game/Enemy/KoopaJrShipCannonShell.o \
    $(BUILD_DIR)/asm/Game/Enemy/KoteBug.o \
    $(BUILD_DIR)/asm/Game/Enemy/Kuribo.o \
    $(BUILD_DIR)/asm/Game/Enemy/KuriboChief.o \
    $(BUILD_DIR)/asm/Game/Enemy/KuriboMini.o \
    $(BUILD_DIR)/asm/Game/Enemy/MechanicKoopaMini.o \
    $(BUILD_DIR)/asm/Game/Enemy/Meramera.o \
    $(BUILD_DIR)/asm/Game/Enemy/Metbo.o \
    $(BUILD_DIR)/asm/Game/Enemy/Mogu.o \
    $(BUILD_DIR)/asm/Game/Enemy/Mogucchi.o \
    $(BUILD_DIR)/asm/Game/Enemy/MogucchiHill.o \
    $(BUILD_DIR)/asm/Game/Enemy/MogucchiRefuseTerritory.o \
    $(BUILD_DIR)/asm/Game/Enemy/MogucchiShooter.o \
    $(BUILD_DIR)/asm/Game/Enemy/MoguStone.o \
    $(BUILD_DIR)/asm/Game/Enemy/NokonokoLand.o \
    $(BUILD_DIR)/asm/Game/Enemy/Onimasu.o \
    $(BUILD_DIR)/asm/Game/Enemy/OnimasuJump.o \
    $(BUILD_DIR)/asm/Game/Enemy/OnimasuPivot.o \
    $(BUILD_DIR)/asm/Game/Enemy/OtaRock.o \
    $(BUILD_DIR)/asm/Game/Enemy/PackunPetit.o \
    $(BUILD_DIR)/asm/Game/Enemy/Petari.o \
    $(BUILD_DIR)/asm/Game/Enemy/Poihana.o \
    $(BUILD_DIR)/asm/Game/Enemy/Pukupuku.o \
    $(BUILD_DIR)/asm/Game/Enemy/RingBeam.o \
    $(BUILD_DIR)/asm/Game/Enemy/RingBeamer.o \
    $(BUILD_DIR)/asm/Game/Enemy/SamboFunction.o \
    $(BUILD_DIR)/asm/Game/Enemy/SamboHead.o \
    $(BUILD_DIR)/asm/Game/Enemy/SearchBeamer.o \
    $(BUILD_DIR)/asm/Game/Enemy/Snakehead.o \
    $(BUILD_DIR)/asm/Game/Enemy/SpinHitController.o \
    $(BUILD_DIR)/asm/Game/Enemy/StinkBugBase.o \
    $(BUILD_DIR)/asm/Game/Enemy/StinkBugParent.o \
    $(BUILD_DIR)/asm/Game/Enemy/StinkBugSmall.o \
    $(BUILD_DIR)/asm/Game/Enemy/StringSpider.o \
    $(BUILD_DIR)/asm/Game/Enemy/Takobo.o \
    $(BUILD_DIR)/asm/Game/Enemy/TakoHei.o \
    $(BUILD_DIR)/asm/Game/Enemy/TakoHeiInk.o \
    $(BUILD_DIR)/asm/Game/Enemy/TakoHeiInkHolder.o \
    $(BUILD_DIR)/asm/Game/Enemy/Teresa.o \
    $(BUILD_DIR)/asm/Game/Enemy/TeresaWater.o \
    $(BUILD_DIR)/asm/Game/Enemy/TerritoryMover.o \
    $(BUILD_DIR)/asm/Game/Enemy/Unizo.o \
    $(BUILD_DIR)/asm/Game/Enemy/UnizoLauncher.o \
    $(BUILD_DIR)/asm/Game/Enemy/WalkerStateBindStarPointer.o \
    $(BUILD_DIR)/asm/Game/Enemy/WalkerStateBlowDamage.o \
    $(BUILD_DIR)/asm/Game/Enemy/WalkerStateChase.o \
    $(BUILD_DIR)/asm/Game/Enemy/WalkerStateFindPlayer.o \
    $(BUILD_DIR)/asm/Game/Enemy/WalkerStateFunction.o \
    $(BUILD_DIR)/asm/Game/Enemy/WalkerStateParam.o \
    $(BUILD_DIR)/asm/Game/Enemy/WalkerStateRunaway.o \
    $(BUILD_DIR)/asm/Game/Enemy/WalkerStateStagger.o \
    $(BUILD_DIR)/asm/Game/Enemy/WalkerStateWander.o \
    $(BUILD_DIR)/asm/Game/Enemy/WaterBazooka.o \
    $(BUILD_DIR)/asm/Game/Enemy/WaterBazookaCapsule.o \
    $(BUILD_DIR)/asm/Game/GameAudio/data.o \
    $(BUILD_DIR)/asm/Game/GameAudio/AudCameraWatcher.o \
    $(BUILD_DIR)/asm/Game/GameAudio/AudStageBgmWrap.o \
    $(BUILD_DIR)/asm/Game/GameAudio/AudSeKeeper.o \
    $(BUILD_DIR)/asm/Game/GameAudio/AudTalkSoundData.o \
    $(BUILD_DIR)/asm/Game/GameAudio/AudEffectDirector.o \
    $(BUILD_DIR)/asm/Game/GameAudio/AudBgmConductor.o \
    $(BUILD_DIR)/asm/Game/GameAudio/AudStageBgmTable.o \
    $(BUILD_DIR)/asm/Game/GameAudio/AudTamakoroBgmCtrl.o \
    $(BUILD_DIR)/asm/Game/Gravity/data.o \
    $(BUILD_DIR)/asm/Game/Gravity/ConeGravity/ConeGravity.o \
    $(BUILD_DIR)/asm/Game/Gravity/ConeGravity/setLocalMatrix.o \
    $(BUILD_DIR)/asm/Game/Gravity/ConeGravity/setEnableBottom.o \
    $(BUILD_DIR)/asm/Game/Gravity/ConeGravity/setTopCutRate.o \
    $(BUILD_DIR)/asm/Game/Gravity/JGeometry/isZero.o \
    $(BUILD_DIR)/asm/Game/Gravity/CubeGravity/CubeGravity.o \
    $(BUILD_DIR)/asm/Game/Gravity/ParallelGravity/setRangeBox.o \
    $(BUILD_DIR)/asm/Game/Gravity/CubeGravity/CubeGravity_methods.o \
    $(BUILD_DIR)/asm/Game/Gravity/JGeometry/normalize.o \
    $(BUILD_DIR)/asm/Game/Gravity/DiskGravity/DiskGravity.o \
    $(BUILD_DIR)/asm/Game/Gravity/DiskTorusGravity/setPosition.o \
    $(BUILD_DIR)/asm/Game/Gravity/DiskGravity/DiskGravity_methods.o \
    $(BUILD_DIR)/asm/Game/Gravity/DiskTorusGravity/DiskTorusGravity.o \
    $(BUILD_DIR)/asm/Game/Gravity/MapObjActorInitInfo/setupFarClipping.o \
    $(BUILD_DIR)/asm/Game/Gravity/DiskTorusGravity/DiskTorusGravity_methods.o \
    $(BUILD_DIR)/asm/Game/Gravity/GlobalGravityObj/GlobalGravityObj_all.o \
    $(BUILD_DIR)/asm/Game/Gravity/GravityFollower/GravityFollower_all.o \
    $(BUILD_DIR)/asm/Game/Gravity/GravityCreator/GravityCreator_all.o \
    $(BUILD_DIR)/asm/Game/Gravity/RailGraphNode/RailGraphNode.o \
    $(BUILD_DIR)/asm/Game/Gravity/GravityInfo/GravityInfo.o \
    $(BUILD_DIR)/asm/Game/Gravity/ParallelGravity/ParallelGravity_all.o \
    $(BUILD_DIR)/asm/Game/Gravity/PlanetGravity/PlanetGravity_all.o \
    $(BUILD_DIR)/asm/Game/Gravity/PlanetGravityManager/PlanetGravityManager_all.o \
    $(BUILD_DIR)/asm/Game/Gravity/PointGravity/PointGravity_all.o \
    $(BUILD_DIR)/asm/Game/Gravity/SegmentGravity/SegmentGravity_all.o \
    $(BUILD_DIR)/asm/Game/Gravity/WireGravity/WireGravity_all.o \
    $(BUILD_DIR)/asm/Game/LiveActor/data.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ActiveActorList.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ActorAnimKeeper.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ActorCameraInfo.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ActorJointCtrl.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ActorLightCtrl.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ActorPadAndCameraCtrl.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ActorStateBase.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ActorStateKeeper.o \
    $(BUILD_DIR)/asm/Game/LiveActor/AllLiveActorGroup.o \
    $(BUILD_DIR)/asm/Game/LiveActor/AnimationRandomPlayer.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Binder.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ClippingActorHolder.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ClippingActorInfo.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ClippingDirector.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ClippingGroupHolder.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ClippingJudge.o \
    $(BUILD_DIR)/asm/Game/LiveActor/DisplayListMaker.o \
    $(BUILD_DIR)/asm/Game/LiveActor/DynamicJointCtrl.o \
    $(BUILD_DIR)/asm/Game/LiveActor/EffectKeeper.o \
    $(BUILD_DIR)/asm/Game/LiveActor/FaceJointCtrl.o \
    $(BUILD_DIR)/asm/Game/LiveActor/FlashingCtrl.o \
    $(BUILD_DIR)/asm/Game/LiveActor/HitSensor.o \
    $(BUILD_DIR)/asm/Game/LiveActor/HitSensorInfo.o \
    $(BUILD_DIR)/asm/Game/LiveActor/HitSensorKeeper.o \
    $(BUILD_DIR)/asm/Game/LiveActor/IKJointCtrl.o \
    $(BUILD_DIR)/asm/Game/LiveActor/LiveActor.o \
    $(BUILD_DIR)/asm/Game/LiveActor/LiveActorFlag.o \
    $(BUILD_DIR)/asm/Game/LiveActor/LiveActorGroup.o \
    $(BUILD_DIR)/asm/Game/LiveActor/LiveActorGroupArray.o \
    $(BUILD_DIR)/asm/Game/LiveActor/LodCtrl.o \
    $(BUILD_DIR)/asm/Game/LiveActor/MaterialCtrl.o \
    $(BUILD_DIR)/asm/Game/LiveActor/MessageSensorHolder.o \
    $(BUILD_DIR)/asm/Game/LiveActor/MirrorActor.o \
    $(BUILD_DIR)/asm/Game/LiveActor/MirrorCamera.o \
    $(BUILD_DIR)/asm/Game/LiveActor/MirrorReflectionModel.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ModelManager.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ModelObj.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Nerve.o \
    $(BUILD_DIR)/asm/Game/LiveActor/PartsModel.o \
    $(BUILD_DIR)/asm/Game/LiveActor/RailRider.o \
    $(BUILD_DIR)/asm/Game/LiveActor/SensorHitChecker.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowController.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowDrawer.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowSurfaceBox.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowSurfaceCircle.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowSurfaceDrawer.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowSurfaceOval.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowVolumeBox.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowVolumeCylinder.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowVolumeDrawer.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowVolumeFlatModel.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowVolumeLine.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowVolumeModel.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowVolumeOval.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowVolumeOvalPole.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowVolumeSphere.o \
    $(BUILD_DIR)/asm/Game/LiveActor/SimpleJ3DModelDrawer.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Spine.o \
    $(BUILD_DIR)/asm/Game/LiveActor/SpotMarkLight.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ViewGroupCtrl.o \
    $(BUILD_DIR)/asm/Game/LiveActor/VolumeModelDrawer.o \
    $(BUILD_DIR)/asm/Game/Map/data.o \
    $(BUILD_DIR)/asm/Game/Map/ActorAppearSwitchListener.o \
    $(BUILD_DIR)/asm/Game/Map/Air.o \
    $(BUILD_DIR)/asm/Game/Map/BezierRail.o \
    $(BUILD_DIR)/asm/Game/Map/Butterfly.o \
    $(BUILD_DIR)/asm/Game/Map/CollisionCategorizedKeeper.o \
    $(BUILD_DIR)/asm/Game/Map/CollisionCode.o \
    $(BUILD_DIR)/asm/Game/Map/CollisionDirector.o \
    $(BUILD_DIR)/asm/Game/Map/CollisionDirector.o \
    $(BUILD_DIR)/asm/Game/Map/CollisionParts.o \
    $(BUILD_DIR)/asm/Game/Map/FileSelectCameraController.o \
    $(BUILD_DIR)/asm/Game/Map/FileSelectEffect.o \
    $(BUILD_DIR)/asm/Game/Map/FileSelectFunc.o \
    $(BUILD_DIR)/asm/Game/Map/FileSelectIconID.o \
    $(BUILD_DIR)/asm/Game/Map/FileSelectItem.o \
    $(BUILD_DIR)/asm/Game/Map/FileSelectModel.o \
    $(BUILD_DIR)/asm/Game/Map/FileSelector.o \
    $(BUILD_DIR)/asm/Game/Map/FileSelectSky.o \
    $(BUILD_DIR)/asm/Game/Map/FishGroup.o \
    $(BUILD_DIR)/asm/Game/Map/Flag.o \
    $(BUILD_DIR)/asm/Game/Map/GravityDust.o \
    $(BUILD_DIR)/asm/Game/Map/GroundChecker.o \
    $(BUILD_DIR)/asm/Game/Map/GroupSwitchWatcher.o \
    $(BUILD_DIR)/asm/Game/Map/Halo.o \
    $(BUILD_DIR)/asm/Game/Map/HitInfo.o \
    $(BUILD_DIR)/asm/Game/Map/KCollision.o \
    $(BUILD_DIR)/asm/Game/Map/KCollisionPlus.o \
    $(BUILD_DIR)/asm/Game/Map/KoopaBattleMapCoinPlate.o \
    $(BUILD_DIR)/asm/Game/Map/KoopaBattleMapDamagePlate.o \
    $(BUILD_DIR)/asm/Game/Map/KoopaBattleMapPlanet.o \
    $(BUILD_DIR)/asm/Game/Map/KoopaBattleMapPlate.o \
    $(BUILD_DIR)/asm/Game/Map/KoopaBattleMapStair.o \
    $(BUILD_DIR)/asm/Game/Map/LavaShellTower.o \
    $(BUILD_DIR)/asm/Game/Map/LavaSunPlanet.o \
    $(BUILD_DIR)/asm/Game/Map/LightDataHolder.o \
    $(BUILD_DIR)/asm/Game/Map/LightDirector.o \
    $(BUILD_DIR)/asm/Game/Map/LightFunction.o \
    $(BUILD_DIR)/asm/Game/Map/LightPointCtrl.o \
    $(BUILD_DIR)/asm/Game/Map/LightZoneDataHolder.o \
    $(BUILD_DIR)/asm/Game/Map/NamePosHolder.o \
    $(BUILD_DIR)/asm/Game/Map/OceanBowl.o \
    $(BUILD_DIR)/asm/Game/Map/OceanBowlBloomDrawer.o \
    $(BUILD_DIR)/asm/Game/Map/OceanBowlPoint.o \
    $(BUILD_DIR)/asm/Game/Map/OceanHomeMapCtrl.o \
    $(BUILD_DIR)/asm/Game/Map/OceanRing.o \
    $(BUILD_DIR)/asm/Game/Map/OceanRingBloomDrawer.o \
    $(BUILD_DIR)/asm/Game/Map/OceanRingDrawer.o \
    $(BUILD_DIR)/asm/Game/Map/OceanRingPipe.o \
    $(BUILD_DIR)/asm/Game/Map/OceanRingPipeInside.o \
    $(BUILD_DIR)/asm/Game/Map/OceanRingPipeOutside.o \
    $(BUILD_DIR)/asm/Game/Map/OceanSphere.o \
    $(BUILD_DIR)/asm/Game/Map/OceanSpherePoint.o \
    $(BUILD_DIR)/asm/Game/Map/PlanetMap.o \
    $(BUILD_DIR)/asm/Game/Map/PlanetMapCreator.o \
    $(BUILD_DIR)/asm/Game/Map/PlanetMapWithoutHighModel.o \
    $(BUILD_DIR)/asm/Game/Map/QuakeEffectGenerator.o \
    $(BUILD_DIR)/asm/Game/Map/RaceManager.o \
    $(BUILD_DIR)/asm/Game/Map/RaceRail.o \
    $(BUILD_DIR)/asm/Game/Map/RailGraph.o \
    $(BUILD_DIR)/asm/Game/Map/RailGraphEdge.o \
    $(BUILD_DIR)/asm/Game/Map/RailGraphIter.o \
    $(BUILD_DIR)/asm/Game/Map/RailGraphNode.o \
    $(BUILD_DIR)/asm/Game/Map/RailPart.o \
    $(BUILD_DIR)/asm/Game/Map/ScenarioSelectStar.o \
    $(BUILD_DIR)/asm/Game/Map/SeaGull.o \
    $(BUILD_DIR)/asm/Game/Map/Sky.o \
    $(BUILD_DIR)/asm/Game/Map/SleepController.o \
    $(BUILD_DIR)/asm/Game/Map/SleepControllerHolder.o \
    $(BUILD_DIR)/asm/Game/Map/SpaceInner.o \
    $(BUILD_DIR)/asm/Game/Map/SphereSelector.o \
    $(BUILD_DIR)/asm/Game/Map/SphereSelectorHandle.o \
    $(BUILD_DIR)/asm/Game/Map/StageSwitch.o \
    $(BUILD_DIR)/asm/Game/Map/SunshadeMapHolder.o \
    $(BUILD_DIR)/asm/Game/Map/SunshadeMapParts.o \
    $(BUILD_DIR)/asm/Game/Map/SwitchSynchronizer.o \
    $(BUILD_DIR)/asm/Game/Map/SwitchWatcher.o \
    $(BUILD_DIR)/asm/Game/Map/SwitchWatcherHolder.o \
    $(BUILD_DIR)/asm/Game/Map/TimerSwitch.o \
    $(BUILD_DIR)/asm/Game/Map/WaterAreaHolder.o \
    $(BUILD_DIR)/asm/Game/Map/WaterInfo.o \
    $(BUILD_DIR)/asm/Game/Map/WaterPlant.o \
    $(BUILD_DIR)/asm/Game/Map/WaterPoint.o \
    $(BUILD_DIR)/asm/Game/Map/WaterRoad.o \
    $(BUILD_DIR)/asm/Game/Map/WhirlPoolAccelerator.o \
    $(BUILD_DIR)/asm/Game/MapObj/data.o \
    $(BUILD_DIR)/asm/Game/MapObj/AirBubble.o \
    $(BUILD_DIR)/asm/Game/MapObj/AirBubbleGenerator.o \
    $(BUILD_DIR)/asm/Game/MapObj/AirBubbleHolder.o \
    $(BUILD_DIR)/asm/Game/MapObj/AnmModelObj.o \
    $(BUILD_DIR)/asm/Game/MapObj/ArrowSwitch.o \
    $(BUILD_DIR)/asm/Game/MapObj/ArrowSwitchMulti.o \
    $(BUILD_DIR)/asm/Game/MapObj/ArrowSwitchMultiHolder.o \
    $(BUILD_DIR)/asm/Game/MapObj/AssemblyBlock.o \
    $(BUILD_DIR)/asm/Game/MapObj/AstroCore.o \
    $(BUILD_DIR)/asm/Game/MapObj/AstroCountDownPlate.o \
    $(BUILD_DIR)/asm/Game/MapObj/AstroDome.o \
    $(BUILD_DIR)/asm/Game/MapObj/AstroDomeAsteroid.o \
    $(BUILD_DIR)/asm/Game/MapObj/AstroDomeBlueStar.o \
    $(BUILD_DIR)/asm/Game/MapObj/AstroDomeCameraController.o \
    $(BUILD_DIR)/asm/Game/MapObj/AstroDomeComet.o \
    $(BUILD_DIR)/asm/Game/MapObj/AstroDomeDemoAstroGalaxy.o \
    $(BUILD_DIR)/asm/Game/MapObj/AstroDomeGalaxySelector.o \
    $(BUILD_DIR)/asm/Game/MapObj/AstroDomeOrbit.o \
    $(BUILD_DIR)/asm/Game/MapObj/AstroDomeSky.o \
    $(BUILD_DIR)/asm/Game/MapObj/AstroMapBoard.o \
    $(BUILD_DIR)/asm/Game/MapObj/AstroMapObj.o \
    $(BUILD_DIR)/asm/Game/MapObj/AstroMapObjFunction.o \
    $(BUILD_DIR)/asm/Game/MapObj/AstroOverlookObj.o \
    $(BUILD_DIR)/asm/Game/MapObj/BallOpener.o \
    $(BUILD_DIR)/asm/Game/MapObj/BallRail.o \
    $(BUILD_DIR)/asm/Game/MapObj/Banekiti.o \
    $(BUILD_DIR)/asm/Game/MapObj/BattleShipElevator.o \
    $(BUILD_DIR)/asm/Game/MapObj/BeamGoRoundPlanet.o \
    $(BUILD_DIR)/asm/Game/MapObj/BeeFlowerHover.o \
    $(BUILD_DIR)/asm/Game/MapObj/BenefitItemInvincible.o \
    $(BUILD_DIR)/asm/Game/MapObj/BenefitItemLifeUp.o \
    $(BUILD_DIR)/asm/Game/MapObj/BenefitItemObj.o \
    $(BUILD_DIR)/asm/Game/MapObj/BigBubbleDrawer.o \
    $(BUILD_DIR)/asm/Game/MapObj/BigBubbleGenerator.o \
    $(BUILD_DIR)/asm/Game/MapObj/BigBubbleHolder.o \
    $(BUILD_DIR)/asm/Game/MapObj/BigBubbleMoveLimitter.o \
    $(BUILD_DIR)/asm/Game/MapObj/BigFan.o \
    $(BUILD_DIR)/asm/Game/MapObj/BigFanHolder.o \
    $(BUILD_DIR)/asm/Game/MapObj/BlackHole.o \
    $(BUILD_DIR)/asm/Game/MapObj/BlueChip.o \
    $(BUILD_DIR)/asm/Game/MapObj/BlueStarCupsulePlanet.o \
    $(BUILD_DIR)/asm/Game/MapObj/BreakableCage.o \
    $(BUILD_DIR)/asm/Game/MapObj/BrightObj.o \
    $(BUILD_DIR)/asm/Game/MapObj/BumpAppearPlanet.o \
    $(BUILD_DIR)/asm/Game/MapObj/Candlestand.o \
    $(BUILD_DIR)/asm/Game/MapObj/CannonFortressBreakStep.o \
    $(BUILD_DIR)/asm/Game/MapObj/CapsuleCage.o \
    $(BUILD_DIR)/asm/Game/MapObj/ChipBase.o \
    $(BUILD_DIR)/asm/Game/MapObj/ChipCounter.o \
    $(BUILD_DIR)/asm/Game/MapObj/ChipGroup.o \
    $(BUILD_DIR)/asm/Game/MapObj/ChipHolder.o \
    $(BUILD_DIR)/asm/Game/MapObj/ChooChooTrain.o \
    $(BUILD_DIR)/asm/Game/MapObj/CircleCoinGroup.o \
    $(BUILD_DIR)/asm/Game/MapObj/ClipArea.o \
    $(BUILD_DIR)/asm/Game/MapObj/ClipAreaDrop.o \
    $(BUILD_DIR)/asm/Game/MapObj/ClipAreaDropHolder.o \
    $(BUILD_DIR)/asm/Game/MapObj/ClipAreaDropLaser.o \
    $(BUILD_DIR)/asm/Game/MapObj/ClipAreaHolder.o \
    $(BUILD_DIR)/asm/Game/MapObj/ClipAreaMovable.o \
    $(BUILD_DIR)/asm/Game/MapObj/ClipAreaShape.o \
    $(BUILD_DIR)/asm/Game/MapObj/ClipFieldFillDraw.o \
    $(BUILD_DIR)/asm/Game/MapObj/ClipFieldMapParts.o \
    $(BUILD_DIR)/asm/Game/MapObj/ClipFieldSwitch.o \
    $(BUILD_DIR)/asm/Game/MapObj/CocoNut.o \
    $(BUILD_DIR)/asm/Game/MapObj/CoconutTree.o \
    $(BUILD_DIR)/asm/Game/MapObj/CoconutTreeLeaf.o \
    $(BUILD_DIR)/asm/Game/MapObj/Coin.o \
    $(BUILD_DIR)/asm/Game/MapObj/CoinBox.o \
    $(BUILD_DIR)/asm/Game/MapObj/CoinGroup.o \
    $(BUILD_DIR)/asm/Game/MapObj/CoinHolder.o \
    $(BUILD_DIR)/asm/Game/MapObj/CoinReplica.o \
    $(BUILD_DIR)/asm/Game/MapObj/CoinRotater.o \
    $(BUILD_DIR)/asm/Game/MapObj/CoinSpot.o \
    $(BUILD_DIR)/asm/Game/MapObj/CollapsePlane.o \
    $(BUILD_DIR)/asm/Game/MapObj/CollectCounter.o \
    $(BUILD_DIR)/asm/Game/MapObj/CollisionBlocker.o \
    $(BUILD_DIR)/asm/Game/MapObj/CrystalCage.o \
    $(BUILD_DIR)/asm/Game/MapObj/CrystalCageMoving.o \
    $(BUILD_DIR)/asm/Game/MapObj/CrystalSwitch.o \
    $(BUILD_DIR)/asm/Game/MapObj/CutBushModelObj.o \
    $(BUILD_DIR)/asm/Game/MapObj/DashRing.o \
    $(BUILD_DIR)/asm/Game/MapObj/DeadLeaves.o \
    $(BUILD_DIR)/asm/Game/MapObj/DesertLandMoveSwitch.o \
    $(BUILD_DIR)/asm/Game/MapObj/DesertMovingLand.o \
    $(BUILD_DIR)/asm/Game/MapObj/DragonHeadFlower.o \
    $(BUILD_DIR)/asm/Game/MapObj/DriftWood.o \
    $(BUILD_DIR)/asm/Game/MapObj/DummyDisplayModel.o \
    $(BUILD_DIR)/asm/Game/MapObj/DynamicCollisionObj.o \
    $(BUILD_DIR)/asm/Game/MapObj/EarthenPipe.o \
    $(BUILD_DIR)/asm/Game/MapObj/ElectricBall.o \
    $(BUILD_DIR)/asm/Game/MapObj/ElectricRail.o \
    $(BUILD_DIR)/asm/Game/MapObj/ElectricRailHolder.o \
    $(BUILD_DIR)/asm/Game/MapObj/ElectricRailMoving.o \
    $(BUILD_DIR)/asm/Game/MapObj/ExterminationChecker.o \
    $(BUILD_DIR)/asm/Game/MapObj/FallDownBridge.o \
    $(BUILD_DIR)/asm/Game/MapObj/FallingSmallRock.o \
    $(BUILD_DIR)/asm/Game/MapObj/FallOutFieldDraw.o \
    $(BUILD_DIR)/asm/Game/MapObj/FireBar.o \
    $(BUILD_DIR)/asm/Game/MapObj/FirePressure.o \
    $(BUILD_DIR)/asm/Game/MapObj/FirePressureBullet.o \
    $(BUILD_DIR)/asm/Game/MapObj/FirePressureBulletHolder.o \
    $(BUILD_DIR)/asm/Game/MapObj/FirePressureRadiate.o \
    $(BUILD_DIR)/asm/Game/MapObj/FlameGun.o \
    $(BUILD_DIR)/asm/Game/MapObj/FlexibleSphere.o \
    $(BUILD_DIR)/asm/Game/MapObj/FlipPanel.o \
    $(BUILD_DIR)/asm/Game/MapObj/Fountain.o \
    $(BUILD_DIR)/asm/Game/MapObj/FountainBig.o \
    $(BUILD_DIR)/asm/Game/MapObj/GCapture.o \
    $(BUILD_DIR)/asm/Game/MapObj/GCaptureRibbon.o \
    $(BUILD_DIR)/asm/Game/MapObj/GCaptureTarget.o \
    $(BUILD_DIR)/asm/Game/MapObj/GravityLight.o \
    $(BUILD_DIR)/asm/Game/MapObj/GravityLightRoad.o \
    $(BUILD_DIR)/asm/Game/MapObj/GreenCaterpillarBig.o \
    $(BUILD_DIR)/asm/Game/MapObj/HatchWaterPlanet.o \
    $(BUILD_DIR)/asm/Game/MapObj/HeavensDoorDemoObj.o \
    $(BUILD_DIR)/asm/Game/MapObj/HipDropMoveObj.o \
    $(BUILD_DIR)/asm/Game/MapObj/HipDropRock.o \
    $(BUILD_DIR)/asm/Game/MapObj/HipDropSwitch.o \
    $(BUILD_DIR)/asm/Game/MapObj/HipDropTimerSwitch.o \
    $(BUILD_DIR)/asm/Game/MapObj/HitWallTimerSwitch.o \
    $(BUILD_DIR)/asm/Game/MapObj/IceStep.o \
    $(BUILD_DIR)/asm/Game/MapObj/IceVolcanoUpDownPlane.o \
    $(BUILD_DIR)/asm/Game/MapObj/InvisiblePolygonObj.o \
    $(BUILD_DIR)/asm/Game/MapObj/InvisiblePolygonObjGCapture.o \
    $(BUILD_DIR)/asm/Game/MapObj/IronCannonShell.o \
    $(BUILD_DIR)/asm/Game/MapObj/ItemAppearStone.o \
    $(BUILD_DIR)/asm/Game/MapObj/ItemBlock.o \
    $(BUILD_DIR)/asm/Game/MapObj/ItemBubble.o \
    $(BUILD_DIR)/asm/Game/MapObj/JetTurtle.o \
    $(BUILD_DIR)/asm/Game/MapObj/JumpHole.o \
    $(BUILD_DIR)/asm/Game/MapObj/JumpStand.o \
    $(BUILD_DIR)/asm/Game/MapObj/KeySwitch.o \
    $(BUILD_DIR)/asm/Game/MapObj/KillerGunnerSingle.o \
    $(BUILD_DIR)/asm/Game/MapObj/LargeChain.o \
    $(BUILD_DIR)/asm/Game/MapObj/LargeChainParts.o \
    $(BUILD_DIR)/asm/Game/MapObj/LavaBallRisingPlanetLava.o \
    $(BUILD_DIR)/asm/Game/MapObj/LavaBreakColumn.o \
    $(BUILD_DIR)/asm/Game/MapObj/LavaFloater.o \
    $(BUILD_DIR)/asm/Game/MapObj/LavaGalaxyParts.o \
    $(BUILD_DIR)/asm/Game/MapObj/LavaGeyser.o \
    $(BUILD_DIR)/asm/Game/MapObj/LavaHomeSeesaw.o \
    $(BUILD_DIR)/asm/Game/MapObj/LavaHomeVolcanoFlow.o \
    $(BUILD_DIR)/asm/Game/MapObj/LavaJamboSunPlanet.o \
    $(BUILD_DIR)/asm/Game/MapObj/LavaProminence.o \
    $(BUILD_DIR)/asm/Game/MapObj/LavaProminenceTriple.o \
    $(BUILD_DIR)/asm/Game/MapObj/LavaSteam.o \
    $(BUILD_DIR)/asm/Game/MapObj/LavaStrangeRock.o \
    $(BUILD_DIR)/asm/Game/MapObj/LotusLeaf.o \
    $(BUILD_DIR)/asm/Game/MapObj/MagicBell.o \
    $(BUILD_DIR)/asm/Game/MapObj/ManholeCover.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapObjActor.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapObjActorInitInfo.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapObjConnector.o \
    $(BUILD_DIR)/asm/Game/MapObj/MarblePlanet.o \
    $(BUILD_DIR)/asm/Game/MapObj/MarioLauncher.o \
    $(BUILD_DIR)/asm/Game/MapObj/MarioLauncherAttractor.o \
    $(BUILD_DIR)/asm/Game/MapObj/MechaKoopaPartsArm.o \
    $(BUILD_DIR)/asm/Game/MapObj/MechaKoopaPartsHead.o \
    $(BUILD_DIR)/asm/Game/MapObj/MercatorFixParts.o \
    $(BUILD_DIR)/asm/Game/MapObj/MercatorRailMoveParts.o \
    $(BUILD_DIR)/asm/Game/MapObj/MercatorRotateParts.o \
    $(BUILD_DIR)/asm/Game/MapObj/MeteoContainer.o \
    $(BUILD_DIR)/asm/Game/MapObj/MeteorStrike.o \
    $(BUILD_DIR)/asm/Game/MapObj/MeteorStrikeLauncher.o \
    $(BUILD_DIR)/asm/Game/MapObj/MiniatureGalaxy.o \
    $(BUILD_DIR)/asm/Game/MapObj/MiniatureGalaxyHolder.o \
    $(BUILD_DIR)/asm/Game/MapObj/MorphItemObjNeo.o \
    $(BUILD_DIR)/asm/Game/MapObj/NeedlePlant.o \
    $(BUILD_DIR)/asm/Game/MapObj/NormalMapBase.o \
    $(BUILD_DIR)/asm/Game/MapObj/NormalMapTestObj.o \
    $(BUILD_DIR)/asm/Game/MapObj/Note.o \
    $(BUILD_DIR)/asm/Game/MapObj/NoteFairy.o \
    $(BUILD_DIR)/asm/Game/MapObj/OceanFloaterLandParts.o \
    $(BUILD_DIR)/asm/Game/MapObj/OceanSmallTurtle.o \
    $(BUILD_DIR)/asm/Game/MapObj/OceanWaveFloater.o \
    $(BUILD_DIR)/asm/Game/MapObj/PalmIsland.o \
    $(BUILD_DIR)/asm/Game/MapObj/PeachCastleGardenPlanet.o \
    $(BUILD_DIR)/asm/Game/MapObj/PhantomShipBoxFloater.o \
    $(BUILD_DIR)/asm/Game/MapObj/PhantomShipBridge.o \
    $(BUILD_DIR)/asm/Game/MapObj/PhantomShipHandle.o \
    $(BUILD_DIR)/asm/Game/MapObj/PhantomTorch.o \
    $(BUILD_DIR)/asm/Game/MapObj/PicketSwitch.o \
    $(BUILD_DIR)/asm/Game/MapObj/PlantGroup.o \
    $(BUILD_DIR)/asm/Game/MapObj/PlantPoint.o \
    $(BUILD_DIR)/asm/Game/MapObj/PlantRailInfo.o \
    $(BUILD_DIR)/asm/Game/MapObj/PomponPlant.o \
    $(BUILD_DIR)/asm/Game/MapObj/PowerStar.o \
    $(BUILD_DIR)/asm/Game/MapObj/PowerStarAppearPoint.o \
    $(BUILD_DIR)/asm/Game/MapObj/PowerStarHolder.o \
    $(BUILD_DIR)/asm/Game/MapObj/PressureBase.o \
    $(BUILD_DIR)/asm/Game/MapObj/PrizeRing.o \
    $(BUILD_DIR)/asm/Game/MapObj/PTimerSwitch.o \
    $(BUILD_DIR)/asm/Game/MapObj/PunchBox.o \
    $(BUILD_DIR)/asm/Game/MapObj/PunchingKinoko.o \
    $(BUILD_DIR)/asm/Game/MapObj/PurpleCoinHolder.o \
    $(BUILD_DIR)/asm/Game/MapObj/PurpleCoinStarter.o \
    $(BUILD_DIR)/asm/Game/MapObj/QuarterRollGravityRoomArrow.o \
    $(BUILD_DIR)/asm/Game/MapObj/QuestionBoxGalleryObj.o \
    $(BUILD_DIR)/asm/Game/MapObj/QuestionCoin.o \
    $(BUILD_DIR)/asm/Game/MapObj/RailBlock.o \
    $(BUILD_DIR)/asm/Game/MapObj/RailCoin.o \
    $(BUILD_DIR)/asm/Game/MapObj/RailMoveObj.o \
    $(BUILD_DIR)/asm/Game/MapObj/RainCloud.o \
    $(BUILD_DIR)/asm/Game/MapObj/ReverseGravityRoomPlanet.o \
    $(BUILD_DIR)/asm/Game/MapObj/RevolvingWay.o \
    $(BUILD_DIR)/asm/Game/MapObj/Rock.o \
    $(BUILD_DIR)/asm/Game/MapObj/RockCreator.o \
    $(BUILD_DIR)/asm/Game/MapObj/RosettaChair.o \
    $(BUILD_DIR)/asm/Game/MapObj/RosettaPictureBook.o \
    $(BUILD_DIR)/asm/Game/MapObj/RotateMoveObj.o \
    $(BUILD_DIR)/asm/Game/MapObj/SandCapsuleInsidePlanet.o \
    $(BUILD_DIR)/asm/Game/MapObj/SandCapsulePressGround.o \
    $(BUILD_DIR)/asm/Game/MapObj/Sandstorm.o \
    $(BUILD_DIR)/asm/Game/MapObj/SandUpDownEffectObj.o \
    $(BUILD_DIR)/asm/Game/MapObj/SandUpDownTriRock.o \
    $(BUILD_DIR)/asm/Game/MapObj/ScrewSwitch.o \
    $(BUILD_DIR)/asm/Game/MapObj/ScrewSwitchReverse.o \
    $(BUILD_DIR)/asm/Game/MapObj/SeaBottomTriplePropeller.o \
    $(BUILD_DIR)/asm/Game/MapObj/SeesawMoveNut.o \
    $(BUILD_DIR)/asm/Game/MapObj/Shellfish.o \
    $(BUILD_DIR)/asm/Game/MapObj/ShockWaveGenerator.o \
    $(BUILD_DIR)/asm/Game/MapObj/ShootingStar.o \
    $(BUILD_DIR)/asm/Game/MapObj/SideSpikeMoveStep.o \
    $(BUILD_DIR)/asm/Game/MapObj/SimpleBreakableObj.o \
    $(BUILD_DIR)/asm/Game/MapObj/SimpleClipPartsObj.o \
    $(BUILD_DIR)/asm/Game/MapObj/SimpleFloaterObj.o \
    $(BUILD_DIR)/asm/Game/MapObj/SimpleMapObj.o \
    $(BUILD_DIR)/asm/Game/MapObj/SimpleNormalMapObj.o \
    $(BUILD_DIR)/asm/Game/MapObj/SimpleTimerObj.o \
    $(BUILD_DIR)/asm/Game/MapObj/SmallStone.o \
    $(BUILD_DIR)/asm/Game/MapObj/SnowCapsulePlanet.o \
    $(BUILD_DIR)/asm/Game/MapObj/SnowFloor.o \
    $(BUILD_DIR)/asm/Game/MapObj/SnowFloorTile.o \
    $(BUILD_DIR)/asm/Game/MapObj/SnowMan.o \
    $(BUILD_DIR)/asm/Game/MapObj/SnowplowSwitch.o \
    $(BUILD_DIR)/asm/Game/MapObj/SoundEmitter.o \
    $(BUILD_DIR)/asm/Game/MapObj/SpaceMine.o \
    $(BUILD_DIR)/asm/Game/MapObj/SpaceShipStep.o \
    $(BUILD_DIR)/asm/Game/MapObj/SphereRailDash.o \
    $(BUILD_DIR)/asm/Game/MapObj/SpiderCoin.o \
    $(BUILD_DIR)/asm/Game/MapObj/SpiderMapBlock.o \
    $(BUILD_DIR)/asm/Game/MapObj/SpiderThread.o \
    $(BUILD_DIR)/asm/Game/MapObj/SpiderThreadHangInfo.o \
    $(BUILD_DIR)/asm/Game/MapObj/SpiderThreadMainPoint.o \
    $(BUILD_DIR)/asm/Game/MapObj/SpiderThreadPart.o \
    $(BUILD_DIR)/asm/Game/MapObj/SpiderThreadPoint.o \
    $(BUILD_DIR)/asm/Game/MapObj/SpiderThreadRadialLine.o \
    $(BUILD_DIR)/asm/Game/MapObj/SpiderThreadWindCtrl.o \
    $(BUILD_DIR)/asm/Game/MapObj/SpinDriver.o \
    $(BUILD_DIR)/asm/Game/MapObj/SpinDriverCamera.o \
    $(BUILD_DIR)/asm/Game/MapObj/SpinDriverOperateRing.o \
    $(BUILD_DIR)/asm/Game/MapObj/SpinDriverPathDrawer.o \
    $(BUILD_DIR)/asm/Game/MapObj/SpinDriverShootPath.o \
    $(BUILD_DIR)/asm/Game/MapObj/SpinDriverUtil.o \
    $(BUILD_DIR)/asm/Game/MapObj/SpinLeverSwitch.o \
    $(BUILD_DIR)/asm/Game/MapObj/SpinningBox.o \
    $(BUILD_DIR)/asm/Game/MapObj/SpringJetWater.o \
    $(BUILD_DIR)/asm/Game/MapObj/SpringWaterFloaterSpot.o \
    $(BUILD_DIR)/asm/Game/MapObj/StageEffectDataTable.o \
    $(BUILD_DIR)/asm/Game/MapObj/StarPiece.o \
    $(BUILD_DIR)/asm/Game/MapObj/StarPieceDirector.o \
    $(BUILD_DIR)/asm/Game/MapObj/StarPieceFollowGroup.o \
    $(BUILD_DIR)/asm/Game/MapObj/StarPieceGroup.o \
    $(BUILD_DIR)/asm/Game/MapObj/StarPieceMother.o \
    $(BUILD_DIR)/asm/Game/MapObj/StarPieceSpot.o \
    $(BUILD_DIR)/asm/Game/MapObj/SubmarineSteam.o \
    $(BUILD_DIR)/asm/Game/MapObj/SubmarineVolcanoBigColumn.o \
    $(BUILD_DIR)/asm/Game/MapObj/Sun.o \
    $(BUILD_DIR)/asm/Game/MapObj/SuperSpinDriver.o \
    $(BUILD_DIR)/asm/Game/MapObj/SurprisedGalaxy.o \
    $(BUILD_DIR)/asm/Game/MapObj/Swinger.o \
    $(BUILD_DIR)/asm/Game/MapObj/SwingLight.o \
    $(BUILD_DIR)/asm/Game/MapObj/SwitchBox.o \
    $(BUILD_DIR)/asm/Game/MapObj/TimeAppearObj.o \
    $(BUILD_DIR)/asm/Game/MapObj/TimerMoveWall.o \
    $(BUILD_DIR)/asm/Game/MapObj/TrampleStar.o \
    $(BUILD_DIR)/asm/Game/MapObj/TransparentWall.o \
    $(BUILD_DIR)/asm/Game/MapObj/TreasureBoxCracked.o \
    $(BUILD_DIR)/asm/Game/MapObj/TreasureSpot.o \
    $(BUILD_DIR)/asm/Game/MapObj/Tsukidashikun.o \
    $(BUILD_DIR)/asm/Game/MapObj/TypicalDoor.o \
    $(BUILD_DIR)/asm/Game/MapObj/UFOBase.o \
    $(BUILD_DIR)/asm/Game/MapObj/UFOKinoko.o \
    $(BUILD_DIR)/asm/Game/MapObj/ValveSwitch.o \
    $(BUILD_DIR)/asm/Game/MapObj/WarpPod.o \
    $(BUILD_DIR)/asm/Game/MapObj/WatchTowerRotateStep.o \
    $(BUILD_DIR)/asm/Game/MapObj/WaterfallCaveCover.o \
    $(BUILD_DIR)/asm/Game/MapObj/WaterLeakPipe.o \
    $(BUILD_DIR)/asm/Game/MapObj/WaterPressure.o \
    $(BUILD_DIR)/asm/Game/MapObj/WaterPressureBullet.o \
    $(BUILD_DIR)/asm/Game/MapObj/WaterPressureBulletHolder.o \
    $(BUILD_DIR)/asm/Game/MapObj/WaveFloatingForce.o \
    $(BUILD_DIR)/asm/Game/MapObj/WhirlPool.o \
    $(BUILD_DIR)/asm/Game/MapObj/WoodBox.o \
    $(BUILD_DIR)/asm/Game/MapObj/WormEatenPlanet.o \
    $(BUILD_DIR)/asm/Game/MapObj/YellowChip.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapParts/MapParts.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapParts/GeneralMapParts.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapParts/Floater/FloaterFloatingForce.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapParts/Floater/FloaterFloatingForceTypeNormal.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapParts/Floater/FloaterFloatingForceTypeSpring.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapParts/Floater/FloaterFunction.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapParts/LavaHomeSeesawRotator.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapParts/MapPartsAppearController.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapParts/MapPartsBreaker.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapParts/MapPartsFloatingForce.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapParts/MapPartsFunction.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapParts/MapPartsRailGuideDrawer.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapParts/MapPartsRailGuideHolder.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapParts/MapPartsRailGuidePoint.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapParts/MapPartsRailMover.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapParts/MapPartsRailPointPassChecker.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapParts/MapPartsRailPosture.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapParts/MapPartsRailRotator.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapParts/MapPartsRotator.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapParts/MapPartsSeesaw1AxisRotator.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapParts/MapPartsSeesaw2AxisRotator.o \
    $(BUILD_DIR)/asm/Game/NameObj/data.o \
    $(BUILD_DIR)/asm/Game/NameObj/ModelChangableObjFactory.o \
    $(BUILD_DIR)/asm/Game/NameObj/MovementOnOffGroupHolder.o \
    $(BUILD_DIR)/asm/Game/NameObj/NameObj.o \
    $(BUILD_DIR)/asm/Game/NameObj/NameObjAdaptor.o \
    $(BUILD_DIR)/asm/Game/NameObj/NameObjArchiveListCollector.o \
    $(BUILD_DIR)/asm/Game/NameObj/NameObjCategoryList.o \
    $(BUILD_DIR)/asm/Game/NameObj/NameObjExecuteHolder.o \
    $(BUILD_DIR)/asm/Game/NameObj/NameObjFactory.o \
    $(BUILD_DIR)/asm/Game/NameObj/NameObjFinder.o \
    $(BUILD_DIR)/asm/Game/NameObj/NameObjGroup.o \
    $(BUILD_DIR)/asm/Game/NameObj/NameObjHolder.o \
    $(BUILD_DIR)/asm/Game/NameObj/NameObjListExecutor.o \
    $(BUILD_DIR)/asm/Game/NameObj/NameObjRegister.o \
    $(BUILD_DIR)/asm/Game/NPC/data.o \
    $(BUILD_DIR)/asm/Game/NPC/Butler.o \
    $(BUILD_DIR)/asm/Game/NPC/ButlerExplain.o \
    $(BUILD_DIR)/asm/Game/NPC/ButlerMap.o \
    $(BUILD_DIR)/asm/Game/NPC/ButlerStateStarPieceReaction.o \
    $(BUILD_DIR)/asm/Game/NPC/CareTaker.o \
    $(BUILD_DIR)/asm/Game/NPC/CollectTico.o \
    $(BUILD_DIR)/asm/Game/NPC/DemoRabbit.o \
    $(BUILD_DIR)/asm/Game/NPC/HoneyBee.o \
    $(BUILD_DIR)/asm/Game/NPC/HoneyQueen.o \
    $(BUILD_DIR)/asm/Game/NPC/Kinopio.o \
    $(BUILD_DIR)/asm/Game/NPC/KinopioAstro.o \
    $(BUILD_DIR)/asm/Game/NPC/KoopaJr.o \
    $(BUILD_DIR)/asm/Game/NPC/LuigiNPC.o \
    $(BUILD_DIR)/asm/Game/NPC/MiiDatabase.o \
    $(BUILD_DIR)/asm/Game/NPC/MiiFaceIcon.o \
    $(BUILD_DIR)/asm/Game/NPC/MiiFaceIconHolder.o \
    $(BUILD_DIR)/asm/Game/NPC/MiiFaceParts.o \
    $(BUILD_DIR)/asm/Game/NPC/MiiFacePartsHolder.o \
    $(BUILD_DIR)/asm/Game/NPC/MiiFaceRecipe.o \
    $(BUILD_DIR)/asm/Game/NPC/Peach.o \
    $(BUILD_DIR)/asm/Game/NPC/Penguin.o \
    $(BUILD_DIR)/asm/Game/NPC/PenguinCoach.o \
    $(BUILD_DIR)/asm/Game/NPC/PenguinMaster.o \
    $(BUILD_DIR)/asm/Game/NPC/PenguinRacer.o \
    $(BUILD_DIR)/asm/Game/NPC/PenguinRacerLeader.o \
    $(BUILD_DIR)/asm/Game/NPC/PenguinSkater.o \
    $(BUILD_DIR)/asm/Game/NPC/PenguinStudent.o \
    $(BUILD_DIR)/asm/Game/NPC/PowerStarEventKeeper.o \
    $(BUILD_DIR)/asm/Game/NPC/Rabbit.o \
    $(BUILD_DIR)/asm/Game/NPC/RabbitStateCaught.o \
    $(BUILD_DIR)/asm/Game/NPC/RabbitStateWaitStart.o \
    $(BUILD_DIR)/asm/Game/NPC/Rosetta.o \
    $(BUILD_DIR)/asm/Game/NPC/RosettaDemoAstroDome.o \
    $(BUILD_DIR)/asm/Game/NPC/RosettaDemoEpilogue.o \
    $(BUILD_DIR)/asm/Game/NPC/RosettaDemoHeavensDoor.o \
    $(BUILD_DIR)/asm/Game/NPC/RosettaReading.o \
    $(BUILD_DIR)/asm/Game/NPC/RunawayRabbit.o \
    $(BUILD_DIR)/asm/Game/NPC/RunawayRabbitCollect.o \
    $(BUILD_DIR)/asm/Game/NPC/RunawayTico.o \
    $(BUILD_DIR)/asm/Game/NPC/SignBoard.o \
    $(BUILD_DIR)/asm/Game/NPC/StrayTico.o \
    $(BUILD_DIR)/asm/Game/NPC/Syati.o \
    $(BUILD_DIR)/asm/Game/NPC/TeresaRacer.o \
    $(BUILD_DIR)/asm/Game/NPC/Tico.o \
    $(BUILD_DIR)/asm/Game/NPC/TicoAstro.o \
    $(BUILD_DIR)/asm/Game/NPC/TicoComet.o \
    $(BUILD_DIR)/asm/Game/NPC/TicoDemoGetPower.o \
    $(BUILD_DIR)/asm/Game/NPC/TicoDomeLecture.o \
    $(BUILD_DIR)/asm/Game/NPC/TicoFat.o \
    $(BUILD_DIR)/asm/Game/NPC/TicoGalaxy.o \
    $(BUILD_DIR)/asm/Game/NPC/TicoRail.o \
    $(BUILD_DIR)/asm/Game/NPC/TicoReading.o \
    $(BUILD_DIR)/asm/Game/NPC/TicoShop.o \
    $(BUILD_DIR)/asm/Game/NPC/TicoStarRing.o \
    $(BUILD_DIR)/asm/Game/NPC/TrickRabbit.o \
    $(BUILD_DIR)/asm/Game/NPC/TrickRabbitFreeRun.o \
    $(BUILD_DIR)/asm/Game/NPC/TrickRabbitSnowCollect.o \
    $(BUILD_DIR)/asm/Game/NPC/TrickRabbitSnow.o \
    $(BUILD_DIR)/asm/Game/NPC/TrickRabbitUtil.o \
    $(BUILD_DIR)/asm/Game/NPC/CometEventExecutorTimeLimit.o \
    $(BUILD_DIR)/asm/Game/NPC/CometEventKeeper.o \
    $(BUILD_DIR)/asm/Game/NPC/EventDirector.o \
    $(BUILD_DIR)/asm/Game/NPC/NPCActor.o \
    $(BUILD_DIR)/asm/Game/NPC/NPCParameter.o \
    $(BUILD_DIR)/asm/Game/NPC/NPCDirector.o \
    $(BUILD_DIR)/asm/Game/NPC/NPCFunction.o \
    $(BUILD_DIR)/asm/Game/NPC/NPCSupportRail.o \
    $(BUILD_DIR)/asm/Game/NPC/StageStateKeeper.o \
    $(BUILD_DIR)/asm/Game/NPC/TalkBalloon.o \
    $(BUILD_DIR)/asm/Game/NPC/TalkDirector.o \
    $(BUILD_DIR)/asm/Game/NPC/TalkMessageCtrl.o \
    $(BUILD_DIR)/asm/Game/NPC/TalkMessageInfo.o \
    $(BUILD_DIR)/asm/Game/NPC/TalkNodeCtrl.o \
    $(BUILD_DIR)/asm/Game/NPC/TurnJointCtrl.o \
    $(BUILD_DIR)/asm/Game/NPC/TalkState.o \
    $(BUILD_DIR)/asm/Game/NPC/TalkSupportPlayerWatcher.o \
    $(BUILD_DIR)/asm/Game/NPC/TalkTextFormer.o \
    $(BUILD_DIR)/asm/Game/NPC/TimeAttackEventKeeper.o \
    $(BUILD_DIR)/asm/Game/Player/data.o \
    $(BUILD_DIR)/asm/Game/Player/FireMarioBall.o \
    $(BUILD_DIR)/asm/Game/Player/GhostPacket.o \
    $(BUILD_DIR)/asm/Game/Player/GhostPlayer.o \
    $(BUILD_DIR)/asm/Game/Player/GroupChecker.o \
    $(BUILD_DIR)/asm/Game/Player/J3DModelX.o \
    $(BUILD_DIR)/asm/Game/Player/JetTurtleShadow.o \
    $(BUILD_DIR)/asm/Game/Player/MarineSnow.o \
    $(BUILD_DIR)/asm/Game/Player/Mario.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActor.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorDraw.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorPunch.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorCamera.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorClap.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorGameOver.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorGravity.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorHand.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorInit.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorPad.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorParts.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorRush.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorSensor.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorShadow.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorSpecialDraw.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorMatrix.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorMorph.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorEye.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorOffensiveMsg.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorDefensiveMsg.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorRushMsg.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorTakeMsg.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorBlackHole.o \
    $(BUILD_DIR)/asm/Game/Player/MarioAnimator.o \
    $(BUILD_DIR)/asm/Game/Player/MarioAnimationEfx.o \
    $(BUILD_DIR)/asm/Game/Player/MarioWait.o \
    $(BUILD_DIR)/asm/Game/Player/MarioClimb.o \
    $(BUILD_DIR)/asm/Game/Player/MarioCollision.o \
    $(BUILD_DIR)/asm/Game/Player/MarioConst.o \
    $(BUILD_DIR)/asm/Game/Player/MarioDamage.o \
    $(BUILD_DIR)/asm/Game/Player/MarioDamageParalyze.o \
    $(BUILD_DIR)/asm/Game/Player/MarioDamageFreeze.o \
    $(BUILD_DIR)/asm/Game/Player/MarioDamageStun.o \
    $(BUILD_DIR)/asm/Game/Player/MarioDamageCrush.o \
    $(BUILD_DIR)/asm/Game/Player/MarioFaint.o \
    $(BUILD_DIR)/asm/Game/Player/MarioFlip.o \
    $(BUILD_DIR)/asm/Game/Player/MarioFrontStep.o \
    $(BUILD_DIR)/asm/Game/Player/MarioBee.o \
    $(BUILD_DIR)/asm/Game/Player/MarioBlown.o \
    $(BUILD_DIR)/asm/Game/Player/MarioEffect.o \
    $(BUILD_DIR)/asm/Game/Player/MarioFlow.o \
    $(BUILD_DIR)/asm/Game/Player/MarioFoo.o \
    $(BUILD_DIR)/asm/Game/Player/MarioHolder.o \
    $(BUILD_DIR)/asm/Game/Player/MarioInit.o \
    $(BUILD_DIR)/asm/Game/Player/MarioJump.o \
    $(BUILD_DIR)/asm/Game/Player/MarioMessenger.o \
    $(BUILD_DIR)/asm/Game/Player/MarioModule.o \
    $(BUILD_DIR)/asm/Game/Player/MarioMove.o \
    $(BUILD_DIR)/asm/Game/Player/MarioMove2D.o \
    $(BUILD_DIR)/asm/Game/Player/MarioMove25D.o \
    $(BUILD_DIR)/asm/Game/Player/MarioMoveSphere.o \
    $(BUILD_DIR)/asm/Game/Player/MarioParts.o \
    $(BUILD_DIR)/asm/Game/Player/MarioPress.o \
    $(BUILD_DIR)/asm/Game/Player/MarioRabbit.o \
    $(BUILD_DIR)/asm/Game/Player/MarioSearchLight.o \
    $(BUILD_DIR)/asm/Game/Player/MarioSideStep.o \
    $(BUILD_DIR)/asm/Game/Player/MarioSkate.o \
    $(BUILD_DIR)/asm/Game/Player/MarioSound.o \
    $(BUILD_DIR)/asm/Game/Player/MarioSpecial.o \
    $(BUILD_DIR)/asm/Game/Player/MarioSpin.o \
    $(BUILD_DIR)/asm/Game/Player/MarioState.o \
    $(BUILD_DIR)/asm/Game/Player/MarioStick.o \
    $(BUILD_DIR)/asm/Game/Player/MarioSukekiyo.o \
    $(BUILD_DIR)/asm/Game/Player/MarioTalk.o \
    $(BUILD_DIR)/asm/Game/Player/MarioWall.o \
    $(BUILD_DIR)/asm/Game/Player/MarioHang.o \
    $(BUILD_DIR)/asm/Game/Player/MarioSwim.o \
    $(BUILD_DIR)/asm/Game/Player/MarioSwimDamage.o \
    $(BUILD_DIR)/asm/Game/Player/MarioAccess.o \
    $(BUILD_DIR)/asm/Game/Player/MarioSlip.o \
    $(BUILD_DIR)/asm/Game/Player/MarioSlope.o \
    $(BUILD_DIR)/asm/Game/Player/MarioWalk.o \
    $(BUILD_DIR)/asm/Game/Player/MarioNullBck.o \
    $(BUILD_DIR)/asm/Game/Player/MarioRecovery.o \
    $(BUILD_DIR)/asm/Game/Player/MarioSlider.o \
    $(BUILD_DIR)/asm/Game/Player/MarioStep.o \
    $(BUILD_DIR)/asm/Game/Player/MarioBump.o \
    $(BUILD_DIR)/asm/Game/Player/MarioEnforce.o \
    $(BUILD_DIR)/asm/Game/Player/MarioTask.o \
    $(BUILD_DIR)/asm/Game/Player/MarioTeresa.o \
    $(BUILD_DIR)/asm/Game/Player/MarioMagic.o \
    $(BUILD_DIR)/asm/Game/Player/MarioWarp.o \
    $(BUILD_DIR)/asm/Game/Player/MarioFpView.o \
    $(BUILD_DIR)/asm/Game/Player/Mario2D.o \
    $(BUILD_DIR)/asm/Game/Player/MatrixControl.o \
    $(BUILD_DIR)/asm/Game/Player/RushEndInfo.o \
    $(BUILD_DIR)/asm/Game/Player/TornadoMario.o \
    $(BUILD_DIR)/asm/Game/Player/ModelHolder.o \
    $(BUILD_DIR)/asm/Game/Player/MarioShadow.o \
    $(BUILD_DIR)/asm/Game/Player/MarioMapCode.o \
    $(BUILD_DIR)/asm/Game/Player/MarioActorWipe.o \
    $(BUILD_DIR)/asm/Game/Player/DrawAdaptor.o \
    $(BUILD_DIR)/asm/Game/Player/PlayerEvent.o \
    $(BUILD_DIR)/asm/Game/Player/PlayerEventGameOver.o \
    $(BUILD_DIR)/asm/Game/Player/PlayerEventAbyss.o \
    $(BUILD_DIR)/asm/Game/Player/PlayerEventDown.o \
    $(BUILD_DIR)/asm/Game/Player/PlayerEventFireDown.o \
    $(BUILD_DIR)/asm/Game/Player/PlayerEventRaceDown.o \
    $(BUILD_DIR)/asm/Game/Player/PlayerEventGhostRaceDown.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/data.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudRhythmSeqParser.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudBgmTempoAdjuster.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudMeTrack.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudMeChannelMgr.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudMeSeqCtrl.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudMeSeqReader.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudMeSeqParser.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudMeTrackCallback.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudMePlayer.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudRhythmMeSystem.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudMeHandles.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudMeObject.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudChordInfo.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudRhythmHolder.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudRhythmWrap.o \
    $(BUILD_DIR)/asm/Game/Ride/data.o \
    $(BUILD_DIR)/asm/Game/Ride/BigBubble.o \
    $(BUILD_DIR)/asm/Game/Ride/Creeper.o \
    $(BUILD_DIR)/asm/Game/Ride/Fluff.o \
    $(BUILD_DIR)/asm/Game/Ride/FluffWind.o \
    $(BUILD_DIR)/asm/Game/Ride/JumpBranch.o \
    $(BUILD_DIR)/asm/Game/Ride/Plant.o \
    $(BUILD_DIR)/asm/Game/Ride/PlantLeaf.o \
    $(BUILD_DIR)/asm/Game/Ride/PlantStalk.o \
    $(BUILD_DIR)/asm/Game/Ride/Pole.o \
    $(BUILD_DIR)/asm/Game/Ride/SledRopePoint.o \
    $(BUILD_DIR)/asm/Game/Ride/SlingShooter.o \
    $(BUILD_DIR)/asm/Game/Ride/SpaceCocoon.o \
    $(BUILD_DIR)/asm/Game/Ride/SphereAccelSensorController.o \
    $(BUILD_DIR)/asm/Game/Ride/SphereController.o \
    $(BUILD_DIR)/asm/Game/Ride/SpherePadController.o \
    $(BUILD_DIR)/asm/Game/Ride/SurfRay.o \
    $(BUILD_DIR)/asm/Game/Ride/SurfRayTutorial.o \
    $(BUILD_DIR)/asm/Game/Ride/SwingRope.o \
    $(BUILD_DIR)/asm/Game/Ride/SwingRopePoint.o \
    $(BUILD_DIR)/asm/Game/Ride/Tamakoro.o \
    $(BUILD_DIR)/asm/Game/Ride/TamakoroTutorial.o \
    $(BUILD_DIR)/asm/Game/Ride/Trapeze.o \
    $(BUILD_DIR)/asm/Game/Scene/data.o \
    $(BUILD_DIR)/asm/Game/Scene/GameScene.o \
    $(BUILD_DIR)/asm/Game/Scene/GameSceneFunction.o \
    $(BUILD_DIR)/asm/Game/Scene/GameScenePauseControl.o \
    $(BUILD_DIR)/asm/Game/Scene/GameSceneScenarioOpeningCameraState.o \
    $(BUILD_DIR)/asm/Game/Scene/IntermissionScene.o \
    $(BUILD_DIR)/asm/Game/Scene/LogoScene.o \
    $(BUILD_DIR)/asm/Game/Scene/MultiSceneEffectKeeper.o \
    $(BUILD_DIR)/asm/Game/Scene/MultiSceneActor.o \
    $(BUILD_DIR)/asm/Game/Scene/PlayTimerScene.o \
    $(BUILD_DIR)/asm/Game/Scene/PlacementInfoOrdered.o \
    $(BUILD_DIR)/asm/Game/Scene/PlacementStateChecker.o \
    $(BUILD_DIR)/asm/Game/Scene/ScenarioSelectScene.o \
    $(BUILD_DIR)/asm/Game/Scene/Scene.o \
    $(BUILD_DIR)/asm/Game/Scene/SceneDataInitializer.o \
    $(BUILD_DIR)/asm/Game/Scene/SceneExecutor.o \
    $(BUILD_DIR)/asm/Game/Scene/SceneFactory.o \
    $(BUILD_DIR)/asm/Game/Scene/SceneFunction.o \
    $(BUILD_DIR)/asm/Game/Scene/SceneObjHolder.o \
    $(BUILD_DIR)/asm/Game/Scene/ScenePlayingResult.o \
    $(BUILD_DIR)/asm/Game/Scene/SceneNameObjListExecutor.o \
    $(BUILD_DIR)/asm/Game/Scene/SceneNameObjMovementController.o \
    $(BUILD_DIR)/asm/Game/Scene/StageDataHolder.o \
    $(BUILD_DIR)/asm/Game/Scene/StageFileLoader.o \
    $(BUILD_DIR)/asm/Game/Scene/StageResourceLoader.o \
    $(BUILD_DIR)/asm/Game/Scene/StopSceneController.o \
    $(BUILD_DIR)/asm/Game/Screen/data.o \
    $(BUILD_DIR)/asm/Game/Screen/Screen.o \
    $(BUILD_DIR)/asm/Game/Speaker/SpkSpeakerCtrl.o \
    $(BUILD_DIR)/asm/Game/Speaker/SpkSystem.o \
    $(BUILD_DIR)/asm/Game/Speaker/SpkMixingBuffer.o \
    $(BUILD_DIR)/asm/Game/Speaker/SpkWave.o \
    $(BUILD_DIR)/asm/Game/Speaker/SpkTable.o \
    $(BUILD_DIR)/asm/Game/Speaker/SpkData.o \
    $(BUILD_DIR)/asm/Game/Speaker/SpkSound.o \
    $(BUILD_DIR)/asm/Game/System/data.o \
    $(BUILD_DIR)/asm/Game/System/AlreadyDoneFlagInGalaxy.o \
    $(BUILD_DIR)/asm/Game/System/ArchiveHolder.o \
    $(BUILD_DIR)/asm/Game/System/AudSystemWrapper.o \
    $(BUILD_DIR)/asm/Game/System/BinaryDataChunkHolder.o \
    $(BUILD_DIR)/asm/Game/System/BinaryDataContentAccessor.o \
    $(BUILD_DIR)/asm/Game/System/DrawBuffer.o \
    $(BUILD_DIR)/asm/Game/System/DrawBufferExecuter.o \
    $(BUILD_DIR)/asm/Game/System/DrawBufferGroup.o \
    $(BUILD_DIR)/asm/Game/System/DrawBufferHolder.o \
    $(BUILD_DIR)/asm/Game/System/DrawSyncManager.o \
    $(BUILD_DIR)/asm/Game/System/FileHolder.o \
    $(BUILD_DIR)/asm/Game/System/FileLoader.o \
    $(BUILD_DIR)/asm/Game/System/FileLoaderThread.o \
    $(BUILD_DIR)/asm/Game/System/FileRipper.o \
    $(BUILD_DIR)/asm/Game/System/FunctionAsyncExecutor.o \
    $(BUILD_DIR)/asm/Game/System/GameSystem.o \
    $(BUILD_DIR)/asm/Game/System/GameSystemDimmingWatcher.o \
    $(BUILD_DIR)/asm/Game/System/GameSystemErrorWatcher.o \
    $(BUILD_DIR)/asm/Game/System/GameSystemException.o \
    $(BUILD_DIR)/asm/Game/System/GameSystemFontHolder.o \
    $(BUILD_DIR)/asm/Game/System/GameSystemFrameControl.o \
    $(BUILD_DIR)/asm/Game/System/GameSystemFunction.o \
    $(BUILD_DIR)/asm/Game/System/GameSystemObjHolder.o \
    $(BUILD_DIR)/asm/Game/System/GameSystemStationedArchiveLoader.o \
    $(BUILD_DIR)/asm/Game/System/GameSystemSceneController.o \
    $(BUILD_DIR)/asm/Game/System/GameSystemResetAndPowerProcess.o \
    $(BUILD_DIR)/asm/Game/System/HeapMemoryWatcher.o \
    $(BUILD_DIR)/asm/Game/System/Language.o \
    $(BUILD_DIR)/asm/Game/System/LayoutHolder.o \
    $(BUILD_DIR)/asm/Game/System/MainLoopFramework.o \
    $(BUILD_DIR)/asm/Game/System/MessageHolder.o \
    $(BUILD_DIR)/asm/Game/System/NANDErrorSequence.o \
    $(BUILD_DIR)/asm/Game/System/NANDManager.o \
    $(BUILD_DIR)/asm/Game/System/NANDManagerThread.o \
    $(BUILD_DIR)/asm/Game/System/NerveExecutor.o \
    $(BUILD_DIR)/asm/Game/System/OSThreadWrapper.o \
    $(BUILD_DIR)/asm/Game/System/Overwrite.o \
    $(BUILD_DIR)/asm/Game/System/PauseButtonCheckerInGame.o \
    $(BUILD_DIR)/asm/Game/System/PlacedHiddenStarScenarioTable.o \
    $(BUILD_DIR)/asm/Game/System/RenderMode.o \
    $(BUILD_DIR)/asm/Game/System/ResourceHolder.o \
    $(BUILD_DIR)/asm/Game/System/ResourceHolderManager.o \
    $(BUILD_DIR)/asm/Game/System/ResourceInfo.o \
    $(BUILD_DIR)/asm/Game/System/ScenarioDataParser.o \
    $(BUILD_DIR)/asm/Game/System/ShapePacketUserData.o \
    $(BUILD_DIR)/asm/Game/System/StarPointerOnOffController.o \
    $(BUILD_DIR)/asm/Game/System/StationedArchiveLoader.o \
    $(BUILD_DIR)/asm/Game/System/StationedFileInfo.o \
    $(BUILD_DIR)/asm/Game/System/WPad.o \
    $(BUILD_DIR)/asm/Game/System/WPadAcceleration.o \
    $(BUILD_DIR)/asm/Game/System/WPadButton.o \
    $(BUILD_DIR)/asm/Game/System/WPadHolder.o \
    $(BUILD_DIR)/asm/Game/System/WPadHVSwing.o \
    $(BUILD_DIR)/asm/Game/System/WPadInfoChecker.o \
    $(BUILD_DIR)/asm/Game/System/WPadLeaveWatcher.o \
    $(BUILD_DIR)/asm/Game/System/WPadPointer.o \
    $(BUILD_DIR)/asm/Game/System/WPadRumble.o \
    $(BUILD_DIR)/asm/Game/System/WPadRumbleData.o \
    $(BUILD_DIR)/asm/Game/System/WPadStick.o \
    $(BUILD_DIR)/asm/Game/System/HomeButtonMenuWrapper.o \
    $(BUILD_DIR)/asm/Game/System/HomeButtonStateNotifier.o \
    $(BUILD_DIR)/asm/Game/System/ConfigDataHolder.o \
    $(BUILD_DIR)/asm/Game/System/ConfigDataMii.o \
    $(BUILD_DIR)/asm/Game/System/ConfigDataMisc.o \
    $(BUILD_DIR)/asm/Game/System/FindingLuigiEventScheduler.o \
    $(BUILD_DIR)/asm/Game/System/GalaxyCometScheduler.o \
    $(BUILD_DIR)/asm/Game/System/GalaxyCometState.o \
    $(BUILD_DIR)/asm/Game/System/GalaxyMoveArgument.o \
    $(BUILD_DIR)/asm/Game/System/GalaxyNameSortTable.o \
    $(BUILD_DIR)/asm/Game/System/GalaxyStatusAccessor.o \
    $(BUILD_DIR)/asm/Game/System/GameDataConst.o \
    $(BUILD_DIR)/asm/Game/System/GameDataFunction.o \
    $(BUILD_DIR)/asm/Game/System/GameDataGalaxyStorage.o \
    $(BUILD_DIR)/asm/Game/System/GameDataHolder.o \
    $(BUILD_DIR)/asm/Game/System/GameDataPlayerStatus.o \
    $(BUILD_DIR)/asm/Game/System/GameDataTemporaryInGalaxy.o \
    $(BUILD_DIR)/asm/Game/System/GameEventFlag.o \
    $(BUILD_DIR)/asm/Game/System/GameEventFlagTable.o \
    $(BUILD_DIR)/asm/Game/System/GameEventFlagChecker.o \
    $(BUILD_DIR)/asm/Game/System/GameEventFlagStorage.o \
    $(BUILD_DIR)/asm/Game/System/GameEventValueChecker.o \
    $(BUILD_DIR)/asm/Game/System/GameSequenceDirector.o \
    $(BUILD_DIR)/asm/Game/System/GameSequenceFunction.o \
    $(BUILD_DIR)/asm/Game/System/GameSequenceProgress.o \
    $(BUILD_DIR)/asm/Game/System/LuigiLeftSupplier.o \
    $(BUILD_DIR)/asm/Game/System/SaveDataBannerCreator.o \
    $(BUILD_DIR)/asm/Game/System/SaveDataFileAccessor.o \
    $(BUILD_DIR)/asm/Game/System/SaveDataHandler.o \
    $(BUILD_DIR)/asm/Game/System/SaveDataHandleSequence.o \
    $(BUILD_DIR)/asm/Game/System/ScenarioProgressTestRun.o \
    $(BUILD_DIR)/asm/Game/System/SpinDriverPathStorage.o \
    $(BUILD_DIR)/asm/Game/System/StageResultSequenceChecker.o \
    $(BUILD_DIR)/asm/Game/System/StarPieceAlmsStorage.o \
    $(BUILD_DIR)/asm/Game/System/StorySequenceExecutor.o \
    $(BUILD_DIR)/asm/Game/System/SysConfigFile.o \
    $(BUILD_DIR)/asm/Game/System/UserFile.o \
    $(BUILD_DIR)/asm/Game/Util/data.o \
    $(BUILD_DIR)/asm/Game/Util/ActorCameraUtil.o \
    $(BUILD_DIR)/asm/Game/Util/ActorMovementUtil.o \
    $(BUILD_DIR)/asm/Game/Util/ActorSensorUtil.o \
    $(BUILD_DIR)/asm/Game/Util/ActorShadowLocalUtil.o \
    $(BUILD_DIR)/asm/Game/Util/ActorShadowUtil.o \
    $(BUILD_DIR)/asm/Game/Util/ActorStateUtil.o \
    $(BUILD_DIR)/asm/Game/Util/ActorSwitchUtil.o \
    $(BUILD_DIR)/asm/Game/Util/BitArray.o \
    $(BUILD_DIR)/asm/Game/Util/CameraUtil.o \
    $(BUILD_DIR)/asm/Game/Util/DemoUtil.o \
    $(BUILD_DIR)/asm/Game/Util/DrawUtil.o \
    $(BUILD_DIR)/asm/Game/Util/EffectUtil.o \
    $(BUILD_DIR)/asm/Game/Util/EventUtil.o \
    $(BUILD_DIR)/asm/Game/Util/FileUtil.o \
    $(BUILD_DIR)/asm/Game/Util/FootPrint.o \
    $(BUILD_DIR)/asm/Game/Util/FurCtrl.o \
    $(BUILD_DIR)/asm/Game/Util/FurDrawer.o \
    $(BUILD_DIR)/asm/Game/Util/FurMulti.o \
    $(BUILD_DIR)/asm/Game/Util/FurShader.o \
    $(BUILD_DIR)/asm/Game/Util/GamePadUtil.o \
    $(BUILD_DIR)/asm/Game/Util/GravityUtil.o \
    $(BUILD_DIR)/asm/Game/Util/HashUtil.o \
    $(BUILD_DIR)/asm/Game/Util/JMapUtil.o \
    $(BUILD_DIR)/asm/Game/Util/JointUtil.o \
    $(BUILD_DIR)/asm/Game/Util/LayoutUtil.o \
    $(BUILD_DIR)/asm/Game/Util/LightUtil.o \
    $(BUILD_DIR)/asm/Game/Util/LiveActorUtil.o \
    $(BUILD_DIR)/asm/Game/Util/MapPartsUtil.o \
    $(BUILD_DIR)/asm/Game/Util/MapUtil.o \
    $(BUILD_DIR)/asm/Game/Util/MathUtil.o \
    $(BUILD_DIR)/asm/Game/Util/MemoryUtil.o \
    $(BUILD_DIR)/asm/Game/Util/MessageUtil.o \
    $(BUILD_DIR)/asm/Game/Util/ModelUtil.o \
    $(BUILD_DIR)/asm/Game/Util/MtxUtil.o \
    $(BUILD_DIR)/asm/Game/Util/MultiEventCamera.o \
    $(BUILD_DIR)/asm/Game/Util/NerveUtil.o \
    $(BUILD_DIR)/asm/Game/Util/NPCUtil.o \
    $(BUILD_DIR)/asm/Game/Util/ObjUtil.o \
    $(BUILD_DIR)/asm/Game/Util/ParabolicPath.o \
    $(BUILD_DIR)/asm/Game/Util/PlayerUtil.o \
    $(BUILD_DIR)/asm/Game/Util/RailGraphUtil.o \
    $(BUILD_DIR)/asm/Game/Util/RailUtil.o \
    $(BUILD_DIR)/asm/Game/Util/SceneUtil.o \
    $(BUILD_DIR)/asm/Game/Util/SchedulerUtil.o \
    $(BUILD_DIR)/asm/Game/Util/ScreenUtil.o \
    $(BUILD_DIR)/asm/Game/Util/SequenceUtil.o \
    $(BUILD_DIR)/asm/Game/Util/ShareUtil.o \
    $(BUILD_DIR)/asm/Game/Util/SoundUtil.o \
    $(BUILD_DIR)/asm/Game/Util/StarPointerUtil.o \
    $(BUILD_DIR)/asm/Game/Util/StringUtil.o \
    $(BUILD_DIR)/asm/Game/Util/SwitchEventFunctorListener.o \
    $(BUILD_DIR)/asm/Game/Util/SystemUtil.o \
    $(BUILD_DIR)/asm/Game/Util/TalkUtil.o \
    $(BUILD_DIR)/asm/Game/Util/AreaObjUtil.o \
    $(BUILD_DIR)/asm/Game/Util/BaseMatrixFollowTargetHolder.o \
    $(BUILD_DIR)/asm/Game/Util/BezierSurface.o \
    $(BUILD_DIR)/asm/Game/Util/BothDirList.o \
    $(BUILD_DIR)/asm/Game/Util/CollisionPartsFilter.o \
    $(BUILD_DIR)/asm/Game/Util/DirectDraw.o \
    $(BUILD_DIR)/asm/Game/Util/DirectDrawUtil.o \
    $(BUILD_DIR)/asm/Game/Util/FixedPosition.o \
    $(BUILD_DIR)/asm/Game/Util/GeometryBindUtil.o \
    $(BUILD_DIR)/asm/Game/Util/IKJoint.o \
    $(BUILD_DIR)/asm/Game/Util/JMapIdInfo.o \
    $(BUILD_DIR)/asm/Game/Util/JMapInfo.o \
    $(BUILD_DIR)/asm/Game/Util/JMapLinkInfo.o \
    $(BUILD_DIR)/asm/Game/Util/JointController.o \
    $(BUILD_DIR)/asm/Game/Util/JointRumbler.o \
    $(BUILD_DIR)/asm/Game/Util/OctahedronBezierSurface.o \
    $(BUILD_DIR)/asm/Game/Util/PostureHolder.o \
    $(BUILD_DIR)/asm/Game/Util/RumbleCalculator.o \
    $(BUILD_DIR)/asm/Game/Util/SpringValue.o \
    $(BUILD_DIR)/asm/Game/Util/TriangleFilter.o \
    $(BUILD_DIR)/asm/Game/Util/TriggerChecker.o \
    $(BUILD_DIR)/asm/Game/Util/ValueControl.o \
    $(BUILD_DIR)/asm/Game/NWC24/NWC24Function.o \
    $(BUILD_DIR)/asm/Game/NWC24/NWC24Messenger.o \
    $(BUILD_DIR)/asm/Game/NWC24/NWC24SendThread.o \
    $(BUILD_DIR)/asm/Game/NWC24/NWC24System.o \
    $(BUILD_DIR)/asm/Game/NWC24/UTF16Util.o \
    $(BUILD_DIR)/asm/Game/NWC24/LuigiMailDirector.o \
    $(BUILD_DIR)/asm/Game/NWC24/ReceiverTagMail.o \
    $(BUILD_DIR)/asm/JSystem/JKernel/JKernel.o \
    $(BUILD_DIR)/asm/JSystem/JSupport/JSupport.o \
    $(BUILD_DIR)/asm/JSystem/JGadget/JGadget.o \
    $(BUILD_DIR)/asm/JSystem/JUtility/JUtility.o \
    $(BUILD_DIR)/asm/JSystem/J2D/J2DGraphContext.o \
    $(BUILD_DIR)/asm/JSystem/J2D/J2DOrthoGraph.o \
    $(BUILD_DIR)/asm/JSystem/J2D/J2DFillBox.o \
    $(BUILD_DIR)/asm/JSystem/J2D/JUTTexture.o \
    $(BUILD_DIR)/asm/JSystem/J2D/J2DPane.o \
    $(BUILD_DIR)/asm/JSystem/J2D/J2DPicture.o \
    $(BUILD_DIR)/asm/JSystem/J2D/get.o \
    $(BUILD_DIR)/asm/JSystem/J3D/J3DGraphBase/J3DGraphBase.o \
    $(BUILD_DIR)/asm/JSystem/J3D/J3DGraphAnimator/J3DGraphAnimator.o \
    $(BUILD_DIR)/asm/JSystem/J3D/J3DGraphLoader/J3DGraphLoader.o \
    $(BUILD_DIR)/asm/JSystem/JMath/JMAEulerToQuat.o \
    $(BUILD_DIR)/asm/JSystem/JMath/JMAQuatLerp.o \
    $(BUILD_DIR)/asm/JSystem/JMath/JMAVECScaleAdd.o \
    $(BUILD_DIR)/asm/JSystem/JMath/JMAVECLerp.o \
    $(BUILD_DIR)/asm/JSystem/JMath/JMAMTXApplyScale.o \
    $(BUILD_DIR)/asm/JSystem/JMath/JMath.o \
    $(BUILD_DIR)/asm/JSystem/JParticle/JParticle.o \
    $(BUILD_DIR)/asm/RVL/gd.o   \
    $(BUILD_DIR)/asm/RVL/kpad.o   \
    $(BUILD_DIR)/asm/RVL/thp.o   \
    $(BUILD_DIR)/asm/RVL/tpl.o   \
    $(BUILD_DIR)/asm/RVL/wenc.o   \
    $(BUILD_DIR)/asm/RVL/rso.o   \
    $(BUILD_DIR)/asm/RVL/RVLFaceLib.o   \
    $(BUILD_DIR)/asm/RevoEx/net.o   \
    $(BUILD_DIR)/asm/RevoEx/nwc24.o   \
    $(BUILD_DIR)/asm/RevoEx/vf.o   \
    $(BUILD_DIR)/asm/JSystem/JAudio2/JAudio2.o   \
    $(BUILD_DIR)/asm/RVL/aralt.o   \
    $(BUILD_DIR)/asm/RVL/base.o   \
    $(BUILD_DIR)/asm/RVL/os.o   \
    $(BUILD_DIR)/asm/RVL/exi.o   \
    $(BUILD_DIR)/asm/RVL/si.o   \
    $(BUILD_DIR)/asm/RVL/db.o   \
    $(BUILD_DIR)/asm/RVL/vi.o   \
    $(BUILD_DIR)/asm/RVL/mtx.o   \
    $(BUILD_DIR)/asm/RVL/gx.o   \
    $(BUILD_DIR)/asm/RVL/dvd.o   \
    $(BUILD_DIR)/asm/RVL/ai.o   \
    $(BUILD_DIR)/asm/RVL/ax.o   \
    $(BUILD_DIR)/asm/RVL/axfx.o   \
    $(BUILD_DIR)/asm/RVL/mem.o   \
    $(BUILD_DIR)/asm/RVL/code_80CA34C.o   \
    $(BUILD_DIR)/asm/RVL/dsp.o   \
    $(BUILD_DIR)/asm/RVL/nand.o   \
    $(BUILD_DIR)/asm/RVL/sc.o   \
    $(BUILD_DIR)/asm/RVL/arc.o   \
    $(BUILD_DIR)/asm/RVL/esp.o   \
    $(BUILD_DIR)/asm/RVL/ipc.o   \
    $(BUILD_DIR)/asm/RVL/fs.o   \
    $(BUILD_DIR)/asm/RVL/pad.o   \
    $(BUILD_DIR)/asm/RVL/wpad.o   \
    $(BUILD_DIR)/asm/RVL/euart.o   \
    $(BUILD_DIR)/asm/RVL/usb.o   \
    $(BUILD_DIR)/asm/RVL/wud.o   \
    $(BUILD_DIR)/asm/RVL/bte.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/Runtime/__mem.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/Runtime/__va_arg.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/Runtime/global_destructor_chain.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/Runtime/NMWException.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/Runtime/ptmf.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/Runtime/runtime.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/Runtime/__init_cpp_exceptions.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/Runtime/Gecko_ExceptionPPC.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/Runtime/GCN_mem_alloc.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/alloc.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/ansi_files.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/ansi_fp.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/arith.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/buffer_io.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/ctype.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/direct_io.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/file_io.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/FILE_POS.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/mbstring.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/mem.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/mem_funcs.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/math_api.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/misc_io.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/printf.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/scanf.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/signal.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/string.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/strtold.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/strtoul.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/wmem.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/wprintf.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/wstring.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/wchar_io.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/uart_console_io_gcn.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/abort_exit_ppc_eabi.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/math_sun.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/extras.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_acos.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_asin.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_atan2.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_fmod.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_log.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_log10.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_pow.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_rem_pio2.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/k_cos.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/k_rem_pio2.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/k_sin.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/k_tan.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_atan.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_ceil.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_copysign.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_cos.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_floor.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_frexp.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_ldexp.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_sin.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_tan.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_acos.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_asin.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_atan2.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_fmod.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_log10.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_pow.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_sqrt.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/SRC/math_ppc.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_sqrt.o   \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/mainloop.o    \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/nubevent.o    \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/nubinit.o    \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/msg.o    \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/msgbuf.o    \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/serpoll.o    \
    $(BUILD_DIR)/src/runtime_libs/debugger/embedded/MetroTRK/Os/dolphin/usr_put.o \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Os/dolphin/usr_put.o \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/dispatch.o    \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/msghndlr.o    \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/support.o    \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/mutex_TRK.o  \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/notify.o     \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Processor/ppc/Generic/flush_cache.o \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/mem_TRK.o    \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/string_TRK.o \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Processor/ppc/Generic/targimpl.o \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Processor/ppc/Generic/targsupp.o \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Processor/ppc/Generic/mpc_7xx_603e.o \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Export/mslsupp.o      \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Os/dolphin/dolphin_trk.o  \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/main_TRK.o   \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Os/dolphin/dolphin_trk_glue.o \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Os/dolphin/targcont.o \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Os/dolphin/target_options.o   \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Os/dolphin/UDP_Stubs.o    \
    $(BUILD_DIR)/asm/runtime_libs/gamedev/cust_connection/cc/exi2/GCN/EXI2_GDEV_GCN/main.o   \
    $(BUILD_DIR)/asm/runtime_libs/gamedev/cust_connection/utils/common/CircleBuffer.o   \
    $(BUILD_DIR)/asm/runtime_libs/gamedev/cust_connection/utils/gc/MWCriticalSection_gc.o  \
    $(BUILD_DIR)/asm/ndev/DebuggerDriver.o  \
    $(BUILD_DIR)/asm/ndev/exi2.o  \

CTORS_O_FILES :=                                    \
    $(BUILD_DIR)/asm/ctors.o

DTORS_O_FILES :=                                    \
    $(BUILD_DIR)/asm/dtors.o

RODATA_O_FILES :=                                   \
    $(BUILD_DIR)/asm/rodata.o

DATA_O_FILES :=                                     \
    $(BUILD_DIR)/asm/data.o

BSS_O_FILES :=                                      \
    $(BUILD_DIR)/asm/bss.o

SDATA_O_FILES :=                                    \
    $(BUILD_DIR)/asm/sdata.o

SDATA2_O_FILES :=                                   \
    $(BUILD_DIR)/asm/sdata2.o

SBSS2_O_FILES :=                                   \
    $(BUILD_DIR)/asm/sbss2.o