INIT_O_FILES := 						            \
	$(BUILD_DIR)/asm/init.o

EXTAB_O_FILES :=                                    \
    $(BUILD_DIR)/asm/extab.o

EXTABINDEX_O_FILES :=                               \
    $(BUILD_DIR)/asm/extabindex.o

NW4R_O_FILES := 					            \
    $(BUILD_DIR)/asm/nw4r/libnw4r_ut.o   \
    $(BUILD_DIR)/asm/nw4r/libnw4r_db.o   \
    $(BUILD_DIR)/asm/nw4r/libnw4r_math.o   \
    $(BUILD_DIR)/asm/nw4r/libnw4r_lyt.o   \

GAME_ANIM_O_FILES := \
    $(BUILD_DIR)/asm/Game/Animation/AnmPlayer.o \
    $(BUILD_DIR)/asm/Game/Animation/BckCtrl.o \
    $(BUILD_DIR)/asm/Game/Animation/BpkPlayer.o \
    $(BUILD_DIR)/asm/Game/Animation/BrkPlayer.o \
    $(BUILD_DIR)/asm/Game/Animation/BtkPlayer.o \
    $(BUILD_DIR)/asm/Game/Animation/BtpPlayer.o \
    $(BUILD_DIR)/asm/Game/Animation/BvaPlayer.o \
    $(BUILD_DIR)/asm/Game/Animation/LayoutAnmPlayer.o \
    $(BUILD_DIR)/asm/Game/Animation/MaterialAnmBuffer.o \
    $(BUILD_DIR)/asm/Game/Animation/XanimeCore.o \
    $(BUILD_DIR)/asm/Game/Animation/XanimePlayer.o \
    $(BUILD_DIR)/asm/Game/Animation/XanimeResource.o

AREAOBJ_O_FILES := \
    $(BUILD_DIR)/asm/Game/AreaObj/AreaForm.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/AreaFormDrawer.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/AreaObj.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/AreaObjContainer.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/AreaObjFollower.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/AstroChangeStageCube.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/AudioEffectArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/BgmProhibitArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/BigBubbleCameraArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/BigBubbleGoalArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/BloomArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/CameraRepulsiveArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/ChangeBgmCube.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/CollisionArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/CubeCamera.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/DeathArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/DepthOfFieldArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/FollowCollisionArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/GlaringLightArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/HazeCube.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/ImageEffectArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/LightArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/LightAreaHolder.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/MercatorTransformCube.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/MessageArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/PlayerSeArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/QuakeEffectArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/RestartCube.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/ScreenBlurArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/SimpleBloomArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/SoundEmitterCube.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/SoundEmitterSphere.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/SpinGuidanceArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/SunLightArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/SwitchArea.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/WarpCube.o    \
    $(BUILD_DIR)/asm/Game/AreaObj/WaterArea.o 

TEXT_O_FILES :=     \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSystem.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSystemVolumeController.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudAudience.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSoundInfo.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudWrap.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSoundObject.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSoundObject_Kawamura.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSoundObject_Takezawa.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSoundObject_Gohara.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudAnmSoundObject.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudBgm.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudBgmKeeper.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudBgmMgr.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudBgmRhythmStrategy.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudBgmSetting.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudBgmVolumeController.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudEffector.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudFader.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudLimitedSound.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudMeNameConverter.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudMicWrap.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudRemixMgr.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudRemixSequencer.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSceneMgr.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSeStrategy.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSoundNameConverter.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSoundObjHolder.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudSpeakerWrap.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudTrackController.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/AudUtil.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/OverwriteJAudio.o    \
    $(BUILD_DIR)/asm/Game/AudioLib/CSSoundNameConverter.o    \
    $(BUILD_DIR)/asm/Game/Boss/BossAccessor.o \
    $(BUILD_DIR)/asm/Game/Boss/BossBegoman/BossBegoman.o \
    $(BUILD_DIR)/asm/Game/Boss/BossBegoman/BossBegomanHead.o \
    $(BUILD_DIR)/asm/Game/Boss/BossKameck/BossKameck.o \
    $(BUILD_DIR)/asm/Game/Boss/BossKameck/BossKameckAction.o \
    $(BUILD_DIR)/asm/Game/Boss/BossKameck/BossKameckBarrier.o \
    $(BUILD_DIR)/asm/Game/Boss/BossKameck/BossKameckBattleDemo.o \
    $(BUILD_DIR)/asm/Game/Boss/BossKameck/BossKameckBattlePattarn.o \
    $(BUILD_DIR)/asm/Game/Boss/BossKameck/BossKameckSequencer.o \
    $(BUILD_DIR)/asm/Game/Boss/BossKameck/BossKameckMoveRail.o \
    $(BUILD_DIR)/asm/Game/Boss/BossKameck/BossKameckVs1.o \
    $(BUILD_DIR)/asm/Game/Boss/BossKameck/BossKameckVs2.o \
    $(BUILD_DIR)/asm/Game/Boss/BossKameck/BossKameckStateBattle.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBug.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugActionBase.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugActionFlyHigh.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugActionFlyLow.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugActionGround.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugActionSequencer.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugAngryDemo.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugBomb.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugBombHolder.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugFinishDemo.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugFlyDemo.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugFunction.o \
    $(BUILD_DIR)/asm/Game/Boss/BossStinkBug/BossStinkBugOpeningDemo.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackun.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunAction.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunBall.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunBattleEgg.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunBattleEggVs2.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunBattleVs1Lv1.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunBattleVs1Lv2.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunBattleVs2Lv1.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunDemo.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunDemoPosition.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunEggShell.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunFire.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunSequencer.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunStateAwake.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunStateDamage.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunStateFire.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunTail.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunTailNode.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunTailPart.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunTailRoot.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunTrackFire.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunVs1.o \
    $(BUILD_DIR)/asm/Game/Boss/DinoPackun/DinoPackunVs2.o \
    $(BUILD_DIR)/asm/Game/Boss/Dodoryu/Dodoryu.o \
    $(BUILD_DIR)/asm/Game/Boss/Dodoryu/DodoryuDemo.o \
    $(BUILD_DIR)/asm/Game/Boss/Dodoryu/DodoryuHill.o \
    $(BUILD_DIR)/asm/Game/Boss/Dodoryu/DodoryuMove.o \
    $(BUILD_DIR)/asm/Game/Boss/Dodoryu/DodoryuStateBase.o \
    $(BUILD_DIR)/asm/Game/Boss/Dodoryu/DodoryuStateLv1.o \
    $(BUILD_DIR)/asm/Game/Boss/Dodoryu/DodoryuStateLv2.o \
    $(BUILD_DIR)/asm/Game/Boss/Dodoryu/DodoryuStateWait.o \
    $(BUILD_DIR)/asm/Game/Boss/Dodoryu/DodoryuUtil.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/Koopa.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaBattleBase.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaBattleMain.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaBattleStairsBase.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaBattleStairsVs1.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaBattleStairsVs3.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaBattleVs3Lv1.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaBattleVs3Lv2.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaDemoPowerUp.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaDemoFallToPlanetVs3Lv2.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaDemoFallToPlanetVs3Lv3.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaDemoJumpToPlanet.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaFigureBall.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaFireShort.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaFireStairs.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaFunction.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaParts.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaPowerUpSwitch.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaPlanetShadow.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaRestarterVs3.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaRockBreak.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaSensorCtrl.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaSequencer.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaSubSequenceBattle.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaSequencerVs1.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaSequencerVs2.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaSequencerVs3.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaShockWave.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaStateAttackFireShort.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaStateAttackFireLong.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaStateAttackHipDrop.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaStateAttackRoll.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaStateAttackShockWave.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaStateAttackSpin.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaStateChaseRoll.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaStateDamageEscape.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaStateGuard.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaStateJumpAway.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaSwitchKeeper.o \
    $(BUILD_DIR)/asm/Game/Boss/Koopa/KoopaViewSwitchKeeper.o \
    $(BUILD_DIR)/asm/Game/Boss/OtaKing/OtaKing.o \
    $(BUILD_DIR)/asm/Game/Boss/OtaKing/OtaKingLongFoot.o \
    $(BUILD_DIR)/asm/Game/Boss/OtaKing/OtaKingMagma.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/Polta.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaActionBase.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaActionSequencer.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaArm.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaBattleLv1.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaBattleLv2.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaDemo.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaFunction.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaGroundRock.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaGroundRockHolder.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaRock.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaRockHolder.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaSensorCtrl.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaStateAttackGround.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaStateGenerateRock.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaStateGroundRockAttack.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaStatePunch.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaStateStagger.o \
    $(BUILD_DIR)/asm/Game/Boss/Polta/PoltaWaitStart.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishBaby.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishBabyRail.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishBabyRailHolder.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishBoss.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishBossBattleDirector.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishBossFunc.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishBossInfo.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishBossRail.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishBossRailHolder.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishGuard.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishGuardHolder.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishJointCalc.o \
    $(BUILD_DIR)/asm/Game/Boss/SkeletalFishBoss/SkeletalFishRailControl.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpider.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderAcid.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderAction1st.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderAction2nd.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderActionBase.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderActionCocoon.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderDemo.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderEnvironment.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderFunction.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderGland.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderParts.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderSensorCtrl.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderStateSwoon.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderThreadAttacher.o \
    $(BUILD_DIR)/asm/Game/Boss/TombSpider/TombSpiderVitalSpot.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBoss.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossAccesser.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossBaseJointPosition.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossBreakMovement.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossCoin.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossCore.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossFixParts.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossFixPartsBase.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossGuardWall.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossGuardWallPart.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossKillerGenerater.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossKillerGeneraterCircle.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossKinokoOneUp.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossLeg.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossMovableArea.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossRailMoveParts.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossRotateParts.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossShell.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossStepPoint.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossStepSequence.o \
    $(BUILD_DIR)/asm/Game/Boss/TripodBoss/TripodBossStepStartArea.o \
    $(BUILD_DIR)/asm/Game/Camera/Camera.o \
    $(BUILD_DIR)/asm/Game/Demo/Demo.o \
    $(BUILD_DIR)/asm/Game/Effect/Effect.o \
    $(BUILD_DIR)/asm/Game/Enemy/AnimScaleController.o \
    $(BUILD_DIR)/asm/Game/Enemy/AnimStampController.o \
    $(BUILD_DIR)/asm/Game/Enemy/BallBeamer.o \
    $(BUILD_DIR)/asm/Game/Enemy/Balloonfish.o \
    $(BUILD_DIR)/asm/Game/Enemy/BasaBasa.o \
    $(BUILD_DIR)/asm/Game/Enemy/BegomanBaby.o \
    $(BUILD_DIR)/asm/Game/Enemy/BegomanBase.o \
    $(BUILD_DIR)/asm/Game/Enemy/BegomanFunction.o \
    $(BUILD_DIR)/asm/Game/Enemy/BegomanLauncher.o \
    $(BUILD_DIR)/asm/Game/Enemy/BegomanSpike.o \
    $(BUILD_DIR)/asm/Game/Enemy/BegomanSpring.o \
    $(BUILD_DIR)/asm/Game/Enemy/BegomanSpringHead.o \
    $(BUILD_DIR)/asm/Game/Enemy/Birikyu.o \
    $(BUILD_DIR)/asm/Game/Enemy/BombBird.o \
    $(BUILD_DIR)/asm/Game/Enemy/BombBirdBomb.o \
    $(BUILD_DIR)/asm/Game/Enemy/BombHei.o \
    $(BUILD_DIR)/asm/Game/Enemy/BombHeiLauncher.o \
    $(BUILD_DIR)/asm/Game/Enemy/BombTeresa.o \
    $(BUILD_DIR)/asm/Game/Enemy/CannonShellBase.o \
    $(BUILD_DIR)/asm/Game/Enemy/CocoNutBall.o \
    $(BUILD_DIR)/asm/Game/Enemy/CocoSambo.o \
    $(BUILD_DIR)/asm/Game/Enemy/DharmaSambo.o \
    $(BUILD_DIR)/asm/Game/Enemy/Dossun.o \
    $(BUILD_DIR)/asm/Game/Enemy/ElectricPressureBullet.o \
    $(BUILD_DIR)/asm/Game/Enemy/EyeBeamer.o \
    $(BUILD_DIR)/asm/Game/Enemy/FireBall.o \
    $(BUILD_DIR)/asm/Game/Enemy/FireBubble.o \
    $(BUILD_DIR)/asm/Game/Enemy/Gesso.o \
    $(BUILD_DIR)/asm/Game/Enemy/HammerHeadPackun.o \
    $(BUILD_DIR)/asm/Game/Enemy/Hanachan.o \
    $(BUILD_DIR)/asm/Game/Enemy/HomingKiller.o \
    $(BUILD_DIR)/asm/Game/Enemy/IceMerameraKing.o \
    $(BUILD_DIR)/asm/Game/Enemy/ItemGenerator.o \
    $(BUILD_DIR)/asm/Game/Enemy/Jellyfish.o \
    $(BUILD_DIR)/asm/Game/Enemy/JellyfishElectric.o \
    $(BUILD_DIR)/asm/Game/Enemy/Jiraira.o \
    $(BUILD_DIR)/asm/Game/Enemy/JumpBeamer.o \
    $(BUILD_DIR)/asm/Game/Enemy/JumpGuarder.o \
    $(BUILD_DIR)/asm/Game/Enemy/JumpSpider.o \
    $(BUILD_DIR)/asm/Game/Enemy/Kabokuri.o \
    $(BUILD_DIR)/asm/Game/Enemy/KabokuriFire.o \
    $(BUILD_DIR)/asm/Game/Enemy/KabokuriFireHolder.o \
    $(BUILD_DIR)/asm/Game/Enemy/Kameck.o \
    $(BUILD_DIR)/asm/Game/Enemy/KameckBeam.o \
    $(BUILD_DIR)/asm/Game/Enemy/KameckBeamHolder.o \
    $(BUILD_DIR)/asm/Game/Enemy/KameckFireBall.o \
    $(BUILD_DIR)/asm/Game/Enemy/KameckHolder.o \
    $(BUILD_DIR)/asm/Game/Enemy/KameckTurtle.o \
    $(BUILD_DIR)/asm/Game/Enemy/Kanina.o \
    $(BUILD_DIR)/asm/Game/Enemy/Karikari.o \
    $(BUILD_DIR)/asm/Game/Enemy/KarikariDirector.o \
    $(BUILD_DIR)/asm/Game/Enemy/Karon.o \
    $(BUILD_DIR)/asm/Game/Enemy/Kiraira.o \
    $(BUILD_DIR)/asm/Game/Enemy/KirairaChain.o \
    $(BUILD_DIR)/asm/Game/Enemy/KoopaJrShip.o \
    $(BUILD_DIR)/asm/Game/Enemy/KoopaJrShipCannonMainShell.o \
    $(BUILD_DIR)/asm/Game/Enemy/KoopaJrShipCannonShell.o \
    $(BUILD_DIR)/asm/Game/Enemy/KoteBug.o \
    $(BUILD_DIR)/asm/Game/Enemy/Kuribo.o \
    $(BUILD_DIR)/asm/Game/Enemy/KuriboChief.o \
    $(BUILD_DIR)/asm/Game/Enemy/KuriboMini.o \
    $(BUILD_DIR)/asm/Game/Enemy/MechanicKoopaMini.o \
    $(BUILD_DIR)/asm/Game/Enemy/Meramera.o \
    $(BUILD_DIR)/asm/Game/Enemy/Metbo.o \
    $(BUILD_DIR)/asm/Game/Enemy/Mogu.o \
    $(BUILD_DIR)/asm/Game/Enemy/Mogucchi.o \
    $(BUILD_DIR)/asm/Game/Enemy/MogucchiHill.o \
    $(BUILD_DIR)/asm/Game/Enemy/MogucchiRefuseTerritory.o \
    $(BUILD_DIR)/asm/Game/Enemy/MogucchiShooter.o \
    $(BUILD_DIR)/asm/Game/Enemy/MoguStone.o \
    $(BUILD_DIR)/asm/Game/Enemy/NokonokoLand.o \
    $(BUILD_DIR)/asm/Game/Enemy/Onimasu.o \
    $(BUILD_DIR)/asm/Game/Enemy/OnimasuJump.o \
    $(BUILD_DIR)/asm/Game/Enemy/OnimasuPivot.o \
    $(BUILD_DIR)/asm/Game/Enemy/OtaRock.o \
    $(BUILD_DIR)/asm/Game/Enemy/PackunPetit.o \
    $(BUILD_DIR)/asm/Game/Enemy/Petari.o \
    $(BUILD_DIR)/asm/Game/Enemy/Poihana.o \
    $(BUILD_DIR)/asm/Game/Enemy/Pukupuku.o \
    $(BUILD_DIR)/asm/Game/Enemy/RingBeam.o \
    $(BUILD_DIR)/asm/Game/Enemy/RingBeamer.o \
    $(BUILD_DIR)/asm/Game/Enemy/SamboFunction.o \
    $(BUILD_DIR)/asm/Game/Enemy/SamboHead.o \
    $(BUILD_DIR)/asm/Game/Enemy/SearchBeamer.o \
    $(BUILD_DIR)/asm/Game/Enemy/Snakehead.o \
    $(BUILD_DIR)/asm/Game/Enemy/SpinHitController.o \
    $(BUILD_DIR)/asm/Game/Enemy/StinkBugBase.o \
    $(BUILD_DIR)/asm/Game/Enemy/StinkBugParent.o \
    $(BUILD_DIR)/asm/Game/Enemy/StinkBugSmall.o \
    $(BUILD_DIR)/asm/Game/Enemy/StringSpider.o \
    $(BUILD_DIR)/asm/Game/Enemy/Takobo.o \
    $(BUILD_DIR)/asm/Game/Enemy/TakoHei.o \
    $(BUILD_DIR)/asm/Game/Enemy/TakoHeiInk.o \
    $(BUILD_DIR)/asm/Game/Enemy/TakoHeiInkHolder.o \
    $(BUILD_DIR)/asm/Game/Enemy/Teresa.o \
    $(BUILD_DIR)/asm/Game/Enemy/TeresaWater.o \
    $(BUILD_DIR)/asm/Game/Enemy/TerritoryMover.o \
    $(BUILD_DIR)/asm/Game/Enemy/Unizo.o \
    $(BUILD_DIR)/asm/Game/Enemy/UnizoLauncher.o \
    $(BUILD_DIR)/asm/Game/Enemy/WalkerStateBindStarPointer.o \
    $(BUILD_DIR)/asm/Game/Enemy/WalkerStateBlowDamage.o \
    $(BUILD_DIR)/asm/Game/Enemy/WalkerStateChase.o \
    $(BUILD_DIR)/asm/Game/Enemy/WalkerStateFindPlayer.o \
    $(BUILD_DIR)/asm/Game/Enemy/WalkerStateFunction.o \
    $(BUILD_DIR)/asm/Game/Enemy/WalkerStateParam.o \
    $(BUILD_DIR)/asm/Game/Enemy/WalkerStateRunaway.o \
    $(BUILD_DIR)/asm/Game/Enemy/WalkerStateStagger.o \
    $(BUILD_DIR)/asm/Game/Enemy/WalkerStateWander.o \
    $(BUILD_DIR)/asm/Game/Enemy/WaterBazooka.o \
    $(BUILD_DIR)/asm/Game/Enemy/WaterBazookaCapsule.o \
    $(BUILD_DIR)/asm/Game/GameAudio/GameAudio.o \
    $(BUILD_DIR)/asm/Game/Gravity/ConeGravity/ConeGravity.o \
    $(BUILD_DIR)/asm/Game/Gravity/ConeGravity/setLocalMatrix.o \
    $(BUILD_DIR)/asm/Game/Gravity/ConeGravity/setEnableBottom.o \
    $(BUILD_DIR)/asm/Game/Gravity/ConeGravity/setTopCutRate.o \
    $(BUILD_DIR)/asm/Game/Gravity/JGeometry/isZero.o \
    $(BUILD_DIR)/asm/Game/Gravity/CubeGravity/CubeGravity.o \
    $(BUILD_DIR)/asm/Game/Gravity/ParallelGravity/setRangeBox.o \
    $(BUILD_DIR)/asm/Game/Gravity/CubeGravity/CubeGravity_methods.o \
    $(BUILD_DIR)/asm/Game/Gravity/JGeometry/normalize.o \
    $(BUILD_DIR)/asm/Game/Gravity/DiskGravity/DiskGravity.o \
    $(BUILD_DIR)/asm/Game/Gravity/DiskTorusGravity/setPosition.o \
    $(BUILD_DIR)/asm/Game/Gravity/DiskGravity/DiskGravity_methods.o \
    $(BUILD_DIR)/asm/Game/Gravity/DiskTorusGravity/DiskTorusGravity.o \
    $(BUILD_DIR)/asm/Game/Gravity/MapObjActorInitInfo/setupFarClipping.o \
    $(BUILD_DIR)/asm/Game/Gravity/DiskTorusGravity/DiskTorusGravity_methods.o \
    $(BUILD_DIR)/asm/Game/Gravity/GlobalGravityObj/GlobalGravityObj_all.o \
    $(BUILD_DIR)/asm/Game/Gravity/GravityFollower/GravityFollower_all.o \
    $(BUILD_DIR)/asm/Game/Gravity/GravityCreator/GravityCreator_all.o \
    $(BUILD_DIR)/asm/Game/Gravity/RailGraphNode/RailGraphNode.o \
    $(BUILD_DIR)/asm/Game/Gravity/GravityInfo/GravityInfo.o \
    $(BUILD_DIR)/asm/Game/Gravity/ParallelGravity/ParallelGravity_all.o \
    $(BUILD_DIR)/asm/Game/Gravity/PlanetGravity/PlanetGravity_all.o \
    $(BUILD_DIR)/asm/Game/Gravity/PlanetGravityManager/PlanetGravityManager_all.o \
    $(BUILD_DIR)/asm/Game/Gravity/PointGravity/PointGravity_all.o \
    $(BUILD_DIR)/asm/Game/Gravity/SegmentGravity/SegmentGravity_all.o \
    $(BUILD_DIR)/asm/Game/Gravity/WireGravity/WireGravity_all.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ActiveActorList.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ActorAnimKeeper.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ActorCameraInfo.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ActorJointCtrl.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ActorLightCtrl.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ActorPadAndCameraCtrl.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ActorStateBase.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ActorStateKeeper.o \
    $(BUILD_DIR)/asm/Game/LiveActor/AllLiveActorGroup.o \
    $(BUILD_DIR)/asm/Game/LiveActor/AnimationRandomPlayer.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Binder.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ClippingActorHolder.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ClippingActorInfo.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ClippingDirector.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ClippingGroupHolder.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ClippingJudge.o \
    $(BUILD_DIR)/asm/Game/LiveActor/DisplayListMaker.o \
    $(BUILD_DIR)/asm/Game/LiveActor/DynamicJointCtrl.o \
    $(BUILD_DIR)/asm/Game/LiveActor/EffectKeeper.o \
    $(BUILD_DIR)/asm/Game/LiveActor/FaceJointCtrl.o \
    $(BUILD_DIR)/asm/Game/LiveActor/FlashingCtrl.o \
    $(BUILD_DIR)/asm/Game/LiveActor/HitSensor.o \
    $(BUILD_DIR)/asm/Game/LiveActor/HitSensorInfo.o \
    $(BUILD_DIR)/asm/Game/LiveActor/HitSensorKeeper.o \
    $(BUILD_DIR)/asm/Game/LiveActor/IKJointCtrl.o \
    $(BUILD_DIR)/asm/Game/LiveActor/LiveActor.o \
    $(BUILD_DIR)/asm/Game/LiveActor/LiveActorFlag.o \
    $(BUILD_DIR)/asm/Game/LiveActor/LiveActorGroup.o \
    $(BUILD_DIR)/asm/Game/LiveActor/LiveActorGroupArray.o \
    $(BUILD_DIR)/asm/Game/LiveActor/LodCtrl.o \
    $(BUILD_DIR)/asm/Game/LiveActor/MaterialCtrl.o \
    $(BUILD_DIR)/asm/Game/LiveActor/MessageSensorHolder.o \
    $(BUILD_DIR)/asm/Game/LiveActor/MirrorActor.o \
    $(BUILD_DIR)/asm/Game/LiveActor/MirrorCamera.o \
    $(BUILD_DIR)/asm/Game/LiveActor/MirrorReflectionModel.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ModelManager.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ModelObj.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Nerve.o \
    $(BUILD_DIR)/asm/Game/LiveActor/PartsModel.o \
    $(BUILD_DIR)/asm/Game/LiveActor/RailRider.o \
    $(BUILD_DIR)/asm/Game/LiveActor/SensorHitChecker.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowController.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowDrawer.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowSurfaceBox.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowSurfaceCircle.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowSurfaceDrawer.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowSurfaceOval.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowVolumeBox.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowVolumeCylinder.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowVolumeDrawer.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowVolumeFlatModel.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowVolumeLine.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowVolumeModel.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowVolumeOval.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowVolumeOvalPole.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Shadow/ShadowVolumeSphere.o \
    $(BUILD_DIR)/asm/Game/LiveActor/SimpleJ3DModelDrawer.o \
    $(BUILD_DIR)/asm/Game/LiveActor/Spine.o \
    $(BUILD_DIR)/asm/Game/LiveActor/SpotMarkLight.o \
    $(BUILD_DIR)/asm/Game/LiveActor/ViewGroupCtrl.o \
    $(BUILD_DIR)/asm/Game/LiveActor/VolumeModelDrawer.o \
    $(BUILD_DIR)/asm/Game/Map/ActorAppearSwitchListener.o \
    $(BUILD_DIR)/asm/Game/Map/Air.o \
    $(BUILD_DIR)/asm/Game/Map/BezierRail.o \
    $(BUILD_DIR)/asm/Game/Map/Butterfly.o \
    $(BUILD_DIR)/asm/Game/Map/CollisionCategorizedKeeper.o \
    $(BUILD_DIR)/asm/Game/Map/CollisionCode.o \
    $(BUILD_DIR)/asm/Game/Map/CollisionDirector.o \
    $(BUILD_DIR)/asm/Game/Map/CollisionDirector.o \
    $(BUILD_DIR)/asm/Game/Map/CollisionParts.o \
    $(BUILD_DIR)/asm/Game/Map/FileSelectCameraController.o \
    $(BUILD_DIR)/asm/Game/Map/FileSelectEffect.o \
    $(BUILD_DIR)/asm/Game/Map/FileSelectFunc.o \
    $(BUILD_DIR)/asm/Game/Map/FileSelectIconID.o \
    $(BUILD_DIR)/asm/Game/Map/FileSelectItem.o \
    $(BUILD_DIR)/asm/Game/Map/FileSelectModel.o \
    $(BUILD_DIR)/asm/Game/Map/FileSelector.o \
    $(BUILD_DIR)/asm/Game/Map/FileSelectSky.o \
    $(BUILD_DIR)/asm/Game/Map/FishGroup.o \
    $(BUILD_DIR)/asm/Game/Map/Flag.o \
    $(BUILD_DIR)/asm/Game/Map/GravityDust.o \
    $(BUILD_DIR)/asm/Game/Map/GroundChecker.o \
    $(BUILD_DIR)/asm/Game/Map/GroupSwitchWatcher.o \
    $(BUILD_DIR)/asm/Game/Map/Halo.o \
    $(BUILD_DIR)/asm/Game/Map/HitInfo.o \
    $(BUILD_DIR)/asm/Game/Map/KCollision.o \
    $(BUILD_DIR)/asm/Game/Map/KCollisionPlus.o \
    $(BUILD_DIR)/asm/Game/Map/KoopaBattleMapCoinPlate.o \
    $(BUILD_DIR)/asm/Game/Map/KoopaBattleMapDamagePlate.o \
    $(BUILD_DIR)/asm/Game/Map/KoopaBattleMapPlanet.o \
    $(BUILD_DIR)/asm/Game/Map/KoopaBattleMapPlate.o \
    $(BUILD_DIR)/asm/Game/Map/KoopaBattleMapStair.o \
    $(BUILD_DIR)/asm/Game/Map/LavaShellTower.o \
    $(BUILD_DIR)/asm/Game/Map/LavaSunPlanet.o \
    $(BUILD_DIR)/asm/Game/Map/LightDataHolder.o \
    $(BUILD_DIR)/asm/Game/Map/LightDirector.o \
    $(BUILD_DIR)/asm/Game/Map/LightFunction.o \
    $(BUILD_DIR)/asm/Game/Map/LightPointCtrl.o \
    $(BUILD_DIR)/asm/Game/Map/LightZoneDataHolder.o \
    $(BUILD_DIR)/asm/Game/Map/NamePosHolder.o \
    $(BUILD_DIR)/asm/Game/Map/OceanBowl.o \
    $(BUILD_DIR)/asm/Game/Map/OceanBowlBloomDrawer.o \
    $(BUILD_DIR)/asm/Game/Map/OceanBowlPoint.o \
    $(BUILD_DIR)/asm/Game/Map/OceanHomeMapCtrl.o \
    $(BUILD_DIR)/asm/Game/Map/OceanRing.o \
    $(BUILD_DIR)/asm/Game/Map/OceanRingBloomDrawer.o \
    $(BUILD_DIR)/asm/Game/Map/OceanRingDrawer.o \
    $(BUILD_DIR)/asm/Game/Map/OceanRingPipe.o \
    $(BUILD_DIR)/asm/Game/Map/OceanRingPipeInside.o \
    $(BUILD_DIR)/asm/Game/Map/OceanRingPipeOutside.o \
    $(BUILD_DIR)/asm/Game/Map/OceanSphere.o \
    $(BUILD_DIR)/asm/Game/Map/OceanSpherePoint.o \
    $(BUILD_DIR)/asm/Game/Map/PlanetMap.o \
    $(BUILD_DIR)/asm/Game/Map/PlanetMapCreator.o \
    $(BUILD_DIR)/asm/Game/Map/PlanetMapWithoutHighModel.o \
    $(BUILD_DIR)/asm/Game/Map/QuakeEffectGenerator.o \
    $(BUILD_DIR)/asm/Game/Map/RaceManager.o \
    $(BUILD_DIR)/asm/Game/Map/RaceRail.o \
    $(BUILD_DIR)/asm/Game/Map/RailGraph.o \
    $(BUILD_DIR)/asm/Game/Map/RailGraphEdge.o \
    $(BUILD_DIR)/asm/Game/Map/RailGraphIter.o \
    $(BUILD_DIR)/asm/Game/Map/RailGraphNode.o \
    $(BUILD_DIR)/asm/Game/Map/RailPart.o \
    $(BUILD_DIR)/asm/Game/Map/ScenarioSelectStar.o \
    $(BUILD_DIR)/asm/Game/Map/SeaGull.o \
    $(BUILD_DIR)/asm/Game/Map/Sky.o \
    $(BUILD_DIR)/asm/Game/Map/SleepController.o \
    $(BUILD_DIR)/asm/Game/Map/SleepControllerHolder.o \
    $(BUILD_DIR)/asm/Game/Map/SpaceInner.o \
    $(BUILD_DIR)/asm/Game/Map/SphereSelector.o \
    $(BUILD_DIR)/asm/Game/Map/SphereSelectorHandle.o \
    $(BUILD_DIR)/asm/Game/Map/StageSwitch.o \
    $(BUILD_DIR)/asm/Game/Map/SunshadeMapHolder.o \
    $(BUILD_DIR)/asm/Game/Map/SunshadeMapParts.o \
    $(BUILD_DIR)/asm/Game/Map/SwitchSynchronizer.o \
    $(BUILD_DIR)/asm/Game/Map/SwitchWatcher.o \
    $(BUILD_DIR)/asm/Game/Map/SwitchWatcherHolder.o \
    $(BUILD_DIR)/asm/Game/Map/TimerSwitch.o \
    $(BUILD_DIR)/asm/Game/Map/WaterAreaHolder.o \
    $(BUILD_DIR)/asm/Game/Map/WaterInfo.o \
    $(BUILD_DIR)/asm/Game/Map/WaterPlant.o \
    $(BUILD_DIR)/asm/Game/Map/WaterPoint.o \
    $(BUILD_DIR)/asm/Game/Map/WaterRoad.o \
    $(BUILD_DIR)/asm/Game/Map/WhirlPoolAccelerator.o \
    $(BUILD_DIR)/asm/Game/MapObj/MapObj.o \
    $(BUILD_DIR)/asm/Game/NameObj/ModelChangableObjFactory.o \
    $(BUILD_DIR)/asm/Game/NameObj/MovementOnOffGroupHolder.o \
    $(BUILD_DIR)/asm/Game/NameObj/NameObj.o \
    $(BUILD_DIR)/asm/Game/NameObj/NameObjAdaptor.o \
    $(BUILD_DIR)/asm/Game/NameObj/NameObjArchiveListCollector.o \
    $(BUILD_DIR)/asm/Game/NameObj/NameObjCategoryList.o \
    $(BUILD_DIR)/asm/Game/NameObj/NameObjExecuteHolder.o \
    $(BUILD_DIR)/asm/Game/NameObj/NameObjFactory.o \
    $(BUILD_DIR)/asm/Game/NameObj/NameObjFinder.o \
    $(BUILD_DIR)/asm/Game/NameObj/NameObjGroup.o \
    $(BUILD_DIR)/asm/Game/NameObj/NameObjHolder.o \
    $(BUILD_DIR)/asm/Game/NameObj/NameObjListExecutor.o \
    $(BUILD_DIR)/asm/Game/NameObj/NameObjRegister.o \
    $(BUILD_DIR)/asm/Game/NPC/NPC.o \
    $(BUILD_DIR)/asm/Game/Player/Player.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudRhythmSeqParser.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudBgmTempoAdjuster.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudMeTrack.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudMeChannelMgr.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudMeSeqCtrl.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudMeSeqReader.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudMeSeqParser.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudMeTrackCallback.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudMePlayer.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudRhythmMeSystem.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudMeHandles.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudMeObject.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudChordInfo.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudRhythmHolder.o \
    $(BUILD_DIR)/asm/Game/RhythmLib/AudRhythmWrap.o \
    $(BUILD_DIR)/asm/Game/Ride/Ride.o \
    $(BUILD_DIR)/asm/Game/Scene/Scene.o \
    $(BUILD_DIR)/asm/Game/Screen/Screen.o \
    $(BUILD_DIR)/asm/Game/Speaker/Speaker.o \
    $(BUILD_DIR)/asm/Game/System/System.o \
    $(BUILD_DIR)/asm/Game/Util/Util.o \
    $(BUILD_DIR)/asm/Game/NWC24/NWC24.o \
    $(BUILD_DIR)/asm/Game/JKernel/JKernel.o \
    $(BUILD_DIR)/asm/Game/JSupport/JSupport.o \
    $(BUILD_DIR)/asm/Game/JGadget/JGadget.o \
    $(BUILD_DIR)/asm/Game/JUtility/JUtility.o \
    $(BUILD_DIR)/asm/Game/J2D/J2DGraph.o \
    $(BUILD_DIR)/asm/Game/J3D/J3DGraphBase.o \
    $(BUILD_DIR)/asm/Game/J3D/J3DGraphAnimator.o \
    $(BUILD_DIR)/asm/Game/J3D/J3DGraphLoader.o \
    $(BUILD_DIR)/asm/Game/JMath/JMath.o \
    $(BUILD_DIR)/asm/Game/JParticle/JParticle.o \
    $(BUILD_DIR)/asm/RVL/gd.o   \
    $(BUILD_DIR)/asm/RVL/kpad.o   \
    $(BUILD_DIR)/asm/RVL/thp.o   \
    $(BUILD_DIR)/asm/RVL/tpl.o   \
    $(BUILD_DIR)/asm/RVL/wenc.o   \
    $(BUILD_DIR)/asm/RVL/rso.o   \
    $(BUILD_DIR)/asm/RVL/RVLFaceLib.o   \
    $(BUILD_DIR)/asm/RevoEx/net.o   \
    $(BUILD_DIR)/asm/RevoEx/nwc24.o   \
    $(BUILD_DIR)/asm/RevoEx/vf.o   \
    $(BUILD_DIR)/asm/Game/JAudio2/JAudio2.o   \
    $(BUILD_DIR)/asm/RVL/aralt.o   \
    $(BUILD_DIR)/asm/RVL/base.o   \
    $(BUILD_DIR)/asm/RVL/os.o   \
    $(BUILD_DIR)/asm/RVL/exi.o   \
    $(BUILD_DIR)/asm/RVL/si.o   \
    $(BUILD_DIR)/asm/RVL/db.o   \
    $(BUILD_DIR)/asm/RVL/vi.o   \
    $(BUILD_DIR)/asm/RVL/mtx.o   \
    $(BUILD_DIR)/asm/RVL/gx.o   \
    $(BUILD_DIR)/asm/RVL/dvd.o   \
    $(BUILD_DIR)/asm/RVL/ai.o   \
    $(BUILD_DIR)/asm/RVL/ax.o   \
    $(BUILD_DIR)/asm/RVL/axfx.o   \
    $(BUILD_DIR)/asm/RVL/mem.o   \
    $(BUILD_DIR)/asm/RVL/code_80CA34C.o   \
    $(BUILD_DIR)/asm/RVL/dsp.o   \
    $(BUILD_DIR)/asm/RVL/nand.o   \
    $(BUILD_DIR)/asm/RVL/sc.o   \
    $(BUILD_DIR)/asm/RVL/arc.o   \
    $(BUILD_DIR)/asm/RVL/esp.o   \
    $(BUILD_DIR)/asm/RVL/ipc.o   \
    $(BUILD_DIR)/asm/RVL/fs.o   \
    $(BUILD_DIR)/asm/RVL/pad.o   \
    $(BUILD_DIR)/asm/RVL/wpad.o   \
    $(BUILD_DIR)/asm/RVL/euart.o   \
    $(BUILD_DIR)/asm/RVL/usb.o   \
    $(BUILD_DIR)/asm/RVL/wud.o   \
    $(BUILD_DIR)/asm/RVL/bte.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/Runtime/__mem.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/Runtime/__va_arg.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/Runtime/global_destructor_chain.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/Runtime/NMWException.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/Runtime/ptmf.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/Runtime/runtime.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/Runtime/__init_cpp_exceptions.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/Runtime/Gecko_ExceptionPPC.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/Runtime/GCN_mem_alloc.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/alloc.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/ansi_files.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/ansi_fp.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/arith.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/buffer_io.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/ctype.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/direct_io.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/file_io.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/FILE_POS.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/mbstring.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/mem.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/mem_funcs.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/math_api.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/misc_io.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/printf.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/scanf.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/signal.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/string.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/strtold.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/strtoul.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/wmem.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/wprintf.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/wstring.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/wchar_io.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/uart_console_io_gcn.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/abort_exit_ppc_eabi.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/math_sun.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/extras.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_acos.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_asin.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_atan2.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_fmod.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_log.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_log10.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_pow.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_rem_pio2.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/k_cos.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/k_rem_pio2.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/k_sin.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/k_tan.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_atan.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_ceil.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_copysign.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_cos.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_floor.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_frexp.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_ldexp.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_sin.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/s_tan.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_acos.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_asin.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_atan2.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_fmod.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_log10.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_pow.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/e_sqrt.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/PPC_EABI/SRC/math_ppc.o   \
    $(BUILD_DIR)/asm/MSL/MSL_C/MSL_Common_Embedded/Math/Double_precision/w_sqrt.o   \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/mainloop.o    \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/nubevent.o    \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/nubinit.o    \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/msg.o    \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/msgbuf.o    \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/serpoll.o    \
    $(BUILD_DIR)/src/runtime_libs/debugger/embedded/MetroTRK/Os/dolphin/usr_put.o \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Os/dolphin/usr_put.o \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/dispatch.o    \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/msghndlr.o    \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/support.o    \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/mutex_TRK.o  \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/notify.o     \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Processor/ppc/Generic/flush_cache.o \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/mem_TRK.o    \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/string_TRK.o \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Processor/ppc/Generic/targimpl.o \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Processor/ppc/Generic/targsupp.o \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Processor/ppc/Generic/mpc_7xx_603e.o \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Export/mslsupp.o      \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Os/dolphin/dolphin_trk.o  \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Portable/main_TRK.o   \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Os/dolphin/dolphin_trk_glue.o \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Os/dolphin/targcont.o \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Os/dolphin/target_options.o   \
    $(BUILD_DIR)/asm/runtime_libs/debugger/embedded/MetroTRK/Os/dolphin/UDP_Stubs.o    \
    $(BUILD_DIR)/asm/runtime_libs/gamedev/cust_connection/cc/exi2/GCN/EXI2_GDEV_GCN/main.o   \
    $(BUILD_DIR)/asm/runtime_libs/gamedev/cust_connection/utils/common/CircleBuffer.o   \
    $(BUILD_DIR)/asm/runtime_libs/gamedev/cust_connection/utils/gc/MWCriticalSection_gc.o  \
    $(BUILD_DIR)/asm/ndev/DebuggerDriver.o  \
    $(BUILD_DIR)/asm/ndev/exi2.o  \

CTORS_O_FILES :=                                    \
    $(BUILD_DIR)/asm/ctors.o

DTORS_O_FILES :=                                    \
    $(BUILD_DIR)/asm/dtors.o

RODATA_O_FILES :=                                   \
    $(BUILD_DIR)/asm/rodata.o

DATA_O_FILES :=                                     \
    $(BUILD_DIR)/asm/data.o

BSS_O_FILES :=                                      \
    $(BUILD_DIR)/asm/bss.o

SDATA_O_FILES :=                                    \
    $(BUILD_DIR)/asm/sdata.o

SDATA2_O_FILES :=                                   \
    $(BUILD_DIR)/asm/sdata2.o

SBSS2_O_FILES :=                                   \
    $(BUILD_DIR)/asm/sbss2.o