object_base: orig/RMGK01
object: sys/main.dol
hash: 25c5959534b3c21246c6c7e42021b916b41fb578
symbols: config/RMGK01/symbols.txt
splits: config/RMGK01/splits.txt
mw_comment_version: 14

block_relocations:
- source: .data:0x805E84F8
- source: .data:0x805E8618
- source: .text:0x804A3898
- source: .text:0x804A3910
- source: .text:0x804ED2FC
- source: .data:0x80603360
- target: .data:0x805658F0
- source: .rodata:0x8055FA7C
- source: .rodata:0x8055FA80
- source: .rodata:0x8055FA84
- source: .rodata:0x8055FA90
- source: .rodata:0x8055FA94
- source: .rodata:0x8055FA98

add_relocations:
- source: .text:0x800076B4
  type: ha
  target: "__vt__Q34nw4r2ut19TagProcessorBase<w>"
- source: .text:0x800076B8
  type: l
  target: "__vt__Q34nw4r2ut19TagProcessorBase<w>"
- source: .text:0x800089A4
  type: ha
  target: "@5713"
- source: .text:0x800089B0
  type: l
  target: "@5713"
- source: .text:0x80008BD0
  type: ha
  target: "@5713"
- source: .text:0x80008BDC
  type: l
  target: "@5713"
- source: .text:0x80008DA0
  type: ha
  target: "@5713"
- source: .text:0x80008DAC
  type: l
  target: "@5713"
- source: .text:0x80008F74
  type: ha
  target: "@5713"
- source: .text:0x80008F84
  type: l
  target: "@5713"
- source: .text:0x80009144
  type: ha
  target: "@5713"
- source: .text:0x80009150
  type: l
  target: "@5713"
- source: .text:0x80009A24
  type: ha
  target: "@5713"
- source: .text:0x80009A34
  type: l
  target: "@5713"

