#ifndef BTE_HCI_DEFS_H
#define BTE_HCI_DEFS_H

/* Original source:
 * bluedroid <android.googlesource.com/platform/external/bluetooth/bluedroid>
 * stack/include/hcidefs.h
 */

/******************************************************************************
 *
 *  Copyright (C) 1999-2012 Broadcom Corporation
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at:
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 ******************************************************************************/

/* Includes changes by muff1n1634 */

/*******************************************************************************
 * headers
 */

#include "data_types.h"

/*******************************************************************************
 * macros
 */

#define HCI_PER_INQ_MIN_MIN_PERIOD					2
#define HCI_PER_INQ_MAX_MIN_PERIOD					65534

#define HCI_PER_INQ_MIN_MAX_PERIOD					3
#define HCI_PER_INQ_MAX_MAX_PERIOD					65535

#define HCI_MAX_INQUIRY_LENGTH						48

#define HCI_DEF_SCAN_TYPE							HCI_SCAN_TYPE_STANDARD

#define HCI_MIN_PAGESCAN_INTERVAL					18
#define HCI_MAX_PAGESCAN_INTERVAL					4096
#define HCI_DEF_PAGESCAN_INTERVAL					2048

#define HCI_MIN_PAGESCAN_WINDOW						18
#define HCI_MAX_PAGESCAN_WINDOW						4096
#define HCI_DEF_PAGESCAN_WINDOW						HCI_MIN_PAGESCAN_WINDOW

#define HCI_MIN_INQUIRYSCAN_INTERVAL				18
#define HCI_MAX_INQUIRYSCAN_INTERVAL				4096
#define HCI_DEF_INQUIRYSCAN_INTERVAL				2048

#define HCI_MIN_INQUIRYSCAN_WINDOW					18
#define HCI_MAX_INQUIRYSCAN_WINDOW					4096
#define HCI_DEF_INQUIRYSCAN_WINDOW					HCI_MIN_INQUIRYSCAN_WINDOW

#define HCI_DEFAULT_INACT_TOUT						32000

#define HCI_INVALID_HANDLE							0xffff

#define HCI_COMMAND_SIZE							255

#define HCIC_PREAMBLE_SIZE							3
#define HCI_DATA_PREAMBLE_SIZE						4

#define LOCAL_BR_EDR_CONTROLLER_ID					0

#define HCI_BRCM_ACL_PRIORITY_PARAM_SIZE			3
#define HCI_BRCM_ACL_PRIORITY_LOW					0
#define HCI_BRCM_ACL_PRIORITY_HIGH					255

#define HCI_DM1_PACKET_SIZE							17
#define HCI_DH1_PACKET_SIZE							27
#define HCI_DM3_PACKET_SIZE							121
#define HCI_DH3_PACKET_SIZE							183
#define HCI_DM5_PACKET_SIZE							224
#define HCI_DH5_PACKET_SIZE							339

#define HCI_EDR2_DH1_PACKET_SIZE					54
#define HCI_EDR2_DH3_PACKET_SIZE					367
#define HCI_EDR2_DH5_PACKET_SIZE					679
#define HCI_EDR3_DH1_PACKET_SIZE					83
#define HCI_EDR3_DH3_PACKET_SIZE					552
#define HCI_EDR3_DH5_PACKET_SIZE					1021

#define HCI_NUM_FEATURE_BYTES						8

// Pre-expanded to reduce noise Because I Said So.
#define HCI_3_SLOT_PACKETS_SUPPORTED(x)				((x)[0] & (1 << 0))
#define HCI_5_SLOT_PACKETS_SUPPORTED(x)				((x)[0] & (1 << 1))

#define HCI_SWITCH_SUPPORTED(x)						((x)[0] & (1 << 5))
#define HCI_HOLD_MODE_SUPPORTED(x)					((x)[0] & (1 << 6))
#define HCI_SNIFF_MODE_SUPPORTED(x)					((x)[0] & (1 << 7))
#define HCI_PARK_MODE_SUPPORTED(x)					((x)[1] & (1 << 0))

#define HCI_SCO_LINK_SUPPORTED(x)					((x)[1] & (1 << 3))
#define HCI_HV2_PACKETS_SUPPORTED(x)				((x)[1] & (1 << 4))
#define HCI_HV3_PACKETS_SUPPORTED(x)				((x)[1] & (1 << 5))

#define HCI_LMP_U_LAW_SUPPORTED(x)					((x)[1] & (1 << 6))
#define HCI_LMP_A_LAW_SUPPORTED(x)					((x)[1] & (1 << 7))
#define HCI_LMP_CVSD_SUPPORTED(x)					((x)[2] & (1 << 0))

#define HCI_EDR_ACL_2MPS_SUPPORTED(x)				((x)[3] & (1 << 1))
#define HCI_EDR_ACL_3MPS_SUPPORTED(x)				((x)[3] & (1 << 2))

#define HCI_LMP_INTERLACED_INQ_SCAN_SUPPORTED(x)	((x)[3] & (1 << 4))
#define HCI_LMP_INTERLACED_PAGE_SCAN_SUPPORTED(x)	((x)[3] & (1 << 5))
#define HCI_LMP_INQ_RSSI_SUPPORTED(x)				((x)[3] & (1 << 6))
#define HCI_ESCO_EV3_SUPPORTED(x)					((x)[3] & (1 << 7))
#define HCI_ESCO_EV4_SUPPORTED(x)					((x)[4] & (1 << 0))
#define HCI_ESCO_EV5_SUPPORTED(x)					((x)[4] & (1 << 1))

#define HCI_LMP_AFH_CAP_SLAVE_SUPPORTED(x)			((x)[4] & (1 << 3))
#define HCI_LMP_AFH_CLASS_SLAVE_SUPPORTED(x)		((x)[4] & (1 << 4))

#define HCI_3_SLOT_EDR_ACL_SUPPORTED(x)				((x)[4] & (1 << 7))
#define HCI_5_SLOT_EDR_ACL_SUPPORTED(x)				((x)[5] & (1 << 0))

#define HCI_LMP_AFH_CAP_MASTER_SUPPORTED(x)			((x)[5] & (1 << 3))
#define HCI_LMP_AFH_CLASS_MASTER_SUPPORTED(x)		((x)[5] & (1 << 4))
#define HCI_EDR_ESCO_2MPS_SUPPORTED(x)				((x)[5] & (1 << 5))
#define HCI_EDR_ESCO_3MPS_SUPPORTED(x)				((x)[5] & (1 << 6))
#define HCI_3_SLOT_EDR_ESCO_SUPPORTED(x)			((x)[5] & (1 << 7))

/*******************************************************************************
 * types
 */

enum
{
	HCI_PROTO_VERSION_2_0	= 3,
};

enum
{
	HCI_GROUP_LINK_CONTROL_CMDS			= 1 << 10,
	HCI_GROUP_LINK_POLICY_CMDS			= 2 << 10,
	HCI_GROUP_HOST_CONT_BASEBAND_CMDS	= 3 << 10,
	HCI_GROUP_INFORMATIONAL_PARAMS		= 4 << 10,
	HCI_GROUP_STATUS_PARAMS				= 5 << 10,
	HCI_GROUP_TESTING_CMDS				= 6 << 10,
	HCI_GROUP_VENDOR_SPECIFIC			= 0x3f << 10,
};

enum
{
	HCI_COMMAND_NONE				= 0,

	/* Link control commands */

	HCI_INQUIRY						= HCI_GROUP_LINK_CONTROL_CMDS | 1,
	HCI_INQUIRY_CANCEL				= HCI_GROUP_LINK_CONTROL_CMDS | 2,
	HCI_PERIODIC_INQUIRY_MODE		= HCI_GROUP_LINK_CONTROL_CMDS | 3,
	HCI_EXIT_PERIODIC_INQUIRY_MODE	= HCI_GROUP_LINK_CONTROL_CMDS | 4,
	HCI_CREATE_CONNECTION			= HCI_GROUP_LINK_CONTROL_CMDS | 5,
	HCI_DISCONNECT					= HCI_GROUP_LINK_CONTROL_CMDS | 6,
	HCI_ADD_SCO_CONNECTION			= HCI_GROUP_LINK_CONTROL_CMDS | 7,
	HCI_CREATE_CONNECTION_CANCEL	= HCI_GROUP_LINK_CONTROL_CMDS | 8,
	HCI_ACCEPT_CONNECTION_REQUEST	= HCI_GROUP_LINK_CONTROL_CMDS | 9,
	HCI_REJECT_CONNECTION_REQUEST	= HCI_GROUP_LINK_CONTROL_CMDS | 10,
	HCI_LINK_KEY_REQUEST_REPLY		= HCI_GROUP_LINK_CONTROL_CMDS | 11,
	HCI_LINK_KEY_REQUEST_NEG_REPLY	= HCI_GROUP_LINK_CONTROL_CMDS | 12,
	HCI_PIN_CODE_REQUEST_REPLY		= HCI_GROUP_LINK_CONTROL_CMDS | 13,
	HCI_PIN_CODE_REQUEST_NEG_REPLY	= HCI_GROUP_LINK_CONTROL_CMDS | 14,
	HCI_CHANGE_CONN_PACKET_TYPE		= HCI_GROUP_LINK_CONTROL_CMDS | 15,

	HCI_AUTHENTICATION_REQUESTED	= HCI_GROUP_LINK_CONTROL_CMDS | 17,

	HCI_SET_CONN_ENCRYPTION			= HCI_GROUP_LINK_CONTROL_CMDS | 19,

	HCI_CHANGE_CONN_LINK_KEY		= HCI_GROUP_LINK_CONTROL_CMDS | 21,

	HCI_MASTER_LINK_KEY				= HCI_GROUP_LINK_CONTROL_CMDS | 23,

	HCI_RMT_NAME_REQUEST			= HCI_GROUP_LINK_CONTROL_CMDS | 25,
	HCI_RMT_NAME_REQUEST_CANCEL		= HCI_GROUP_LINK_CONTROL_CMDS | 26,
	HCI_READ_RMT_FEATURES			= HCI_GROUP_LINK_CONTROL_CMDS | 27,
	HCI_READ_RMT_EXT_FEATURES		= HCI_GROUP_LINK_CONTROL_CMDS | 28,
	HCI_READ_RMT_VERSION_INFO		= HCI_GROUP_LINK_CONTROL_CMDS | 29,
	HCI_READ_RMT_CLOCK_OFFSET		= HCI_GROUP_LINK_CONTROL_CMDS | 31,
	HCI_READ_LMP_HANDLE				= HCI_GROUP_LINK_CONTROL_CMDS | 32,

	HCI_SETUP_ESCO_CONNECTION		= HCI_GROUP_LINK_CONTROL_CMDS | 40,
	HCI_ACCEPT_ESCO_CONNECTION		= HCI_GROUP_LINK_CONTROL_CMDS | 41,
	HCI_REJECT_ESCO_CONNECTION		= HCI_GROUP_LINK_CONTROL_CMDS | 42,

	/* Link policy commands */

	HCI_HOLD_MODE					= HCI_GROUP_LINK_POLICY_CMDS | 1,

	HCI_SNIFF_MODE					= HCI_GROUP_LINK_POLICY_CMDS | 3,
	HCI_EXIT_SNIFF_MODE				= HCI_GROUP_LINK_POLICY_CMDS | 4,
	HCI_PARK_MODE					= HCI_GROUP_LINK_POLICY_CMDS | 5,
	HCI_EXIT_PARK_MODE				= HCI_GROUP_LINK_POLICY_CMDS | 6,
	HCI_QOS_SETUP					= HCI_GROUP_LINK_POLICY_CMDS | 7,

	HCI_ROLE_DISCOVERY				= HCI_GROUP_LINK_POLICY_CMDS | 9,

	HCI_SWITCH_ROLE					= HCI_GROUP_LINK_POLICY_CMDS | 11,
	HCI_READ_POLICY_SETTINGS		= HCI_GROUP_LINK_POLICY_CMDS | 12,
	HCI_WRITE_POLICY_SETTINGS		= HCI_GROUP_LINK_POLICY_CMDS | 13,
	HCI_READ_DEF_POLICY_SETTINGS	= HCI_GROUP_LINK_POLICY_CMDS | 14,
	HCI_WRITE_DEF_POLICY_SETTINGS	= HCI_GROUP_LINK_POLICY_CMDS | 15,
	HCI_FLOW_SPECIFICATION			= HCI_GROUP_LINK_POLICY_CMDS | 16,
	HCI_SNIFF_SUB_RATE				= HCI_GROUP_LINK_POLICY_CMDS | 17,

	/* Cont baseband commands */

	HCI_SET_EVENT_MASK				= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 1,

	HCI_RESET						= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 3,

	HCI_SET_EVENT_FILTER			= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 5,

	HCI_FLUSH						= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 8,
	HCI_READ_PIN_TYPE				= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 9,
	HCI_WRITE_PIN_TYPE				= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 10,
	HCI_CREATE_NEW_UNIT_KEY			= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 11,

	HCI_READ_STORED_LINK_KEY		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 13,

	HCI_WRITE_STORED_LINK_KEY		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 17,
	HCI_DELETE_STORED_LINK_KEY		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 18,
	HCI_CHANGE_LOCAL_NAME			= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 19,
	HCI_READ_LOCAL_NAME				= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 20,
	HCI_READ_CONN_ACCEPT_TOUT		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 21,
	HCI_WRITE_CONN_ACCEPT_TOUT		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 22,
	HCI_READ_PAGE_TOUT				= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 23,
	HCI_WRITE_PAGE_TOUT				= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 24,
	HCI_READ_SCAN_ENABLE			= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 25,
	HCI_WRITE_SCAN_ENABLE			= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 26,
	HCI_READ_PAGESCAN_CFG			= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 27,
	HCI_WRITE_PAGESCAN_CFG			= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 28,
	HCI_READ_INQUIRYSCAN_CFG		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 29,
	HCI_WRITE_INQUIRYSCAN_CFG		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 30,
	HCI_READ_AUTHENTICATION_ENABLE	= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 31,
	HCI_WRITE_AUTHENTICATION_ENABLE	= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 32,
	HCI_READ_ENCRYPTION_MODE		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 33,
	HCI_WRITE_ENCRYPTION_MODE		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 34,
	HCI_READ_CLASS_OF_DEVICE		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 35,
	HCI_WRITE_CLASS_OF_DEVICE		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 36,
	HCI_READ_VOICE_SETTINGS			= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 37,
	HCI_WRITE_VOICE_SETTINGS		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 38,
	HCI_READ_AUTO_FLUSH_TOUT		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 39,
	HCI_WRITE_AUTO_FLUSH_TOUT		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 40,
	HCI_READ_NUM_BCAST_REXMITS		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 41,
	HCI_WRITE_NUM_BCAST_REXMITS		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 42,
	HCI_READ_HOLD_MODE_ACTIVITY		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 43,
	HCI_WRITE_HOLD_MODE_ACTIVITY	= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 44,
	HCI_READ_TRANSMIT_POWER_LEVEL	= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 45,
	HCI_READ_SCO_FLOW_CTRL_ENABLE	= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 46,
	HCI_WRITE_SCO_FLOW_CTRL_ENABLE	= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 47,

	HCI_SET_HC_TO_HOST_FLOW_CTRL	= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 49,

	HCI_HOST_BUFFER_SIZE			= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 51,

	HCI_HOST_NUM_PACKETS_DONE		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 53,
	HCI_READ_LINK_SUPER_TOUT		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 54,
	HCI_WRITE_LINK_SUPER_TOUT		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 55,
	HCI_READ_NUM_SUPPORTED_IAC		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 56,
	HCI_READ_CURRENT_IAC_LAP		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 57,
	HCI_WRITE_CURRENT_IAC_LAP		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 58,
	HCI_READ_PAGESCAN_PERIOD_MODE	= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 59,
	HCI_WRITE_PAGESCAN_PERIOD_MODE	= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 60,
	HCI_READ_PAGESCAN_MODE			= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 61,
	HCI_WRITE_PAGESCAN_MODE			= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 62,
	HCI_SET_AFH_CHANNELS			= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 63,

	HCI_READ_INQSCAN_TYPE			= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 66,
	HCI_WRITE_INQSCAN_TYPE			= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 67,
	HCI_READ_INQUIRY_MODE			= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 68,
	HCI_WRITE_INQUIRY_MODE			= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 69,
	HCI_READ_PAGESCAN_TYPE			= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 70,
	HCI_WRITE_PAGESCAN_TYPE			= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 71,
	HCI_READ_AFH_ASSESSMENT_MODE	= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 72,
	HCI_WRITE_AFH_ASSESSMENT_MODE	= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 73,

	HCI_READ_EXT_INQ_RESPONSE		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 81,
	HCI_WRITE_EXT_INQ_RESPONSE		= HCI_GROUP_HOST_CONT_BASEBAND_CMDS | 82,

	/* Informational parameter commands */

	HCI_READ_LOCAL_VERSION_INFO		= HCI_GROUP_INFORMATIONAL_PARAMS | 1,
	HCI_READ_LOCAL_SUPPORTED_CMDS	= HCI_GROUP_INFORMATIONAL_PARAMS | 2,
	HCI_READ_LOCAL_FEATURES			= HCI_GROUP_INFORMATIONAL_PARAMS | 3,
	HCI_READ_LOCAL_EXT_FEATURES		= HCI_GROUP_INFORMATIONAL_PARAMS | 4,
	HCI_READ_BUFFER_SIZE			= HCI_GROUP_INFORMATIONAL_PARAMS | 5,

	HCI_READ_COUNTRY_CODE			= HCI_GROUP_INFORMATIONAL_PARAMS | 7,

	HCI_READ_BD_ADDR				= HCI_GROUP_INFORMATIONAL_PARAMS | 9,

	/* Status parameter commands */

	HCI_READ_FAILED_CONN_COUNT		= HCI_GROUP_STATUS_PARAMS | 1,
	HCI_RESET_FAILED_CONN_COUNT		= HCI_GROUP_STATUS_PARAMS | 2,
	HCI_GET_LINK_QUALITY			= HCI_GROUP_STATUS_PARAMS | 3,

	HCI_READ_RSSI					= HCI_GROUP_STATUS_PARAMS | 5,
	HCI_READ_AFH_CH_MAP				= HCI_GROUP_STATUS_PARAMS | 6,
	HCI_READ_CLOCK					= HCI_GROUP_STATUS_PARAMS | 7,

	/* Testing commands */

	HCI_READ_LOOPBACK_MODE			= HCI_GROUP_TESTING_CMDS | 1,
	HCI_WRITE_LOOPBACK_MODE			= HCI_GROUP_TESTING_CMDS | 2,
	HCI_ENABLE_DEV_UNDER_TEST_MODE	= HCI_GROUP_TESTING_CMDS | 3,

	/* Vendor-specific commands */

	HCI_BRCM_SET_ACL_PRIORITY		= HCI_GROUP_VENDOR_SPECIFIC | 87,
};

enum
{
	HCI_INQUIRY_COMP_EVT				= 1,
	HCI_INQUIRY_RESULT_EVT				= 2,
	HCI_CONNECTION_COMP_EVT				= 3,
	HCI_CONNECTION_REQUEST_EVT			= 4,
	HCI_DISCONNECTION_COMP_EVT			= 5,
	HCI_AUTHENTICATION_COMP_EVT			= 6,
	HCI_RMT_NAME_REQUEST_COMP_EVT		= 7,
	HCI_ENCRYPTION_CHANGE_EVT			= 8,
	HCI_CHANGE_CONN_LINK_KEY_EVT		= 9,
	HCI_MASTER_LINK_KEY_COMP_EVT		= 10,
	HCI_READ_RMT_FEATURES_COMP_EVT		= 11,
	HCI_READ_RMT_VERSION_COMP_EVT		= 12,
	HCI_QOS_SETUP_COMP_EVT				= 13,
	HCI_COMMAND_COMPLETE_EVT			= 14,
	HCI_COMMAND_STATUS_EVT				= 15,
	HCI_HARDWARE_ERROR_EVT				= 16,
	HCI_FLUSH_OCCURED_EVT				= 17,
	HCI_ROLE_CHANGE_EVT					= 18,
	HCI_NUM_COMPL_DATA_PKTS_EVT			= 19,
	HCI_MODE_CHANGE_EVT					= 20,
	HCI_RETURN_LINK_KEYS_EVT			= 21,
	HCI_PIN_CODE_REQUEST_EVT			= 22,
	HCI_LINK_KEY_REQUEST_EVT			= 23,
	HCI_LINK_KEY_NOTIFICATION_EVT		= 24,
	HCI_LOOPBACK_COMMAND_EVT			= 25,
	HCI_DATA_BUF_OVERFLOW_EVT			= 26,
	HCI_MAX_SLOTS_CHANGED_EVT			= 27,
	HCI_READ_CLOCK_OFF_COMP_EVT			= 28,
	HCI_CONN_PKT_TYPE_CHANGE_EVT		= 29,
	HCI_QOS_VIOLATION_EVT				= 30,
	HCI_PAGE_SCAN_MODE_CHANGE_EVT		= 31,
	HCI_PAGE_SCAN_REP_MODE_CHNG_EVT		= 32,
	HCI_FLOW_SPECIFICATION_COMP_EVT		= 33,
	HCI_INQUIRY_RSSI_RESULT_EVT			= 34,
	HCI_READ_RMT_EXT_FEATURES_COMP_EVT	= 35,

	HCI_ESCO_CONNECTION_COMP_EVT		= 44,
	HCI_ESCO_CONNECTION_CHANGED_EVT		= 45,
	HCI_SNIFF_SUB_RATE_EVT				= 46,
	HCI_EXTENDED_INQUIRY_RESULT_EVT		= 47,
	HCI_ENCRYPTION_KEY_REFRESH_COMP_EVT	= 48,
	HCI_IO_CAPABILITY_REQUEST_EVT		= 49,
	HCI_IO_CAPABILITY_RESPONSE_EVT		= 50,
	HCI_USER_CONFIRMATION_REQUEST_EVT	= 51,
	HCI_USER_PASSKEY_REQUEST_EVT		= 52,
	HCI_REMOTE_OOB_DATA_REQUEST_EVT		= 53,
	HCI_SIMPLE_PAIRING_COMPLETE_EVT		= 54,
	HCI_LINK_SUPER_TOUT_CHANGED_EVT		= 56,
	HCI_ENHANCED_FLUSH_COMPLETE_EVT		= 57,

	HCI_USER_PASSKEY_NOTIFY_EVT			= 59,
	HCI_KEYPRESS_NOTIFY_EVT				= 60,
	HCI_RMT_HOST_SUP_FEAT_NOTIFY_EVT	= 61,

	HCI_VENDOR_SPECIFIC_EVT				= 255
};

typedef UINT8 tHCI_STATUS;
enum
{
	HCI_SUCCESS									= 0,

	HCI_ERR_HW_FAILURE							= 3,
	HCI_ERR_PAGE_TIMEOUT						= 4,
	HCI_ERR_AUTH_FAILURE						= 5,
	HCI_ERR_KEY_MISSING							= 6,

	HCI_ERR_MAX_NUM_OF_CONNECTIONS				= 9,

	HCI_ERR_CONNECTION_EXISTS					= 11,

	HCI_ERR_HOST_REJECT_RESOURCES				= 13,
	HCI_ERR_HOST_REJECT_SECURITY				= 14,
	HCI_ERR_HOST_REJECT_DEVICE					= 15,

	HCI_ERR_UNSUPPORTED_VALUE					= 17,

	HCI_ERR_PEER_USER							= 19,

	HCI_ERR_REPEATED_ATTEMPTS					= 23,
	HCI_ERR_PAIRING_NOT_ALLOWED					= 24,

	HCI_ERR_UNSPECIFIED							= 31,

	HCI_ERR_LMP_ERR_TRANS_COLLISION				= 35,

	HCI_ERR_ENCRY_MODE_NOT_ACCEPTABLE			= 37,
	HCI_ERR_UNIT_KEY_USED						= 38,

	HCI_ERR_PAIRING_WITH_UNIT_KEY_NOT_SUPPORTED	= 41,

	HCI_ERR_ROLE_SWITCH_PENDING					= 50,
};

enum
{
	HCI_PKT_TYPES_MASK_NO_2_DH1	= 1 << 1,
	HCI_PKT_TYPES_MASK_NO_3_DH1	= 1 << 2,
	HCI_PKT_TYPES_MASK_DM1		= 1 << 3,
	HCI_PKT_TYPES_MASK_DH1		= 1 << 4,

	HCI_PKT_TYPES_MASK_NO_2_DH3	= 1 << 8,
	HCI_PKT_TYPES_MASK_NO_3_DH3	= 1 << 9,
	HCI_PKT_TYPES_MASK_DM3		= 1 << 10,
	HCI_PKT_TYPES_MASK_DH3		= 1 << 11,
	HCI_PKT_TYPES_MASK_NO_2_DH5	= 1 << 12,
	HCI_PKT_TYPES_MASK_NO_3_DH5	= 1 << 13,
	HCI_PKT_TYPES_MASK_DM5		= 1 << 14,
	HCI_PKT_TYPES_MASK_DH5		= 1 << 15,
};

enum
{
	HCI_ESCO_PKT_TYPES_MASK_HV1			= 1 << 0,
	HCI_ESCO_PKT_TYPES_MASK_HV2			= 1 << 1,
	HCI_ESCO_PKT_TYPES_MASK_HV3			= 1 << 2,
	HCI_ESCO_PKT_TYPES_MASK_EV3			= 1 << 3,
	HCI_ESCO_PKT_TYPES_MASK_EV4			= 1 << 4,
	HCI_ESCO_PKT_TYPES_MASK_EV5			= 1 << 5,
	HCI_ESCO_PKT_TYPES_MASK_NO_2_EV3	= 1 << 6,
	HCI_ESCO_PKT_TYPES_MASK_NO_3_EV3	= 1 << 7,
	HCI_ESCO_PKT_TYPES_MASK_NO_2_EV5	= 1 << 8,
	HCI_ESCO_PKT_TYPES_MASK_NO_3_EV5	= 1 << 9,
};

// TODO: can condense into true and false
enum
{
	HCI_CR_CONN_NOT_ALLOW_SWITCH,
	HCI_CR_CONN_ALLOW_SWITCH
};

enum
{
	HCI_ROLE_MASTER	= 0,
	HCI_ROLE_SLAVE	= 1,
};

enum
{
	HCI_MODE_ACTIVE,
	HCI_MODE_HOLD,
	HCI_MODE_SNIFF,
	HCI_MODE_PARK,
};

enum
{
	HCI_PAGE_SCAN_REP_MODE_R1	= 1,
};

enum
{
	HCI_MANDATARY_PAGE_SCAN_MODE	= 0,
};

enum
{
	HCI_SCAN_TYPE_STANDARD	= 0,
};

typedef UINT16 tHCI_LINK_POLICY;
enum
{
	HCI_DISABLE_ALL_LM_MODES		= 0,
	HCI_ENABLE_MASTER_SLAVE_SWITCH	= 1 << 0,
	HCI_ENABLE_HOLD_MODE			= 1 << 1,
	HCI_ENABLE_SNIFF_MODE			= 1 << 2,
	HCI_ENABLE_PARK_MODE			= 1 << 3,
};

enum
{
	HCI_FILTER_INQUIRY_RESULT	= 1,
	HCI_FILTER_CONNECTION_SETUP	= 2,
};

enum
{
	HCI_FILTER_COND_NEW_DEVICE,
	HCI_FILTER_COND_DEVICE_CLASS,
	HCI_FILTER_COND_BD_ADDR,
};

enum
{
	HCI_DO_AUTO_ACCEPT_CONNECT	= 2,
};

enum
{
	HCI_PIN_TYPE_FIXED	= 1,
};

typedef UINT8 tHCI_SCAN_MODE;
enum
{
	HCI_NO_SCAN_ENABLED			= 0,
	HCI_INQUIRY_SCAN_ENABLED	= 1 << 0,
	HCI_PAGE_SCAN_ENABLED		= 1 << 1,
};

enum
{
	HCI_ENCRYPT_MODE_DISABLED		= 0,
	HCI_ENCRYPT_MODE_POINT_TO_POINT	= 1,
};

enum
{
	HCI_LINK_TYPE_SCO,
	HCI_LINK_TYPE_ACL,
	HCI_LINK_TYPE_ESCO,
};

enum
{
	LMP_COMPID_BROADCOM	= 15,
	LMP_COMPID_ZEEVO	= 18, // What
};

typedef UINT16 tHCI_HANDLE;
#define HCI_HANDLE_INVALID	0xffff

#endif // BTE_HCI_DEFS_H
