#include "Game/GameAudio/AudTalkSoundData.hpp"
#include <JSystem/JAudio2/JAISound.hpp>

namespace {
    JAISoundID cTalkSoundList[] = {
        // 0x00
        -1,       //
        0xA001C,  // SE_SV_KINOPIO_TALK_HEY
        0xA001D,  // SE_SV_KINOPIO_TALK_YAHOO
        0xA001E,  // SE_SV_KINOPIO_TALK_ANGRY
        0xA001F,  // SE_SV_KINOPIO_TALK_SAD
        0xA0020,  // SE_SV_KINOPIO_TALK_HAPPY
        0xA0052,  // SE_SV_KINOPIO_TALK_SLEEP
        0xA0024,  // SE_SV_RABBIT_TALK_NORMAL
        0xA0025,  // SE_SV_RABBIT_TALK_CAUGHT
        0xA0026,  // SE_SV_RABBIT_TALK_THATS
        0xA0082,  // SE_SV_RABBIT_TALK_HELP
        0xA0083,  // SE_SV_RABBIT_TALK_THANKS
        0xA0028,  // SE_SV_PENGUIN_L_TALK_NORMAL
        0xA0029,  // SE_SV_PENGUIN_L_TALK_PLEASED
        0xA0045,  // SE_SV_PENGUIN_L_TALK_NG
        0xA0044,  // SE_SV_PENGUIN_L_TALK_QUESTION
        // 0x10
        0xA006B,  // SE_SV_PENGUIN_L_TALK_DISTANT
        0xA0077,  // SE_SV_PENGUIN_L_TALK_NORMAL_L
        0xA0078,  // SE_SV_PENGUIN_L_TALK_PLEASED_L
        0xA007D,  // SE_SV_PENGUIN_L_TALK_NG_L
        0xA007C,  // SE_SV_PENGUIN_L_TALK_QUESTION_L
        0xA007E,  // SE_SV_PENGUIN_L_TALK_OH
        0xA002D,  // SE_SV_PENGUIN_S_TALK_NORMAL
        0xA002E,  // SE_SV_PENGUIN_S_TALK_GLAD
        0xA0040,  // SE_SV_PENGUIN_S_TALK_GLAD_HIGH
        0xA002F,  // SE_SV_PENGUIN_S_TALK_ANGRY
        0xA0030,  // SE_SV_PENGUIN_S_TALK_SAD
        0xA0031,  // SE_SV_PENGUIN_S_TALK_HAPPY
        0xA0041,  // SE_SV_PENGUIN_S_TALK_STRONG
        0xA0042,  // SE_SV_PENGUIN_S_TALK_NORMAL_W
        0xA0035,  // SE_SV_PENGUIN_S_TALK_GREET
        0xA0036,  // SE_SV_PENGUIN_S_TALK_WIN
        // 0x20
        0xA0037,  // SE_SV_PENGUIN_S_TALK_LOSE
        0xA003A,  // SE_SV_PENGUIN_S_TALK_OUCH
        0xA003C,  // SE_SV_PENGUIN_ACE_TALK_NORMAL
        0xA003D,  // SE_SV_PENGUIN_ACE_TALK_GREET
        0xA003E,  // SE_SV_PENGUIN_ACE_TALK_WIN
        0xA003F,  // SE_SV_PENGUIN_ACE_TALK_LOSE
        0xA0033,  // SE_SV_SYATI_TALK_NORMAL
        0xA0046,  // SE_SV_SYATI_TALK_RING_MEET
        0xA0047,  // SE_SV_SYATI_TALK_RING_WIN
        0xA0048,  // SE_SV_SYATI_TALK_RING_LOSE
        0xA0049,  // SE_SV_SYATI_TALK_PHAN_MEET
        0xA004A,  // SE_SV_SYATI_TALK_PHAN_WIN
        0xA004B,  // SE_SV_SYATI_TALK_PHAN_LOSE
        0xA004C,  // SE_SV_PENGUIN_SS_HAPPY
        0xA004D,  // SE_SV_PENGUIN_SS_GREET
        0xA004E,  // SE_SV_PENGUIN_SS_DAMAGE
        // 0x30
        0xA004F,  // SE_SV_PENGUIN_SS_DISAPPOINTED
        0xA0050,  // SE_SV_PENGUIN_SS_PLEASED
        0xA0051,  // SE_SV_PENGUIN_SS_ANGRY
        0xA0053,  // SE_SV_HONEYBEE_TALK_NORMAL
        0xA0054,  // SE_SV_HONEYBEE_TALK_CONFUSION
        0xA0055,  // SE_SV_HONEYBEE_TALK_QUESTION
        0xA0056,  // SE_SV_HONEYBEE_TALK_SURPRISE
        0xA0057,  // SE_SV_HONEYBEE_TALK_ORDER
        0xA0058,  // SE_SV_HONEYBEE_TALK_LAUGH
        0xA0061,  // SE_SV_HONEYBEE_TALK_GLAD
        0xA005A,  // SE_SV_TICO_TALK_NORMAL
        0xA005B,  // SE_SV_TICO_TALK_GLAD
        0xA005C,  // SE_SV_TICO_TALK_ANGRY
        0xA005D,  // SE_SV_TICO_TALK_SAD
        0xA005E,  // SE_SV_TICO_TALK_HAPPY
        -1,       //
        // 0x40
        0xA0060,  // SE_SV_TICO_TICO
        0xA0080,  // SE_SV_TICO_TALK_CONFUSION
        0xA0081,  // SE_SV_TICO_TALK_THANKS
        0xA0062,  // SE_SV_LUIGI_MARIO
        0xA0063,  // SE_SV_LUIGI_FRIGHTENED
        0xA0064,  // SE_SV_LUIGI_SORRY
        0xA0065,  // SE_SV_LUIGI_THANKS
        0xA0066,  // SE_SV_LUIGI_HEY
        0x7000A,  // SE_DM_KINOPIO_CHIEF
        0xA0067,  // SE_SV_TERERACER_TALK_NORMAL
        0xA0068,  // SE_SV_TERERACER_TALK_LAUGH
        0xA0069,  // SE_SV_TERERACER_TALK_REGRET
        0xA006C,  // SE_SV_CARETAKER_SHORT
        0xA006D,  // SE_SV_CARETAKER_NORMAL
        0xA006E,  // SE_SV_CARETAKER_LONG
        0xA006F,  // SE_SV_CARETAKER_REPEAT
        // 0x50
        -1,       //
        -1,       //
        -1,       //
        -1,       //
        -1,       //
        0xA0085,  // SE_SV_HONEYQUEEN_TALK_SURPRISE
        0xA0086,  // SE_SV_HONEYQUEEN_TALK_THANKS
        0xA0087,  // SE_SV_HONEYQUEEN_TALK_WORRY
        0xA0088,  // SE_SV_HONEYQUEEN_TALK_AA
        0xA0089,  // SE_SV_HONEYQUEEN_TALK_AN
        0xA008A,  // SE_SV_HONEYQUEEN_TALK_UFUFU
        0xA008B,  // SE_SV_KINOPIO_TALK_WELCOME
        0xA008C,  // SE_SV_KINOPIO_TALK_BEAUTIFUL
        0xA008D,  // SE_SV_KINOPIO_TALK_SURPRISE
        0xA008E,  // SE_SV_KINOPIO_PUHA
        0xA008F,  // SE_SV_KINOPIO_TALK_HELP
        // 0x60
        0xA0090,  // SE_SV_KINOPIO_TALK_TREMBLE
        0xA0091,  // SE_SV_KINOPIO_TALK_STRONG
        0xA0092,  // SE_SV_KINOPIO_TALK_LOOK_OUT
        0xA0093,  // SE_SV_KINOPIO_TALK_WOW
        0xA0094,  // SE_SV_PEACH_TALK_HELP
        0xA0095,  // SE_SV_ROSETTA_TALK_NORMAL
        0xA0096,  // SE_SV_ROSETTA_TALK_SURPRISE
        0xA0097,  // SE_SV_ROSETTA_TALK_SMILE
        0xA0099,  // SE_SV_ROSETTA_TALK_WAITING
        0xA009A,  // SE_SV_ROSETTA_TALK_WORRIED
        0xA009C,  // SE_SV_TICOFAT_TALK_NORMAL
        0xA009D,  // SE_SV_TICOFAT_TALK_KITA
        0xA009E,  // SE_SV_TICOFAT_META
        0xA00A0,  // SE_SV_KINOPIOCHIEF_TALK_HEY
        0xA00A1,  // SE_SV_KINOPIOCHIEF_TALK_LAUGH
        0xA00A2,  // SE_SV_KINOPIOCHIEF_TALK_YAHOO
        // 0x70
        0xA00A6,  // SE_SV_TICOFAT_TALK_GIVE_ME
        0xA00A7,  // SE_SV_TICOFAT_TALK_WAKU
        0xA00AB,  // SE_SV_BUTLER_TALK_SURPRISE
        0xA00AC,  // SE_SV_BUTLER_TALK_AGREE
        0xA00AD,  // SE_SV_BUTLER_TALK_WORRIED
        0xA00AE,  // SE_SV_BUTLER_TALK_NORMAL
        0xA00B1,  // SE_SV_PENGUIN_OLD_GREET
        0xA00B2,  // SE_SV_PENGUIN_OLD_GRAD
        0xA00B3,  // SE_SV_PENGUIN_OLD_SAD
        0xA00B5,  // SE_SV_PENGUIN_OLD_NORMAL
        0xA00B6,  // SE_SV_LUIGI_TALK_TIRE
        0xA00B7,  // SE_SV_LUIGI_TALK_YAH
        0xA00B8,  // SE_SV_LUIGI_TALK_HELP
        0xA00C0,  // SE_SV_LUIGI_TALK_OH_YEAH
        0xA00C1,  // SE_SV_BUTLER_TALK_QUESTION
        0xA00C2,  // SE_SV_ROSETTA_TALK_LETS_START
        // 0x80
        0xA00C3,  // SE_SV_ROSETTA_TALK_SOMUCH_TODAY
        0xA00C4,  // SE_SV_PENGUIN_OLD_SCARED
        0xA00C5,  // SE_SV_TICOCOMET_TALK_PURURIN
        0xA00C6,  // SE_SV_TICOCOMET_TALK_DON
        0xA00C8,  // SE_SV_KINOPIO_TALK_WATER
        0xA00C9,  // SE_SV_KINOPIO_TALK_HEY_SNOR
        0xA00CA,  // SE_SV_KINOPIO_TALK_SAD_SNOR
        0xA00C7,  // SE_SV_TICOSHOP_TALK_PIKARIN
        0xA00CB,  // SE_SV_TICOSHOP_TALK_KITA
        0x300B7,  // SE_BV_KOOPAJR_TLK_PROVOKE
        0x300B8,  // SE_BV_KOOPA_TLK_LAUGH
        0x300B9,  // SE_BV_KOOPA_TLK_NORMAL
        0x300BA,  // SE_BV_KOOPA_TLK_REGRET
        0x300BB,  // SE_BV_KOOPA_TLK_CALM
        0x300BC,  // SE_BV_KOOPA_TLK_EXCITED
        0xA00D0,  // SE_SV_TICOFAT_TALK_YEAH
        // 0x90
        0xA00D1,  // SE_SV_ROSETTA_TALK_THATS_ALL
        0xA00D4,  // SE_SV_CARE_TAKER_TRAMPLE
        0xA00E3,  // SE_SV_KINOPIO_NO_MAIL
        0xA00E4,  // SE_SV_KINOPIO_LOOK_MAIL
        0xA00E5,  // SE_SV_KINOPIO_TALK_SHOUT
        0xA00E8,  // SE_SV_KINOPIOCHIEF_TALK_EVASIVE
        0xA00E6,  // SE_SV_ROSETTA_TALK_SO
        0xA00E7,  // SE_SV_ROSETTA_TALK_LOOK
        0xA00EB,  // SE_SM_SIGNBOARD_HEY
        0xA0100,  // SE_SV_ROSETTA_TALK_PLEASE
        0xA0101,  // SE_SV_ROSETTA_TALK_FU
        0xA0102,  // SE_SV_ROSETTA_TALK_TROUBLE
        0xA0103,  // SE_SV_ROSETTA_TALK_SIGH
        0xA0104,  // SE_SV_ROSETTA_TALK_QUESTION
        0xA0105,  // SE_SV_ROSETTA_TALK_SMILE_EP_B
        0xA010E,  // SE_SV_HONEYBEE_TALK_SLEEP
        // 0xA0
        0xA0110,  // SE_SV_KINOPIO_TALK_TIRED
        0xA0111,  // SE_SV_CARETAKER_ANGRY_FAST
    };
};

JAISoundID AudTalkSoundData::getSoundIDFromTalkSoundNo(u8 soundNo) {
    if ((s32)soundNo >= ARRAY_SIZE(::cTalkSoundList)) {
        return -1;
    }
    return ::cTalkSoundList[soundNo];
}
