#pragma once

#include "Game/Ride/BigBubble.hpp"
#include "Game/Ride/Creeper.hpp"
#include "Game/Ride/Fluff.hpp"
#include "Game/Ride/FluffWind.hpp"
#include "Game/Ride/JumpBranch.hpp"
#include "Game/Ride/Plant.hpp"
#include "Game/Ride/Pole.hpp"
#include "Game/Ride/SlingShooter.hpp"
#include "Game/Ride/SpaceCocoon.hpp"
#include "Game/Ride/SphereController.hpp"
#include "Game/Ride/SurfRay.hpp"
#include "Game/Ride/SurfRayTutorial.hpp"
#include "Game/Ride/SwingRope.hpp"
#include "Game/Ride/Tamakoro.hpp"
#include "Game/Ride/TamakoroTutorial.hpp"
#include "Game/Ride/Trapeze.hpp"
