#include "Game/System/StationedFileInfo.hpp"

namespace MR {
    const StationedFileInfo cStationedFileInfo[] = {
        {
            StationedFileInfo::HEAP_TYPE_NAPA,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_MARIO,
            "/ObjectData/MarioAnime.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_NAPA,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_MARIO,
            "/ObjectData/BoneMario.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_NAPA,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_MARIO,
            "/ObjectData/Mario.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_NAPA,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_MARIO,
            "/ObjectData/MarioFace.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_NAPA,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_MARIO,
            "/ObjectData/MarioShadow.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_MARIO,
            "/ObjectData/MarioTornado.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_NAPA,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LUIGI,
            "/ObjectData/MarioAnime.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_NAPA,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LUIGI,
            "/ObjectData/BoneLuigi.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_NAPA,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LUIGI,
            "/ObjectData/Luigi.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_NAPA,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LUIGI,
            "/ObjectData/LuigiFace.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_NAPA,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LUIGI,
            "/ObjectData/LuigiShadow.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LUIGI,
            "/ObjectData/LuigiTornado.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_NAPA,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/MarioHandL.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_NAPA,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/MarioHandR.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_NAPA,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/MarioDummyItem.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_NAPA,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/IceStep.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_NAPA,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/MarioFireBall.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/MarineSnow.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/MarioFreezeIce.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/SpinTico.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/Coin.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/KinokoOneUp.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/KinokoLifeUp.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/PowerUpLife.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/Kinoko.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/SearchLightCone.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/ShadowVolumeCylinder.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/ShadowVolumeSphere.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/ShadowVolumeOval.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/StarPiece.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/WaterColumn.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/YellowChip.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/StarPointerBlur.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/PowerStar.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/Koura.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/RailPoint.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/ScenarioSelect.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/BackButton.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/ScenarioSelectSky.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/MapTicoIcon.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/GalaxyNamePlate.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/IconComet.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/MapTitle.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/GalaxyDetail.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/ResultWindow.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/MapGalaxyIcon.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/IconMario.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/MapButton.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/MapDomeIcon.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/AllStarList.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/SuperSpinDriver.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/PauseMenu.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/MapGalaxyBG.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/MapGrandGalaxy.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/SpinDriverPath.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/MarioHair.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/VROrbit.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/Butler.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/GalaxyInfoTexture.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/Butterfly.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroNamePlateData.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/SuperSpinDriverShadow.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/StarPieceTargetMeter.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/KinopioGoodsPickel.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/SignBoard.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/TicoLow.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/CutBush.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/CrystalBox.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/TicoMiddle.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/DemoAstroReturn.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroMapBoard.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/KinopioLow.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/SuperSpinDriverEmpty.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/PowerupFoo.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/KinopioGoodsMailBag.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/WoodBox.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/TicoFatGoodsStarPiece.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/KinopioMiddle.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/WoodBoxBreak.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/CrystalBoxBreak.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/KinopioGoodsLight.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroDecoratePartsA.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/KinopioGoodsRucksack.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/MiniSurprisedGalaxy.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroStarPlateObservatory.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroStarPlateWell.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroStarPlateBedRoom.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/WarpPod.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/RosettaLow.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroCore.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroDecoratePartsGearA.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/Tico.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroStarPlateMachine.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/TicoFat.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroStarPlateKitchen.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroRotateStepB.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroParking.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroStarPlateTower.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/RosettaMiddle.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/Kinopio.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroBaseCenterTop.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/GrandStar.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroBaseKitchen.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroBaseCenterA.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroLibrary.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroRotateStepA.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroBaseCenterB.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroBaseC.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroDomeEntranceMachine.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroDomeEntranceBedRoom.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroDomeEntranceObservatory.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroDomeEntranceKitchen.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroChildRoom.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/TicoCometGoodsStar.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/LuigiNPCLow.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/LuigiNPCMiddle.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/TicoComet.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/GlareGlow.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/GlareLine.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/LensFlare.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/Sun.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/GalaxyInfo.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/GalaxySelect.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/GCaptureRibbon.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/MiniatureGalaxySelect.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroDomeDemoCamera.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/MiniatureGalaxyShadow.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroDomeCometBloom.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/GCaptureTarget.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroDomeDemoAstroGalaxy.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/AstroDomeComet.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/MiniatureGalaxyUnknown.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/DemoSheet.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/LightData.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/NPCData.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/AirMeter.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/BatteryInfo.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/BlueChipCounter.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/CameraInfo.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/CinemaFrame.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/CinemaSuper.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/CoinCounter.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/CollectCounter.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/CometScreenFilter.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/CommandStream.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/DPDPointer.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/DPDPointerSub.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/DPDPointerNumber.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/FlyMeter.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/GetStar.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/HitPointMeter.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/SuddenDeathMeter.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/IconAButton.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/IconSave.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/InformationWindow.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/OneUp.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/PlayerLeft.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/PointerGuidance.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/PurpleCoinCounter.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/RetryButton.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/SelectButton.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/SignBoardBalloon.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/StageTitle.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/StarCounter.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/StarPieceCounter.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/SysInfoWindow.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/SysInfoWindowMini.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/TalkBalloonEvent.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/TalkBalloonStretch.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/TalkBalloonLetter.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/TooBad.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/WipeKoopa.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/WipeRing.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/YellowChipCounter.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_FILE,
            "/HomeButton2/SpeakerSe.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_FILE,
            "/HomeButton2/home.csv",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_FILE,
            "/HomeButton2/config.txt",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT,
            "/ParticleData/Effect.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT,
            "/StageData/ObjNameTable.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/ErrorMessageImage.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/PlanetMapDataTable.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/TimeLimit.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/TimeUp.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_FILE,
            "/ModuleData/HomeButtonMenuWrapperRSO.rso",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_FILE,
            "/ModuleData/product.sel",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE,
            "/ObjectData/SaveIconBanner.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_FILE,
            "/LayoutData/HomeButton.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT,
            "/LayoutData/Font.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT,
            "/MessageData/Message.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_GDDR,
            StationedFileInfo::LOAD_TYPE_MOUNT_RESOURCE_LAYOUT,
            "/LayoutData/GameOver.arc",
        },
        {
            StationedFileInfo::HEAP_TYPE_NAPA,
            StationedFileInfo::LOAD_TYPE_FILE,
            nullptr,
        },
    };

    const StationedFileInfo* getStationedFileInfoTable() {
        return cStationedFileInfo;
    }
};  // namespace MR
