#pragma once

#include <JSystem/JGeometry/TVec.hpp>

class BckCtrlData;
class CubeCameraArea;
class HitSensor;
class LiveActor;
class MarioActor;
class RushEndInfo;
class Triangle;

class MarioAccess {
public:
    static void getTakePos(TVec3f*);
    static bool isOnActor(const LiveActor*);
    static bool isOnGround(u32);
    static bool isHipDropFalling();
    static bool isHipDropLand();
    static bool isSwingAction();
    static bool isInRush();
    static bool isSquat();
    static bool isParalyzing();
    static bool isTeresaDisappear();
    static bool isFlying();
    static bool isNeedBrakingCamera();
    static CubeCameraArea* getCameraCubeCode();
    static bool isSwimming();
    static bool isSkating();
    static Triangle* getGroundingPolygon(u32);
    static Triangle* getShadowingPolygon();
    static f32 getShadowHeight();
    static void forceKill(u32, u32);
    static bool isOnPress();
    static bool isDisableFpView();
    static bool isFpViewChangingFailure();
    static void stopFpView();
    static void noticeDashChance();
    static void setWalkingResist(f32);
    static void forceFly(const TVec3f&, const TVec3f&, s32);
    static void setJumpVec(const TVec3f&);
    static void forceJump(const TVec3f&, u32);
    static void freeJump(const TVec3f&, u32);
    static void tornadoJump();
    static void tornadoJumpMini();
    static void becomeNormalJumpStatus();
    static void setFrontVecKeepUp(const TVec3f&, u16);
    static void setFrontVecTarget(const TVec3f&, u16);
    static void getThrowVec(TVec3f*);
    static void setTrans(const TVec3f&, u16);
    static void endRush(const RushEndInfo*);
    static void incLife(u32);
    static bool isConfrontDeath();
    static void addStarPiece();
    static void getStarPieceDirect();
    static MtxPtr getJointMtx(const char*);
    static TVec3f* getVelocity();
    static TVec3f* getLastMove();
    static void hide();
    static void show();
    static HitSensor* getTakingSensor();
    static void dropTakingActor();
    static void killTakingActor();
    static f32 getAnimationFrameMax();
    static void changeAnimationJ(const char*);
    static void changeAnimationE(const char*, s32);
    static void changeAnimationE(const char*, const char*);
    static void changeAnimationE(const char*, const BckCtrlData&);
    static void keepCurrentAnimation();
    static void progressAnimation();
    static const char* getCurrentBckName();
    static void setAnimationBlendWeight(const f32*);
    static void setSpot(f32, u32);
    static void offControl();
    static bool isOffControl();
    static void onControl(bool);
    static void setStateWait();
    static void startTalk(const LiveActor*);
    static void endTalk();
    static void readyRemoteDemo();
    static void onFollowDemo();
    static void setBaseMtx(MtxPtr);
    static MtxPtr getBaseMtx();
    static bool calcSpinPullVelocity(TVec3f*, const TVec3f&);
    static void tryCoinPull();
    static void addVelocity(const TVec3f&);
    static void addVelocityFromArea(const TVec3f&);
    static bool isOnWaterSurface();
    static void calcWorldPadDir(TVec3f*, f32, f32);
    static void preventRush();
    static MarioActor* getPlayerActor();
    static void validateSensor();
    static void incOxygen(u32);
    static void scatterStarPiece(u32);
    static void startDownWipe();
    static void readyDemo();
    static void endRemoteDemo(const RushEndInfo*);
    static bool isInWaterMode();
    static void changeItemStatus(s32);
};
